language: php
dist: trusty
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install xvfb curl wget xfonts-75dpi
  - sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo mv wkhtmltox/bin/* /usr/local/bin
  - composer install
