language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/sabre-cs-fixer fix . --dry-run --diff

before_script:
  - phpenv config-rm xdebug.ini; true
  - composer install

cache:
  directories:
    - $HOME/.composer/cache
