dolibarr: TraceableDB Class Reference
TraceableDB Class Reference
TraceableDB class.
Public Member Functions
__construct ($db)
Constructor.
ifsql ($test, $resok, $resko)
Format a SQL IF.
fetch_row ($resultset)
Return datas as an array.
idate ($param, $gm='tzserver')
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
lasterrno ()
Return last error code.
begin ($textinlog='')
Start transaction.
DDLCreateDb ($database, $charset='', $collation='', $owner='')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
getVersionArray ()
Return version of database server into an array.
affected_rows ($resultset)
Return the number o flines into the result of a request INSERT, DELETE or UPDATE.
error ()
Return description of last error.
DDLListTables ($database, $table='')
List tables into a database.
lastquery ()
Return last request executed with query()
order ($sortfield=null, $sortorder=null)
Define sort criteria of request.
decrypt ($value)
Decrypt sensitive data in database.
fetch_array ($resultset)
Return datas as an array.
lasterror ()
Return last error label.
escape ($stringtoencode)
Escape a string to insert data.
escapeforlike ($stringtoencode)
Escape a string to insert data into a like.
last_insert_id ($tab, $fieldid='rowid')
Get last ID after an insert INSERT.
getPathOfRestore ()
Return full path of restore program.
rollback ($log='')
Cancel a transaction and go back to initial data values.
query ($query, $usesavepoint=0, $type='auto', $result_mode=0)
Execute a SQL request and return the resultset.
connect ($host, $login, $passwd, $name, $port=0)
Connexion to server.
plimit ($limit=0, $offset=0)
Define limits and offset of request.
getServerParametersValues ($filter='')
Return value of server parameters.
getServerStatusValues ($filter='')
Return value of server status.
getDefaultCollationDatabase ()
Return collation used in database.
num_rows ($resultset)
Return number of lines for result of a SELECT.
getPathOfDump ()
Return full path of dump program.
getDriverInfo ()
Return version of database client driver.
errno ()
Return generic error code of last operation.
DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys=null, $fulltext_keys=null, $keys=null)
Create a table into database.
DDLDropTable ($table)
Drop a table into database.
getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
DDLAddField ($table, $field_name, $field_desc, $field_position="")
Create a new field into table.
DDLDropField ($table, $field_name)
Drop a field from table.
DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
getListOfCollation ()
Return list of available collation that can be used for database.
DDLDescTable ($table, $field="")
Return a pointer of line with description of a table or field.
getVersion ()
Return version of database server.
getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
jdate ($string, $gm=false)
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with TZ+1 and gmt=0 19700101020000 -> 7200 whaterver is TZ if gmt=1.
encrypt ($fieldorvalue, $withQuotes=1)
Encrypt sensitive data in database Warning: This function includes the escape and add the SQL simple quotes on strings.
commit ($log='')
Validate a database transaction.
DDLInfoTable ($table)
List information of columns into a table.
free ($resultset=null)
Free last resultset used.
close ()
Close database connexion.
lastqueryerror ()
Return last query in error.
DDLGetConnectId ()
Return connexion ID.
fetch_object ($resultset)
Returns the current line (as an object) for the resultset cursor.
select_db ($database)
Select a database.
Public Member Functions inherited from DoliDB
prefix ()
Return the DB prefix.
hintindex ($nameofindex)
Return SQL string to force an index.
regexpsql ($subject, $pattern, $sqlstring=false)
Format a SQL REGEXP.
sanitize ($stringtosanitize, $allowsimplequote=0, $allowsequals=0)
Sanitize a string for SQL forging.
getRow ($sql)
Return first result from query as object Note : This method executes a given SQL query and retrieves the first row of results as an object.
getRows ($sql)
Return all results from query as an array of objects Note : This method executes a given SQL query and retrieves all row of results as an array of objects.
Public Member Functions inherited from Database
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
sanitize ($stringtosanitize)
Sanitize a string for SQL forging.
Static Public Member Functions
static convertSQLFromMysql ($line, $type='ddl')
Convert a SQL request in Mysql syntax to native syntax.
Public Attributes
const LABEL = ''
@const Database label
const VERSIONMIN = ''
@const Version min database
Protected Member Functions
startTracing ()
Start query tracing.
endTracing ($sql, $resql)
End query tracing.
Detailed Description
TraceableDB class.
Used to log queries into DebugBar
Definition at line 10 of file TraceableDB.php.
Constructor & Destructor Documentation
__construct()
TraceableDB::__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 46 of file TraceableDB.php.
References db, and type.
Member Function Documentation
affected_rows()
TraceableDB::affected_rows ($resultset)
Return the number o flines into the result of a request INSERT, DELETE or UPDATE.
Parameters
resource $resultset Curseur de la requete voulue
Returns
int Number of lines
See also
num_rows()
Implements Database.
Definition at line 159 of file TraceableDB.php.
References db.
begin()
TraceableDB::begin ($textinlog = '')
Start transaction.
Parameters
string $textinlog Add a small text into log. '' by default.
Returns
int 1 if transaction successfuly opened or already opened, 0 if error
Reimplemented from DoliDB.
Definition at line 108 of file TraceableDB.php.
References db.
close()
TraceableDB::close ()
Close database connexion.
Returns
boolean True if disconnect successfull, false otherwise
See also
connect()
Implements Database.
Definition at line 661 of file TraceableDB.php.
References db.
commit()
TraceableDB::commit ($log = '')
Validate a database transaction.
Parameters
string $log Add more log to default log line
Returns
int 1 if validation is OK or transaction level no started, 0 if ERROR
Reimplemented from DoliDB.
Definition at line 628 of file TraceableDB.php.
connect()
TraceableDB::connect ($host, $login, $passwd, $name, $port = 0)
Connexion to server.
Parameters
string $host database server host
string $login login
string $passwd password
string $name name of database (not used for mysql, used for pgsql)
int $port Port of database server
Returns
resource Database access handler
See also
close()
Implements Database.
Definition at line 367 of file TraceableDB.php.
convertSQLFromMysql()
static TraceableDB::convertSQLFromMysql ($line, $type = 'ddl') static
Convert a SQL request in Mysql syntax to native syntax.
Parameters
string $line SQL request line to convert
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
Returns
string SQL request line converted
Implements Database.
Definition at line 146 of file TraceableDB.php.
DDLAddField()
TraceableDB::DDLAddField ($table, $field_name, $field_desc, $field_position = "")
Create a new field into table.
Parameters
string $table Name of table
string $field_name Name of field to add
string $field_desc Tableau associatif de description du champ a inserer[nom du parametre][valeur du parametre]
string $field_position Optionnel ex.: "after champtruc"
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 507 of file TraceableDB.php.
DDLCreateDb()
TraceableDB::DDLCreateDb ($database, $charset = '', $collation = '', $owner = '')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
Parameters
string $database Database name to create
string $charset Charset used to store data
string $collation Charset used to sort data
string $owner Username of database owner
Returns
resource resource defined if OK, null if KO
Implements Database.
Definition at line 124 of file TraceableDB.php.
References db.
DDLCreateTable()
TraceableDB::DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys = null, $fulltext_keys = null, $keys = null)
Create a table into database.
Parameters
string $table Name of table
array $fields Tableau associatif [nom champ][tableau des descriptions]
string $primary_key Nom du champ qui sera la clef primaire
string $type Type de la table
array $unique_keys Tableau associatifs Nom de champs qui seront clef unique => valeur
array $fulltext_keys Tableau des Nom de champs qui seront indexes en fulltext
array $keys Tableau des champs cles noms => valeur
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 472 of file TraceableDB.php.
DDLCreateUser()
TraceableDB::DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
Parameters
string $dolibarr_main_db_host Ip serveur
string $dolibarr_main_db_user Nom user a creer
string $dolibarr_main_db_pass Mot de passe user a creer
string $dolibarr_main_db_name Database name where user must be granted
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 588 of file TraceableDB.php.
References db.
DDLDescTable()
TraceableDB::DDLDescTable ($table, $field = "")
Return a pointer of line with description of a table or field.
Parameters
string $table Name of table
string $field Optionnel : Name of field if we want description of field
Returns
resource Resource
Implements Database.
Definition at line 554 of file TraceableDB.php.
DDLDropField()
TraceableDB::DDLDropField ($table, $field_name)
Drop a field from table.
Parameters
string $table Name of table
string $field_name Name of field to drop
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 519 of file TraceableDB.php.
DDLDropTable()
TraceableDB::DDLDropTable ($table)
Drop a table into database.
Parameters
string $table Name of table
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 483 of file TraceableDB.php.
DDLGetConnectId()
TraceableDB::DDLGetConnectId ()
Return connexion ID.
Returns
string Id connexion
Implements Database.
Definition at line 681 of file TraceableDB.php.
References db.
DDLInfoTable()
TraceableDB::DDLInfoTable ($table)
List information of columns into a table.
Parameters
string $table Name of table
Returns
array Array with inforation on table
Implements Database.
Definition at line 639 of file TraceableDB.php.
DDLListTables()
TraceableDB::DDLListTables ($database, $table = '')
List tables into a database.
Parameters
string $database Name of database
string $table Nmae of table filter ('xxx')
Returns
array List of tables in an array
Implements Database.
Definition at line 182 of file TraceableDB.php.
DDLUpdateField()
TraceableDB::DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
Parameters
string $table Name of table
string $field_name Name of field to modify
string $field_desc Array with description of field format
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 532 of file TraceableDB.php.
decrypt()
TraceableDB::decrypt ($value)
Decrypt sensitive data in database.
Parameters
string $value Value to decrypt
Returns
string Decrypted value if used
Implements Database.
Definition at line 215 of file TraceableDB.php.
encrypt()
TraceableDB::encrypt ($fieldorvalue, $withQuotes = 1)
Encrypt sensitive data in database Warning: This function includes the escape and add the SQL simple quotes on strings.
Parameters
string $fieldorvalue Field name or value to encrypt
int $withQuotes Return string including the SQL simple quotes. This param must always be 1 (Value 0 is bugged and deprecated).
Returns
string XXX(field) or XXX('value') or field or 'value'
Implements Database.
Definition at line 617 of file TraceableDB.php.
References db.
endTracing()
TraceableDB::endTracing ($sql, $resql) protected
End query tracing.
Parameters
string $sql query string
string $resql query result
Returns
void
Definition at line 339 of file TraceableDB.php.
Referenced by query().
errno()
TraceableDB::errno ()
Return generic error code of last operation.
Returns
string Error code (Exemples: DB_ERROR_TABLE_ALREADY_EXISTS, DB_ERROR_RECORD_ALREADY_EXISTS...)
Implements Database.
Definition at line 455 of file TraceableDB.php.
References db.
error()
TraceableDB::error ()
Return description of last error.
Returns
string Error text
Implements Database.
Definition at line 170 of file TraceableDB.php.
References db.
escape()
TraceableDB::escape ($stringtoencode)
Escape a string to insert data.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implements Database.
Definition at line 249 of file TraceableDB.php.
References db.
escapeforlike()
TraceableDB::escapeforlike ($stringtoencode)
Escape a string to insert data into a like.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implements Database.
Definition at line 260 of file TraceableDB.php.
fetch_array()
TraceableDB::fetch_array ($resultset)
Return datas as an array.
Parameters
resource $resultset Resultset of request
Returns
array Array
Implements Database.
Definition at line 227 of file TraceableDB.php.
References db.
fetch_object()
TraceableDB::fetch_object ($resultset)
Returns the current line (as an object) for the resultset cursor.
Parameters
resource | Connection $resultset Handler of the desired SQL request
Returns
Object Object result line or false if KO or end of cursor
Implements Database.
Definition at line 693 of file TraceableDB.php.
References db.
fetch_row()
TraceableDB::fetch_row ($resultset)
Return datas as an array.
Parameters
resource $resultset Resultset of request
Returns
array Array
Implements Database.
Definition at line 73 of file TraceableDB.php.
References db.
free()
TraceableDB::free ($resultset = null)
Free last resultset used.
Parameters
resource $resultset Fre cursor
Returns
void
Implements Database.
Definition at line 650 of file TraceableDB.php.
References db.
getDefaultCharacterSetDatabase()
TraceableDB::getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
Returns
string Charset
Implements Database.
Definition at line 574 of file TraceableDB.php.
References db.
getDefaultCollationDatabase()
TraceableDB::getDefaultCollationDatabase ()
Return collation used in database.
Returns
string Collation value
Implements Database.
Definition at line 411 of file TraceableDB.php.
References db.
getDriverInfo()
TraceableDB::getDriverInfo ()
Return version of database client driver.
Returns
string Version string
Implements Database.
Definition at line 445 of file TraceableDB.php.
References db.
getListOfCharacterSet()
TraceableDB::getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
Returns
array List of Charset
Implements Database.
Definition at line 493 of file TraceableDB.php.
References db.
getListOfCollation()
TraceableDB::getListOfCollation ()
Return list of available collation that can be used for database.
Returns
array List of Collation
Implements Database.
Definition at line 542 of file TraceableDB.php.
References db.
getPathOfDump()
TraceableDB::getPathOfDump ()
Return full path of dump program.
Returns
string Full path of dump program
Implements Database.
Definition at line 435 of file TraceableDB.php.
References db.
getPathOfRestore()
TraceableDB::getPathOfRestore ()
Return full path of restore program.
Returns
string Full path of restore program
Implements Database.
Definition at line 284 of file TraceableDB.php.
References db.
getServerParametersValues()
TraceableDB::getServerParametersValues ($filter = '')
Return value of server parameters.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implements Database.
Definition at line 390 of file TraceableDB.php.
getServerStatusValues()
TraceableDB::getServerStatusValues ($filter = '')
Return value of server status.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implements Database.
Definition at line 401 of file TraceableDB.php.
getVersion()
TraceableDB::getVersion ()
Return version of database server.
Returns
string Version string
Implements Database.
Definition at line 564 of file TraceableDB.php.
References db.
getVersionArray()
TraceableDB::getVersionArray ()
Return version of database server into an array.
Returns
array Version array
Reimplemented from DoliDB.
Definition at line 134 of file TraceableDB.php.
References db.
idate()
TraceableDB::idate ($param, $gm = 'tzserver')
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
Function to use to build INSERT, UPDATE or WHERE predica
Parameters
int $param Date TMS to convert
mixed $gm 'gmt'=Input informations are GMT values, 'tzserver'=Local to server TZ
Returns
string Date in a string YYYY-MM-DD HH:MM:SS
Reimplemented from DoliDB.
Definition at line 87 of file TraceableDB.php.
ifsql()
TraceableDB::ifsql ($test, $resok, $resko)
Format a SQL IF.
Parameters
string $test Test string (example: 'cd.statut=0', 'field IS NULL')
string $resok resultat si test egal
string $resko resultat si test non egal
Returns
string SQL string
Reimplemented from DoliDB.
Definition at line 61 of file TraceableDB.php.
jdate()
TraceableDB::jdate ($string, $gm = false)
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with TZ+1 and gmt=0 19700101020000 -> 7200 whaterver is TZ if gmt=1.
Parameters
string $string Date in a string (YYYYMMDDHHMMSS, YYYYMMDD, YYYY-MM-DD HH:MM:SS)
bool $gm 1=Input informations are GMT values, otherwise local to server TZ
Returns
int|string Date TMS or ''
Reimplemented from DoliDB.
Definition at line 603 of file TraceableDB.php.
last_insert_id()
TraceableDB::last_insert_id ($tab, $fieldid = 'rowid')
Get last ID after an insert INSERT.
Parameters
string $tab Table name concerned by insert. Ne sert pas sous MySql mais requis pour compatibilite avec Postgresql
string $fieldid Field name
Returns
int Id of row
Implements Database.
Definition at line 273 of file TraceableDB.php.
lasterrno()
TraceableDB::lasterrno ()
Return last error code.
Returns
string lasterrno
Reimplemented from DoliDB.
Definition at line 97 of file TraceableDB.php.
References db.
lasterror()
TraceableDB::lasterror ()
Return last error label.
Returns
string lasterror
Reimplemented from DoliDB.
Definition at line 238 of file TraceableDB.php.
References db.
lastquery()
TraceableDB::lastquery ()
Return last request executed with query()
Returns
string Last query
Reimplemented from DoliDB.
Definition at line 192 of file TraceableDB.php.
References db.
lastqueryerror()
TraceableDB::lastqueryerror ()
Return last query in error.
Returns
string lastqueryerror
Reimplemented from DoliDB.
Definition at line 671 of file TraceableDB.php.
References db.
num_rows()
TraceableDB::num_rows ($resultset)
Return number of lines for result of a SELECT.
Parameters
resource $resultset Resulset of requests
Returns
int Nb of lines
See also
affected_rows()
Implements Database.
Definition at line 424 of file TraceableDB.php.
References db.
order()
TraceableDB::order ($sortfield = null, $sortorder = null)
Define sort criteria of request.
Parameters
string $sortfield List of sort fields
string $sortorder Sort order
Returns
string String to provide syntax of a sort sql string
Reimplemented from DoliDB.
Definition at line 204 of file TraceableDB.php.
plimit()
TraceableDB::plimit ($limit = 0, $offset = 0)
Define limits and offset of request.
Parameters
int $limit Maximum number of lines returned (-1=conf->liste_limit, 0=no limit)
int $offset Numero of line from where starting fetch
Returns
string String with SQL syntax to add a limit and offset
Reimplemented from DoliDB.
Definition at line 379 of file TraceableDB.php.
query()
TraceableDB::query ($query, $usesavepoint = 0, $type = 'auto', $result_mode = 0)
Execute a SQL request and return the resultset.
Parameters
string $query SQL query string
int $usesavepoint 0=Default mode, 1=Run a savepoint before and a rollback to savepoint if error (this allow to have some request with errors inside global transactions). Note that with Mysql, this parameter is not used as Myssql can already commit a transaction even if one request is in error, without using savepoints.
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
int $result_mode Result mode
Returns
resource Resultset of answer
Implements Database.
Definition at line 310 of file TraceableDB.php.
References $resql, db, endTracing(), and startTracing().
rollback()
TraceableDB::rollback ($log = '')
Cancel a transaction and go back to initial data values.
Parameters
string $log Add more log to default log line
Returns
resource|int 1 if cancelation is ok or transaction not open, 0 if error
Reimplemented from DoliDB.
Definition at line 295 of file TraceableDB.php.
select_db()
TraceableDB::select_db ($database)
Select a database.
Parameters
string $database Name of database
Returns
boolean true if OK, false if KO
Implements Database.
Definition at line 706 of file TraceableDB.php.
References db.
startTracing()
TraceableDB::startTracing () protected
Start query tracing.
Returns
void
Definition at line 326 of file TraceableDB.php.
Referenced by query().
The documentation for this class was generated from the following file:
htdocs/debugbar/class/TraceableDB.php