dolibarr: DolibarrCollector Class Reference
DolibarrCollector Class Reference
DolibarrCollector class.
Public Member Functions
getName ()
Return collector name.
collect ()
Return collected data.
getWidgets ()
Return widget settings.
getAssets ()
Return collector assests.
Protected Member Functions
getDatabaseInfo ()
Return database info as an HTML string.
getDolibarrInfo ()
Return dolibarr info as an HTML string.
getMailInfo ()
Return mail info as an HTML string.
Detailed Description
DolibarrCollector class.
Definition at line 12 of file DolibarrCollector.php.
Member Function Documentation
collect()
DolibarrCollector::collect ()
Return collected data.
Returns
array Array
Definition at line 29 of file DolibarrCollector.php.
getAssets()
DolibarrCollector::getAssets ()
Return collector assests.
Returns
array Array
Definition at line 149 of file DolibarrCollector.php.
References dol_buildpath().
getDatabaseInfo()
DolibarrCollector::getDatabaseInfo () protected
Return database info as an HTML string.
Returns
string HTML string
Definition at line 39 of file DolibarrCollector.php.
Referenced by getWidgets().
getDolibarrInfo()
DolibarrCollector::getDolibarrInfo () protected
Return dolibarr info as an HTML string.
Returns
string HTML string
Definition at line 59 of file DolibarrCollector.php.
Referenced by getWidgets().
getMailInfo()
DolibarrCollector::getMailInfo () protected
Return mail info as an HTML string.
Returns
string HTML string
Definition at line 84 of file DolibarrCollector.php.
Referenced by getWidgets().
getName()
DolibarrCollector::getName ()
Return collector name.
Returns
string Name
Definition at line 19 of file DolibarrCollector.php.
getWidgets()
DolibarrCollector::getWidgets ()
Return widget settings.
Returns
array Array
Definition at line 108 of file DolibarrCollector.php.
References getDatabaseInfo(), getDolibarrInfo(), and getMailInfo().
The documentation for this class was generated from the following file:
htdocs/debugbar/class/DataCollector/DolibarrCollector.php