dolibarr: htdocs/support/inc.php File Reference
inc.php File Reference
File that define environment for support pages.
Functions
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
pHeader ($soutitre, $next, $action='none')
Show HTML header.
pFooter ($nonext=0, $setuplang='')
Print HTML footer.
Variables
$conf db = new stdClass()
API class for accounts.
Detailed Description
File that define environment for support pages.
Definition in file inc.php.
Function Documentation
conf()
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
Parameters
string $dolibarr_main_document_root Root directory of Dolibarr bin files
Returns
int <0 if KO, >0 if OK
Definition at line 190 of file inc.php.
pFooter()
pFooter ($nonext = 0, $setuplang = '')
Print HTML footer.
Parameters
integer $nonext No button "Next step"
string $setuplang Language code
Returns
void
Definition at line 269 of file inc.php.
pHeader()
pHeader ($soutitre, $next, $action = 'none')
Show HTML header.
Parameters
string $soutitre Title
string $next Next
string $action Action code
Returns
void
Definition at line 230 of file inc.php.
Variable Documentation
db
DoliDB db = new stdClass()
API class for accounts.
API class for supplier invoices.
@access protected
Definition at line 41 of file inc.php.
Referenced by AccountancyCategory\__construct(), AccountancySystem\__construct(), AccountingJournal\__construct(), Adherent\__construct(), AdherentType\__construct(), Subscription\__construct(), Bookmark\__construct(), CActionComm\__construct(), Mailing\__construct(), PropaleLigne\__construct(), Commande\__construct(), OrderLine\__construct(), Localtax\__construct(), RemiseCheque\__construct(), Paiement\__construct(), PaymentVAT\__construct(), Tva\__construct(), Contrat\__construct(), ContratLigne\__construct(), AntiVir\__construct(), Ccountry\__construct(), Comment\__construct(), CommonDocGenerator\__construct(), CommonObjectLine\__construct(), CProductNature\__construct(), Cstate\__construct(), Ctypent\__construct(), CUnits\__construct(), DiscountAbsolute\__construct(), dolReceiptPrinter\__construct(), Events\__construct(), ExtraFields\__construct(), ExtraLanguages\__construct(), GenericObject\__construct(), HookManager\__construct(), Form\__construct(), FormAccounting\__construct(), FormActions\__construct(), FormAdmin\__construct(), FormBank\__construct(), FormBarCode\__construct(), FormContract\__construct(), FormCron\__construct(), FormExpenseReport\__construct(), FormFile\__construct(), FormIntervention\__construct(), FormMail\__construct(), FormMargin\__construct(), FormOther\__construct(), FormProjets\__construct(), FormPropal\__construct(), FormSms\__construct(), FormSocialContrib\__construct(), FormWebsite\__construct(), Interfaces\__construct(), Link\__construct(), Notify\__construct(), RssParser\__construct(), Utils\__construct(), DolibarrModules\__construct(), mailing_advthirdparties\__construct(), mailing_contacts1\__construct(), mailing_fraise\__construct(), MailingTargets\__construct(), mailing_pomme\__construct(), mailing_xinputfile\__construct(), mailing_xinputuser\__construct(), modBarcode\__construct(), modBookmark\__construct(), modClickToDial\__construct(), modDebugBar\__construct(), modDocumentGeneration\__construct(), modDon\__construct(), modDynamicPrices\__construct(), modECM\__construct(), modExport\__construct(), modExternalSite\__construct(), modFckeditor\__construct(), modFTP\__construct(), modGeoIPMaxmind\__construct(), modGravatar\__construct(), modImport\__construct(), modLabel\__construct(), modLdap\__construct(), modMailing\__construct(), modMailmanSpip\__construct(), modMargin\__construct(), modNotification\__construct(), modOauth\__construct(), modPayBox\__construct(), modPaypal\__construct(), modPrinting\__construct(), modReceiptPrinter\__construct(), modStripe\__construct(), modSyslog\__construct(), modWebServices\__construct(), modWebServicesClient\__construct(), modWorkflow\__construct(), PrintingDriver\__construct(), InterfaceLogevents\__construct(), InterfaceWorkflowManager\__construct(), InterfaceActionsAuto\__construct(), InterfaceActionsBlockedLog\__construct(), InterfaceEventOrganization\__construct(), InterfaceLdapsynchro\__construct(), InterfaceMailmanSpipsynchro\__construct(), InterfaceNotification\__construct(), InterfaceTicketEmail\__construct(), InterfaceStripe\__construct(), InterfaceContactRoles\__construct(), InterfaceWebhookTriggers\__construct(), InterfaceZapierTriggers\__construct(), Cronjob\__construct(), ActionsDatapolicy\__construct(), TraceableDB\__construct(), Delivery\__construct(), DeliveryLine\__construct(), Don\__construct(), PaymentDonation\__construct(), EcmDirectory\__construct(), FormEcm\__construct(), ExpeditionLigne\__construct(), ExpeditionLineBatch\__construct(), ExpenseReport\__construct(), ExpenseReportLine\__construct(), PaymentExpenseReport\__construct(), Export\__construct(), Fichinter\__construct(), FichinterLigne\__construct(), FichinterRec\__construct(), Fournisseur\__construct(), CommandeFournisseur\__construct(), CommandeFournisseurLigne\__construct(), CommandeFournisseurDispatch\__construct(), FactureFournisseurRec\__construct(), FactureFournisseur\__construct(), SupplierInvoiceLine\__construct(), PaiementFourn\__construct(), Holiday\__construct(), Establishment\__construct(), Loan\__construct(), LoanSchedule\__construct(), PaymentLoan\__construct(), MailmanSpip\__construct(), ActionsMyModule\__construct(), mailing_mailinglist_mymodule_myobject\__construct(), InterfaceMyModuleTriggers\__construct(), Opensurveysondage\__construct(), PartnershipUtils\__construct(), FormProduct\__construct(), Product\__construct(), Productbatch\__construct(), Productcustomerprice\__construct(), Propalmergepdfproduct\__construct(), PriceExpression\__construct(), PriceGlobalVariable\__construct(), PriceGlobalVariableUpdater\__construct(), PriceParser\__construct(), MouvementStock\__construct(), Task\__construct(), TaskStats\__construct(), Reception\__construct(), Dolresource\__construct(), FormResource\__construct(), PaymentSalary\__construct(), Salary\__construct(), Client\__construct(), ActionsStripeconnect\__construct(), Stripe\__construct(), SupplierProposalLine\__construct(), ActionsTicket\__construct(), User\__construct(), UserGroup\__construct(), Canvas\__construct(), ActionsAdherentCardDefault\__construct(), ActionsContactCardDefault\__construct(), ActionsCardCompany\__construct(), ActionsCardIndividual\__construct(), GoogleAPI\__construct(), Menubase\__construct(), MenuManager\__construct(), CdavLib\__construct(), AccountancyImport\__construct(), BookKeeping\__construct(), AssetAccountancyCodes\__construct(), AvailabilitiesLine\__construct(), BookingLine\__construct(), ActionComm\__construct(), AccountLine\__construct(), PaymentVarious\__construct(), CashControl\__construct(), Deplacement\__construct(), FactureRec\__construct(), Facture\__construct(), PaymentTerm\__construct(), ChargeSociales\__construct(), PaymentSocialContribution\__construct(), DolibarrTriggers\__construct(), EcmFiles\__construct(), ConferenceOrBoothAttendeeLine\__construct(), ExpenseReportIk\__construct(), ExpenseReportRule\__construct(), JobLine\__construct(), PositionLine\__construct(), IntracommReport\__construct(), KnowledgeRecordLine\__construct(), MyObjectLine\__construct(), MultiCurrency\__construct(), CurrencyRate\__construct(), PartnershipLine\__construct(), Productlot\__construct(), ProductStockEntrepot\__construct(), RecruitmentCandidatureLine\__construct(), CompanyBankAccount\__construct(), UserBankAccount\__construct(), ProductCombinationLevel\__construct(), ProductCombination2ValuePair\__construct(), TargetLine\__construct(), Website\__construct(), WebsitePage\__construct(), Societe\add_commercial(), DoliDBMysqli\affected_rows(), DoliDBSqlite3\affected_rows(), TraceableDB\affected_rows(), TraceableDB\begin(), CommonInvoice\calculate_date_lim_reglement(), MultiCurrency\checkCodeAlreadyExists(), CommandeFournisseur\classifyBilled(), Commande\classifyBilled(), Commande\classifyUnBilled(), Product\clone_associations(), Product\clone_fournisseurs(), DoliDBMysqli\close(), DoliDBPgsql\close(), DoliDBSqlite3\close(), TraceableDB\close(), DolQueryCollector\collect(), Export\conditionDate(), TraceableDB\DDLCreateDb(), TraceableDB\DDLCreateUser(), TraceableDB\DDLGetConnectId(), Fiscalyear\delete(), Establishment\delete(), Deplacement\delete(), ChargeSociales\delete(), Link\delete(), Loan\delete(), Cronjob\delete(), CommandeFournisseurDispatch\delete(), BonPrelevement\delete(), FactureLigneRec\delete(), EcmFiles\delete(), FactureFournisseurLigneRec\delete(), Evaluationline\delete(), Productlot\delete(), ProductStockEntrepot\delete(), CompanyBankAccount\delete(), BookKeeping\deleteByImportkey(), FactureFournisseur\deleteline(), TraceableDB\encrypt(), DoliDBPgsql\errno(), DoliDBSqlite3\errno(), TraceableDB\errno(), DoliDBMysqli\error(), DoliDBPgsql\error(), TraceableDB\error(), DoliDBMysqli\escape(), TraceableDB\escape(), TraceableDB\fetch_array(), TraceableDB\fetch_object(), TraceableDB\fetch_row(), Skill\fetchLines(), TraceableDB\free(), TraceableDB\getDefaultCharacterSetDatabase(), TraceableDB\getDefaultCollationDatabase(), DoliDBMysqli\getDriverInfo(), TraceableDB\getDriverInfo(), ActionsTicket\getInstanceDao(), Mo\getLinesArray(), BOM\getLinesArray(), Availabilities\getLinesArray(), Booking\getLinesArray(), Evaluation\getLinesArray(), Evaluationline\getLinesArray(), Job\getLinesArray(), Position\getLinesArray(), Skill\getLinesArray(), KnowledgeRecord\getLinesArray(), MyObject\getLinesArray(), Partnership\getLinesArray(), StockTransfer\getLinesArray(), StockTransferLine\getLinesArray(), RecruitmentCandidature\getLinesArray(), Target\getLinesArray(), TraceableDB\getListOfCharacterSet(), TraceableDB\getListOfCollation(), Mo\getMoParent(), TraceableDB\getPathOfDump(), TraceableDB\getPathOfRestore(), DoliDBMysqli\getVersion(), TraceableDB\getVersion(), TraceableDB\getVersionArray(), AccountLine\insert(), TraceableDB\lasterrno(), TraceableDB\lasterror(), TraceableDB\lastquery(), TraceableDB\lastqueryerror(), DoliDBSqlite3\num_rows(), TraceableDB\num_rows(), Tickets\post(), Tickets\postNewMessage(), TraceableDB\query(), TraceableDB\select_db(), Propal\set_availability(), Commande\set_date(), Propal\set_demand_reason(), Propal\set_echeance(), CommandeFournisseur\set_id_projet(), Propal\set_ref_client(), Commande\set_ref_client(), Propal\set_remise_absolue(), Commande\set_remise_absolue(), Facture\set_remise_absolue(), Propal\set_remise_percent(), Commande\set_reopen(), CompanyPaymentMode\setAsDefault(), CompanyBankAccount\setAsDefault(), Facture\setCanceled(), FactureFournisseur\setCanceled(), Inventory\setCanceled(), Propal\setDeliveryDate(), Commande\setDeliveryDate(), CommandeFournisseur\setDeliveryDate(), Commande\setDiscount(), Facture\setDiscount(), Propal\setDraft(), Inventory\setDraft(), Facture\setFinal(), Facture\setPaid(), FactureFournisseur\setPaid(), Inventory\setRecorded(), Fichinter\setRefClient(), Facture\setUnpaid(), FactureFournisseur\setUnpaid(), AccountingAccount\update(), Loan\update(), Subscription\update(), ChargeSociales\update(), AccountLine\update(), User\update_clicktodial(), Paiement\update_date(), Adherent\update_end_date(), PropaleLigne\update_total(), OrderLine\update_total(), FactureLigne\update_total(), ContratLigne\update_total(), SupplierInvoiceLine\update_total(), SupplierProposalLine\update_total(), Holiday\updateBalance(), CommandeFournisseur\updateFromCommandeClient(), ActionComm\updatePercent(), and Mo\updateProduction().