name 'puppetlabs-git'
version '0.0.3'
source 'git://github.com/puppetlabs/puppetlabs-git.git'
author 'puppetlabs'
license 'Apache 2.0'
summary 'module for installing git'
description 'module for installing git'
project_page 'https://github.com/puppetlabs/puppetlabs-git/'
dependency 'puppetlabs/vcsrepo'

