dolibarr: test\functional\MyModuleFunctionalTest Class Reference
test\functional\MyModuleFunctionalTest Class Reference
Public Member Functions
setUp ()
Unit test setup.
testEnableDeveloperMode ()
Test enabling developer mode.
testModuleEnabled ()
Test enabling the module.
testConfigurationPage ()
Test access to the configuration page.
testAboutPage ()
Test access to the about page.
testAboutPageRendersMarkdownReadme ()
Test about page is rendering Markdown.
testBoxDeclared ()
Test box is properly declared.
testTriggerDeclared ()
Test trigger is properly enabled.
testTriggerEnabled ()
Test trigger is properly declared.
tearDown ()
Unit test teardown.
Static Public Member Functions
static setUpBeforeClass ()
Global test setup.
static tearDownAfterClass ()
Global test teardown.
Protected Member Functions
byHref ($value)
Helper function to select links by href.
assertPreConditions ()
Verify pre conditions.
assertPostConditions ()
Verify post conditions.
Private Member Functions
authenticate ()
Handle Dolibarr authentication.
Detailed Description
Definition at line 44 of file MyModuleFunctionalTest.php.
Member Function Documentation
assertPostConditions()
test\functional\MyModuleFunctionalTest::assertPostConditions () protected
Verify post conditions.
Returns
void
Definition at line 285 of file MyModuleFunctionalTest.php.
assertPreConditions()
test\functional\MyModuleFunctionalTest::assertPreConditions () protected
Verify pre conditions.
Returns
void
Definition at line 122 of file MyModuleFunctionalTest.php.
authenticate()
test\functional\MyModuleFunctionalTest::authenticate () private
Handle Dolibarr authentication.
Returns
void
Definition at line 130 of file MyModuleFunctionalTest.php.
Referenced by test\functional\MyModuleFunctionalTest\testAboutPage(), test\functional\MyModuleFunctionalTest\testAboutPageRendersMarkdownReadme(), test\functional\MyModuleFunctionalTest\testBoxDeclared(), test\functional\MyModuleFunctionalTest\testConfigurationPage(), test\functional\MyModuleFunctionalTest\testEnableDeveloperMode(), test\functional\MyModuleFunctionalTest\testModuleEnabled(), test\functional\MyModuleFunctionalTest\testTriggerDeclared(), and test\functional\MyModuleFunctionalTest\testTriggerEnabled().
byHref()
test\functional\MyModuleFunctionalTest::byHref ($value) protected
Helper function to select links by href.
Parameters
string $value Href
Returns
mixed Helper string
Definition at line 88 of file MyModuleFunctionalTest.php.
Referenced by test\functional\MyModuleFunctionalTest\testModuleEnabled().
setUp()
test\functional\MyModuleFunctionalTest::setUp ()
Unit test setup.
Returns
void
Definition at line 112 of file MyModuleFunctionalTest.php.
setUpBeforeClass()
static test\functional\MyModuleFunctionalTest::setUpBeforeClass () static
Global test setup.
Returns
void
Definition at line 104 of file MyModuleFunctionalTest.php.
tearDown()
test\functional\MyModuleFunctionalTest::tearDown ()
Unit test teardown.
Returns
void
Definition at line 293 of file MyModuleFunctionalTest.php.
tearDownAfterClass()
static test\functional\MyModuleFunctionalTest::tearDownAfterClass () static
Global test teardown.
Returns
void
Definition at line 301 of file MyModuleFunctionalTest.php.
testAboutPage()
test\functional\MyModuleFunctionalTest::testAboutPage ()
Test access to the about page.
@depends testConfigurationPage
Returns
bool
Definition at line 210 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
testAboutPageRendersMarkdownReadme()
test\functional\MyModuleFunctionalTest::testAboutPageRendersMarkdownReadme ()
Test about page is rendering Markdown.
@depends testAboutPage
Returns
bool
Definition at line 223 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
testBoxDeclared()
test\functional\MyModuleFunctionalTest::testBoxDeclared ()
Test box is properly declared.
@depends testModuleEnabled
Returns
bool
Definition at line 240 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
testConfigurationPage()
test\functional\MyModuleFunctionalTest::testConfigurationPage ()
Test access to the configuration page.
@depends testModuleEnabled
Returns
bool
Definition at line 197 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
testEnableDeveloperMode()
test\functional\MyModuleFunctionalTest::testEnableDeveloperMode ()
Test enabling developer mode.
Returns
bool
Definition at line 151 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
testModuleEnabled()
test\functional\MyModuleFunctionalTest::testModuleEnabled ()
Test enabling the module.
@depends testEnableDeveloperMode
Returns
bool
Definition at line 171 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate(), and test\functional\MyModuleFunctionalTest\byHref().
testTriggerDeclared()
test\functional\MyModuleFunctionalTest::testTriggerDeclared ()
Test trigger is properly enabled.
@depends testModuleEnabled
Returns
bool
Definition at line 253 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
testTriggerEnabled()
test\functional\MyModuleFunctionalTest::testTriggerEnabled ()
Test trigger is properly declared.
@depends testTriggerDeclared
Returns
bool
Definition at line 270 of file MyModuleFunctionalTest.php.
References test\functional\MyModuleFunctionalTest\authenticate().
The documentation for this class was generated from the following file:
htdocs/modulebuilder/template/test/phpunit/MyModuleFunctionalTest.php