dolibarr: BlockedLog Class Reference
BlockedLog Class Reference
Class to manage Blocked Log.
Public Member Functions
__construct (DoliDB $db)
Constructor.
loadTrackedEvents ()
Load list of tracked events into $this->trackedevents.
getObjectLink ()
Try to retrieve source object (it it still exists).
getUser ()
setObjectData (&$object, $action, $amounts, $fuser=null)
Populate properties of log from object data.
fetch ($id)
Get object from database.
dolEncodeBlockedData ($data, $mode=0)
Encode data.
dolDecodeBlockedData ($data, $mode=0)
Decode data.
setCertified ()
Set block certified by authority.
create ($user, $forcesignature='')
Create blocked log in database.
checkSignature ($previoushash='', $returnarray=0)
Check if current signature still correct compared to the value in chain.
getPreviousHash ($withlock=0, $beforeid=0)
Get previous signature/hash in chain.
getLog ($element, $fk_object, $limit=0, $sortfield='', $sortorder='', $search_fk_user=-1, $search_start=-1, $search_end=-1, $search_ref='', $search_amount='', $search_code='')
Return array of log objects (with criterias)
getSignature ()
Return the signature (hash) of the "genesis-block" (Block 0).
alreadyUsed ($ignoresystem=0)
Check if module was already used or not for at least one recording.
Private Member Functions
buildKeyForSignature ()
Return a string for signature.
Detailed Description
Class to manage Blocked Log.
Definition at line 26 of file blockedlog.class.php.
Constructor & Destructor Documentation
__construct()
BlockedLog::__construct (DoliDB $db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 126 of file blockedlog.class.php.
Member Function Documentation
alreadyUsed()
BlockedLog::alreadyUsed ($ignoresystem = 0)
Check if module was already used or not for at least one recording.
Parameters
int $ignoresystem Ignore system events for the test
Returns
bool
Definition at line 1195 of file blockedlog.class.php.
buildKeyForSignature()
BlockedLog::buildKeyForSignature () private
Return a string for signature.
Note: rowid of line not included as it is not a business data and this allow to make backup of a year and restore it into another database with different id wihtout comprimising checksums
Returns
string Key for signature
Definition at line 1020 of file blockedlog.class.php.
Referenced by checkSignature().
checkSignature()
BlockedLog::checkSignature ($previoushash = '', $returnarray = 0)
Check if current signature still correct compared to the value in chain.
Parameters
string $previoushash If previous signature hash is known, we can provide it to avoid to make a search of it in database.
int $returnarray 1=Return array of details, 2=Return array of details including keyforsignature, 0=Boolean
Returns
boolean|array True if OK, False if KO
Definition at line 982 of file blockedlog.class.php.
References buildKeyForSignature(), dol_hash(), and getPreviousHash().
create()
BlockedLog::create ($user, $forcesignature = '')
Create blocked log in database.
Parameters
User $user Object user that create
int $forcesignature Force signature (for example '0000000000' when we disabled the module)
Returns
int <0 if KO, >0 if OK
Definition at line 855 of file blockedlog.class.php.
dolDecodeBlockedData()
BlockedLog::dolDecodeBlockedData ($data, $mode = 0)
Decode data.
Parameters
string $data Data to unserialize
string $mode 0=unserialize, 1=json_decode
Returns
object Value unserialized, an object (stdClass)
Definition at line 819 of file blockedlog.class.php.
dolEncodeBlockedData()
BlockedLog::dolEncodeBlockedData ($data, $mode = 0)
Encode data.
Parameters
string $data Data to serialize
string $mode 0=serialize, 1=json_encode
Returns
string Value serialized, an object (stdClass)
Definition at line 799 of file blockedlog.class.php.
fetch()
BlockedLog::fetch ($id)
Get object from database.
Parameters
int $id Id of object to load
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 734 of file blockedlog.class.php.
getLog()
BlockedLog::getLog ($element, $fk_object, $limit = 0, $sortfield = '', $sortorder = '', $search_fk_user = -1, $search_start = -1, $search_end = -1, $search_ref = '', $search_amount = '', $search_code = '')
Return array of log objects (with criterias)
Parameters
string $element element to search
int $fk_object id of object to search
int $limit max number of element, 0 for all
string $sortfield sort field
string $sortorder sort order
int $search_fk_user id of user(s)
int $search_start start time limit
int $search_end end time limit
string $search_ref search ref
string $search_amount search amount
string $search_code search code
Returns
array|int Array of object log or <0 if error
Definition at line 1087 of file blockedlog.class.php.
getObjectLink()
BlockedLog::getObjectLink ()
Try to retrieve source object (it it still exists).
Returns
string URL string of source object
Definition at line 223 of file blockedlog.class.php.
getPreviousHash()
BlockedLog::getPreviousHash ($withlock = 0, $beforeid = 0)
Get previous signature/hash in chain.
Parameters
int $withlock 1=With a lock
int $beforeid ID of a record
Returns
string Hash of previous record (if beforeid is defined) or hash of last record (if beforeid is 0)
Definition at line 1038 of file blockedlog.class.php.
Referenced by checkSignature().
getSignature()
BlockedLog::getSignature ()
Return the signature (hash) of the "genesis-block" (Block 0).
Returns
string Signature of genesis-block for current conf->entity
Definition at line 1169 of file blockedlog.class.php.
getUser()
BlockedLog::getUser ()
 try to retrieve user author
Returns
string
Definition at line 335 of file blockedlog.class.php.
loadTrackedEvents()
BlockedLog::loadTrackedEvents ()
Load list of tracked events into $this->trackedevents.
Returns
int Always 1
Definition at line 137 of file blockedlog.class.php.
setCertified()
BlockedLog::setCertified ()
Set block certified by authority.
Returns
boolean
Definition at line 837 of file blockedlog.class.php.
setObjectData()
BlockedLog::setObjectData (& $object, $action, $amounts, $fuser = null)
Populate properties of log from object data.
Parameters
Object $object object to store
string $action action
string $amounts amounts
User $fuser User object (forced)
Returns
int >0 if OK, <0 if KO
Definition at line 366 of file blockedlog.class.php.
The documentation for this class was generated from the following file:
htdocs/blockedlog/class/blockedlog.class.php