version: '3'

services:
    web:
      build: 
          context: .
          dockerfile: Dockerfile
      volumes:
          - ./:/var/www/
      ports:
          - "80:80"
      networks:
          - bridge

networks:
    bridge:
