#!/bin/bash -v
set -e
git checkout develop
#pull et màj remotes
#git remote update
git pull origin develop
git fetch d master1000

#start loop 

source numcommit
echo 'Commit number =' $numcommit

git checkout -b abb1000$numcommit
git cherry-pick d/master1000
