#!/bin/bash -v
set -e
git checkout develop
#pull et màj remotes
#git remote update
git pull origin develop
git fetch d800 master800

#start loop 

source numcommit
echo 'Commit number =' $numcommit

git checkout -b abb800$numcommit
git cherry-pick d800/master800
