language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script:
  - "rake lint"
  - "rake parser_validate"
  - "rake template_verify"
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
matrix:
  allow_failures:
    - rvm: 2.0.0
gemfile: Gemfile
notifications:
  email:
    recipients:
      - richard.pijnenburg@elasticsearch.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: "gFaED3lu9MRrmoojO2iagrfOaKAbCeQSqVZ9TsIo+qkqem8hwOsMuxsYQ9evPbPbanXQoVNALXTd4fgQW16+hfg/ClqI3nDtVZZJSy0W+U0yVZtz9TXFpi9Q/Z4TwK5TMdNMjemt0l2idY2SE3leHBZEeaIAGfLf0v38tCsNI84="
    template:
       - '@electrical %{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'
    on_success: change
    on_failure: always
