name    'elasticsearch-elasticsearch'
version '0.2.2'
source 'https://github.com/elasticsearch/puppet-elasticsearch'
author 'elasticsearch'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Elasticsearch nodes'
description 'Module for managing and configuring Elasticsearch nodes'
project_page 'https://github.com/elasticsearch/puppet-elasticsearch'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
