dolibarr: FactureRec Class Reference
FactureRec Class Reference
Class to manage invoice templates.
Public Member Functions
__construct (DoliDB $db)
Constructor.
create ($user, $facid, $notrigger=0)
Create a predefined invoice.
update (User $user, $notrigger=0)
Update a line invoice_rec.
fetch ($rowid, $ref='', $ref_ext='')
Load object and lines.
getLinesArray ()
Create an array of invoice lines.
fetch_lines ()
Get lines of template invoices into this->lines.
delete (User $user, $notrigger=0, $idwarehouse=-1)
Delete template invoice.
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1=0, $txlocaltax2=0, $fk_product=0, $remise_percent=0, $price_base_type='HT', $info_bits=0, $fk_remise_except='', $pu_ttc=0, $type=0, $rang=-1, $special_code=0, $label='', $fk_unit=null, $pu_ht_devise=0, $date_start_fill=0, $date_end_fill=0, $fk_fournprice=null, $pa_ht=0)
Add a line to invoice.
updateline ($rowid, $desc, $pu_ht, $qty, $txtva, $txlocaltax1=0, $txlocaltax2=0, $fk_product=0, $remise_percent=0, $price_base_type='HT', $info_bits=0, $fk_remise_except='', $pu_ttc=0, $type=0, $rang=-1, $special_code=0, $label='', $fk_unit=null, $pu_ht_devise=0, $notrigger=0, $date_start_fill=0, $date_end_fill=0, $fk_fournprice=null, $pa_ht=0)
Update a line to invoice.
getNextDate ()
Return the next date of.
isMaxNbGenReached ()
Return if maximum number of generation is reached.
strikeIfMaxNbGenReached ($ret)
Format string to output with by striking the string if max number of generation was reached.
createRecurringInvoices ($restrictioninvoiceid=0, $forcevalidation=0, $notrigger=0)
Create all recurrents invoices (for all entities if multicompany is used).
getNomUrl ($withpicto=0, $option='', $max=0, $short=0, $moretitle='', $notooltip='', $save_lastsearch_value=-1)
Return clicable name (with picto eventually)
getLibStatut ($mode=0, $alreadypaid=-1)
Return label of object status.
LibStatut ($recur, $status, $mode=0, $alreadypaid=-1, $type=0)
Return label of a status.
initAsSpecimen ($option='')
Initialise an instance with random values.
setFrequencyAndUnit ($frequency, $unit, $notrigger=0)
Update frequency and unit.
setNextDate ($date, $increment_nb_gen_done=0, $notrigger=0)
Update the next date of execution.
setMaxPeriod ($nb, $notrigger=0)
Update the maximum period.
setAutoValidate ($validate, $notrigger=0)
Update the auto validate flag of invoice.
setGeneratePdf ($validate, $notrigger=0)
Update the auto generate documents.
setModelPdf ($model, $notrigger=0)
Update the model for documents.
Public Member Functions inherited from CommonInvoice
getRemainToPay ($multicurrency=0)
Return remain amount to pay.
getSommePaiement ($multicurrency=0)
Return amount of payments already done.
getSumDepositsUsed ($multicurrency=0)
Return amount (with tax) of all deposits invoices used by invoice.
getSumCreditNotesUsed ($multicurrency=0)
Return amount (with tax) of all credit notes invoices + excess received used by invoice.
getSumFromThisCreditNotesNotUsed ($multicurrency=0)
Return amount (with tax) of all converted amount for this credit note.
getListIdAvoirFromInvoice ()
Returns array of credit note ids from the invoice.
getIdReplacingInvoice ($option='')
Returns the id of the invoice that replaces it.
getListOfPayments ($filtertype='')
Return list of payments.
is_erasable ()
Return if an invoice can be deleted Rule is: If invoice is draft and has a temporary ref -> yes (1) If hidden option INVOICE_CAN_NEVER_BE_REMOVED is on -> no (0) If invoice is dispatched in bookkeeping -> no (-1) If invoice has a definitive ref, is not last and INVOICE_CAN_ALWAYS_BE_REMOVED off -> no (-2) If invoice not last in a cycle -> no (-3) If there is payment -> no (-4) Otherwise -> yes (2)
getVentilExportCompta ()
Return if an invoice was dispatched into bookkeeping.
getLibType ($withbadge=0)
Return label of type of invoice.
calculate_date_lim_reglement ($cond_reglement=0)
Returns an invoice payment deadline based on the invoice settlement conditions and billing date.
demande_prelevement ($fuser, $amount=0, $type='direct-debit', $sourcetype='facture')
Create a withdrawal request for a direct debit order or a credit transfer order.
makeStripeSepaRequest ($fuser, $did=0, $type='direct-debit', $sourcetype='facture')
Create a withdrawal request for a direct debit order or a credit transfer order.
demande_prelevement_delete ($fuser, $did)
Remove a direct debit request or a credit transfer request.
buildZATCAQRString ()
Build string for ZATCA QR Code (Arabi Saudia)
buildSwitzerlandQRString ()
Build string for QR-Bill (Switzerland)
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
static replaceProduct (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a product id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
$total
$tva
Public Attributes inherited from CommonInvoice
const TYPE_STANDARD = 0
Standard invoice.
const TYPE_REPLACEMENT = 1
Replacement invoice.
const TYPE_CREDIT_NOTE = 2
Credit note invoice.
const TYPE_DEPOSIT = 3
Deposit invoice.
const TYPE_PROFORMA = 4
Proforma invoice.
const TYPE_SITUATION = 5
Situation invoice.
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated (need to be paid)
const STATUS_CLOSED = 2
Classified paid.
const STATUS_ABANDONED = 3
Classified abandoned and no payment done.
Public Attributes inherited from CommonObject
$projet
$fk_projet
$note
Protected Attributes
$table_ref_field = 'titre'
{}
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage invoice templates.
Definition at line 40 of file facture-rec.class.php.
Constructor & Destructor Documentation
__construct()
FactureRec::__construct (DoliDB $db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 224 of file facture-rec.class.php.
References db.
Member Function Documentation
addline()
FactureRec::addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $fk_product = 0, $remise_percent = 0, $price_base_type = 'HT', $info_bits = 0, $fk_remise_except = '', $pu_ttc = 0, $type = 0, $rang = -1, $special_code = 0, $label = '', $fk_unit = null, $pu_ht_devise = 0, $date_start_fill = 0, $date_end_fill = 0, $fk_fournprice = null, $pa_ht = 0)
Add a line to invoice.
Parameters
string $desc Description de la ligne
double $pu_ht Prix unitaire HT (> 0 even for credit note)
double $qty Quantite
double $txtva Taux de tva force, sinon -1
double $txlocaltax1 Local tax 1 rate (deprecated)
double $txlocaltax2 Local tax 2 rate (deprecated)
int $fk_product Product/Service ID predefined
double $remise_percent Percentage discount of the line
string $price_base_type HT or TTC
int $info_bits VAT npr or not ?
int $fk_remise_except Id remise
double $pu_ttc Prix unitaire TTC (> 0 even for credit note)
int $type Type of line (0=product, 1=service)
int $rang Position of line
int $special_code Special code
string $label Label of the line
string $fk_unit Unit
double $pu_ht_devise Unit price in currency
int $date_start_fill 1=Flag to fill start date when generating invoice
int $date_end_fill 1=Flag to fill end date when generating invoice
int $fk_fournprice Supplier price id (to calculate margin) or ''
int $pa_ht Buying price of line (to calculate margin) or ''
Returns
int <0 if KO, Id of line if OK
Definition at line 863 of file facture-rec.class.php.
create()
FactureRec::create ($user, $facid, $notrigger = 0)
Create a predefined invoice.
Parameters
User $user User object
int $facid Id of source invoice
int $notrigger No trigger
Returns
int <0 if KO, id of invoice created if OK
Definition at line 237 of file facture-rec.class.php.
createRecurringInvoices()
FactureRec::createRecurringInvoices ($restrictioninvoiceid = 0, $forcevalidation = 0, $notrigger = 0)
Create all recurrents invoices (for all entities if multicompany is used).
A result may also be provided into this->output.
WARNING: This method change temporarly context $conf->entity to be in correct context for each recurring invoice found.
Parameters
int $restrictioninvoiceid 0=All qualified template invoices found. > 0 = restrict action on invoice ID
int $forcevalidation 1=Force validation of invoice whatever is template auto_validate flag.
int $notrigger Disable the trigger
Returns
int 0 if OK, < 0 if KO (this function is used also by cron so only 0 is OK)
Definition at line 1260 of file facture-rec.class.php.
delete()
FactureRec::delete (User $user, $notrigger = 0, $idwarehouse = -1)
Delete template invoice.
Parameters
User $user User that delete.
int $notrigger 1=Does not execute triggers, 0= execute triggers
int $idwarehouse Id warehouse to use for stock change.
Returns
int <0 if KO, >0 if OK
Definition at line 781 of file facture-rec.class.php.
fetch()
FactureRec::fetch ($rowid, $ref = '', $ref_ext = '')
Load object and lines.
Parameters
int $rowid Id of object to load
string $ref Reference of recurring invoice
string $ref_ext External reference of invoice
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 527 of file facture-rec.class.php.
fetch_lines()
FactureRec::fetch_lines ()
Get lines of template invoices into this->lines.
Returns
int 1 if OK, < 0 if KO
Definition at line 660 of file facture-rec.class.php.
References dol_syslog().
Referenced by getLinesArray().
getLibStatut()
FactureRec::getLibStatut ($mode = 0, $alreadypaid = -1)
Return label of object status.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=short label + picto, 6=Long label + picto
integer $alreadypaid Not used on recurring invoices
Returns
string Label of status
Reimplemented from CommonInvoice.
Definition at line 1501 of file facture-rec.class.php.
getLinesArray()
FactureRec::getLinesArray ()
Create an array of invoice lines.
Returns
int >0 if OK, <0 if KO
Definition at line 648 of file facture-rec.class.php.
References fetch_lines().
getNextDate()
FactureRec::getNextDate ()
Return the next date of.
Returns
int|false false if KO, timestamp if OK
Definition at line 1215 of file facture-rec.class.php.
References dol_time_plus_duree().
getNomUrl()
FactureRec::getNomUrl ($withpicto = 0, $option = '', $max = 0, $short = 0, $moretitle = '', $notooltip = '', $save_lastsearch_value = -1)
Return clicable name (with picto eventually)
Parameters
int $withpicto Add picto into link
string $option Where point the link
int $max Maxlength of ref
int $short 1=Return just URL
string $moretitle Add more text to title tooltip
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 1428 of file facture-rec.class.php.
initAsSpecimen()
FactureRec::initAsSpecimen ($option = '')
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Parameters
string $option ''=Create a specimen invoice with lines, 'nolines'=No lines
Returns
void
Definition at line 1649 of file facture-rec.class.php.
isMaxNbGenReached()
FactureRec::isMaxNbGenReached ()
Return if maximum number of generation is reached.
Returns
boolean False by default, True if maximum number of generation is reached
Definition at line 1228 of file facture-rec.class.php.
LibStatut()
FactureRec::LibStatut ($recur, $status, $mode = 0, $alreadypaid = -1, $type = 0)
Return label of a status.
Parameters
int $recur Is it a recurring invoice ?
int $status Id status (suspended or not)
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=short label + picto, 6=long label + picto
integer $alreadypaid Not used for recurring invoices
int $type Type invoice
Returns
string Label of status
Reimplemented from CommonInvoice.
Definition at line 1517 of file facture-rec.class.php.
replaceProduct()
static FactureRec::replaceProduct (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a product id with another one.
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old product id
int $dest_id New product id
Returns
bool
Definition at line 1795 of file facture-rec.class.php.
References CommonObject\commonReplaceProduct().
replaceThirdparty()
static FactureRec::replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 1778 of file facture-rec.class.php.
References CommonObject\commonReplaceThirdparty().
setAutoValidate()
FactureRec::setAutoValidate ($validate, $notrigger = 0)
Update the auto validate flag of invoice.
Parameters
int $validate 0 to create in draft, 1 to create and validate invoice
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 1954 of file facture-rec.class.php.
setFrequencyAndUnit()
FactureRec::setFrequencyAndUnit ($frequency, $unit, $notrigger = 0)
Update frequency and unit.
Parameters
int $frequency value of frequency
string $unit unit of frequency (d, m, y)
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 1812 of file facture-rec.class.php.
setGeneratePdf()
FactureRec::setGeneratePdf ($validate, $notrigger = 0)
Update the auto generate documents.
Parameters
int $validate 0 no document, 1 to generate document
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 1994 of file facture-rec.class.php.
setMaxPeriod()
FactureRec::setMaxPeriod ($nb, $notrigger = 0)
Update the maximum period.
Parameters
int $nb number of maximum period
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 1909 of file facture-rec.class.php.
setModelPdf()
FactureRec::setModelPdf ($model, $notrigger = 0)
Update the model for documents.
Parameters
string $model model of document generator
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 2034 of file facture-rec.class.php.
setNextDate()
FactureRec::setNextDate ($date, $increment_nb_gen_done = 0, $notrigger = 0)
Update the next date of execution.
Parameters
datetime $date date of execution
int $increment_nb_gen_done 0 do nothing more, >0 increment nb_gen_done
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 1864 of file facture-rec.class.php.
strikeIfMaxNbGenReached()
FactureRec::strikeIfMaxNbGenReached ($ret)
Format string to output with by striking the string if max number of generation was reached.
Parameters
string $ret Default value to output
Returns
boolean False by default, True if maximum number of generation is reached
Definition at line 1243 of file facture-rec.class.php.
update()
FactureRec::update (User $user, $notrigger = 0)
Update a line invoice_rec.
Parameters
User $user User
int $notrigger No trigger
Returns
int <0 if KO, Id of line if OK
Definition at line 470 of file facture-rec.class.php.
updateline()
FactureRec::updateline ($rowid, $desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $fk_product = 0, $remise_percent = 0, $price_base_type = 'HT', $info_bits = 0, $fk_remise_except = '', $pu_ttc = 0, $type = 0, $rang = -1, $special_code = 0, $label = '', $fk_unit = null, $pu_ht_devise = 0, $notrigger = 0, $date_start_fill = 0, $date_end_fill = 0, $fk_fournprice = null, $pa_ht = 0)
Update a line to invoice.
Parameters
int $rowid Id of line to update
string $desc Description de la ligne
double $pu_ht Prix unitaire HT (> 0 even for credit note)
double $qty Quantite
double $txtva Taux de tva force, sinon -1
double $txlocaltax1 Local tax 1 rate (deprecated)
double $txlocaltax2 Local tax 2 rate (deprecated)
int $fk_product Product/Service ID predefined
double $remise_percent Percentage discount of the line
string $price_base_type HT or TTC
int $info_bits Bits of type of lines
int $fk_remise_except Id remise
double $pu_ttc Prix unitaire TTC (> 0 even for credit note)
int $type Type of line (0=product, 1=service)
int $rang Position of line
int $special_code Special code
string $label Label of the line
string $fk_unit Unit
double $pu_ht_devise Unit price in currency
int $notrigger disable line update trigger
int $date_start_fill 1=Flag to fill start date when generating invoice
int $date_end_fill 1=Flag to fill end date when generating invoice
int $fk_fournprice Id of origin supplier price
int $pa_ht Price (without tax) of product for margin calculation
Returns
int <0 if KO, Id of line if OK
Definition at line 1064 of file facture-rec.class.php.
Member Data Documentation
$total
FactureRec::$total
Deprecated:
See also
$total_ht
Definition at line 94 of file facture-rec.class.php.
$tva
FactureRec::$tva
Deprecated:
See also
$total_tva
Definition at line 100 of file facture-rec.class.php.
The documentation for this class was generated from the following file:
htdocs/compta/facture/class/facture-rec.class.php