dolibarr: SMTPs Class Reference
SMTPs Class Reference
Class to construct and send SMTP compliant email, even to a secure SMTP server, regardless of platform.
Public Member Functions
setOptions ($_options=array())
Set delivery receipt.
setDeliveryReceipt ($_val=0)
Set delivery receipt.
getDeliveryReceipt ()
get delivery receipt
setTrackId ($_val='')
Set trackid.
setMoreInHeader ($_val='')
Set moreInHeader.
getTrackId ()
get trackid
getMoreInHeader ()
get moreInHeader
setErrorsTo ($_strErrorsTo)
Set errors to.
getErrorsTo ($_part=true)
Get errors to.
setDebug ($_vDebug=false)
Set debug.
buildRCPTlist ()
build RECIPIENT List, all addresses who will recieve this message
sendMsg ()
Now send the message.
setConfig ($_strConfigPath=null)
setConfig() is used to populate select class properties from either a user defined INI file or the systems 'php.ini' file
setTransportType ($_type=0)
Determines the method inwhich the messages are to be sent.
getTransportType ()
Return the method inwhich the message is to be sent.
setMailPath ($_path)
Path to the sendmail execuable.
setHost ($_strHost)
Defines the Host Name or IP of the Mail Server to use.
getHost ()
Retrieves the Host Name or IP of the Mail Server to use This is used only with 'socket' based mail transmission.
setPort ($_intPort)
Defines the Port Number of the Mail Server to use This is defaulted to '25' This is used only with 'socket' based mail transmission.
getPort ()
Retrieves the Port Number of the Mail Server to use This is used only with 'socket' based mail transmission.
setID ($_strID)
User Name for authentication on Mail Server.
getID ()
Retrieves the User Name for authentication on Mail Server.
setPW ($_strPW)
User Password for authentication on Mail Server.
getPW ()
Retrieves the User Password for authentication on Mail Server.
setToken ($_strToken)
User token for OAUTH2.
getToken ()
Retrieves the User token for OAUTH2.
setCharSet ($_strCharSet)
Character set used for current message Character set is defaulted to 'iso-8859-1';.
getCharSet ()
Retrieves the Character set used for current message.
setTransEncode ($_strTransEncode)
Content-Transfer-Encoding, Defaulted to '7bit' This can be changed for 2byte characers sets Known Encode Types.
getTransEncode ()
Retrieves the Content-Transfer-Encoding.
setTransEncodeType ($_strTransEncodeType)
Content-Transfer-Encoding, Defaulted to '0' [ZERO] This can be changed for 2byte characers sets Known Encode Types.
getTransEncodeType ()
Retrieves the Content-Transfer-Encoding.
setFrom ($_strFrom)
FROM Address from which mail will be sent.
getFrom ($_part=true)
Retrieves the Address from which mail will be sent.
setReplyTo ($_strReplyTo)
Reply-To Address from which mail will be the reply-to.
getReplyTo ($_part=true)
Retrieves the Address from which mail will be the reply-to.
get_RCPT_list ()
Returns an array of bares addresses for use with 'RCPT TO:' This is a "build as you go" method.
get_email_list ($_which=null)
Returns an array of addresses for a specific type; TO, CC or BCC.
setTO ($_addrTo)
TO Address[es] inwhich to send mail to.
getTo ()
Retrieves the TO Address[es] inwhich to send mail to.
setCC ($_strCC)
CC Address[es] inwhich to send mail to.
getCC ()
Retrieves the CC Address[es] inwhich to send mail to.
setBCC ($_strBCC)
BCC Address[es] inwhich to send mail to.
getBCC ()
Retrieves the BCC Address[es] inwhich to send mail to.
setSubject ($_strSubject='')
Message Subject.
getSubject ()
Retrieves the Message Subject.
getHeader ()
Constructes and returns message header.
setBodyContent ($strContent, $strType='plain')
Message Content.
getBodyContent ()
Retrieves the Message Content.
setAttachment ($strContent, $strFileName='unknown', $strMimeType='unknown', $strCid='')
File attachments are added to the content array as sub-arrays, allowing for multiple attachments for each outbound email.
setImageInline ($strContent, $strImageName='unknown', $strMimeType='unknown', $strImageCid='unknown')
Image attachments are added to the content array as sub-arrays, allowing for multiple images for each outbound email.
setSensitivity ($_value=0)
Message Content Sensitivity Message Sensitivity values:
getSensitivity ()
Returns Message Content Sensitivity string Message Sensitivity values:
setPriority ($_value=3)
Message Content Priority Message Priority values:
getPriority ()
Message Content Priority Message Priority values:
setMD5flag ($_flag=false)
Set flag which determines whether to calculate message MD5 checksum.
getMD5flag ()
Gets flag which determines whether to calculate message MD5 checksum.
setXheader ($strXdata)
Message X-Header Content This is a simple "insert".
getXheader ()
Retrieves the Message X-Header Content.
server_parse ($socket, $response)
This function has been modified as provided by SirSir to allow multiline responses when using SMTP Extensions.
socket_send_str ($_strSend, $_returnCode=null, $CRLF="\r\n")
Send str.
getErrors ()
Returns errors codes and messages for Class.
Private Member Functions
_server_connect ()
Attempt a connection to mail server.
_server_authenticate ()
Attempt mail server authentication for a secure connection.
_buildAddrList ($_type, $_addrList)
Inserts given addresses into structured format.
_strip_email ($_strAddr)
Returns an array of the various parts of an email address This assumes a well formed address:
_setBoundary ()
Generates Random string for MIME message Boundary.
_getBoundary ($type='mixed')
Retrieves the MIME message Boundary.
_setErr ($_errNum, $_errMsg)
Defines errors codes and messages for Class.
Private Attributes
$_smtpsHost = 'localhost'
Host Name or IP of SMTP Server to use.
$_smtpsPort = '25'
SMTP Server Port definition.
$_smtpsID = null
Secure SMTP Server access ID This can be defined via a INI file or via a setter method.
$_smtpsPW = null
Secure SMTP Server access Password This can be defined via a INI file or via a setter method.
$_smtpsToken = null
Token in case we use OAUTH2.
$_msgFrom = null
Who sent the Message This can be defined via a INI file or via a setter method.
$_msgReplyTo = null
Where are replies and errors to be sent to This can be defined via a INI file or via a setter method.
$_msgRecipients = null
Who will the Message be sent to; TO, CC, BCC Multi-diminsional array containg addresses the message will be sent TO, CC or BCC.
$_msgSubject = null
Message Subject.
$_msgContent = null
Message Content.
$_msgXheader = null
Custom X-Headers.
$_smtpsCharSet = 'iso-8859-1'
Character set Defaulted to 'iso-8859-1'.
$_msgSensitivity = 0
Message Sensitivity Defaults to ZERO - None.
$_arySensitivity
Message Sensitivity.
$_msgPriority = 3
Message Sensitivity Defaults to 3 - Normal.
$_aryPriority
Message Priority.
$_smtpsTransEncodeType = 0
Content-Transfer-Encoding Defaulted to 0 - 7bit.
$_smtpsTransEncodeTypes
Content-Transfer-Encoding.
$_smtpsTransEncode = '7bit'
Content-Transfer-Encoding Defaulted to '7bit'.
$_smtpsBoundary = null
Boundary String for MIME seperation.
$_smtpsRelatedBoundary = null
Related Boundary.
$_smtpsAlternativeBoundary = null
Alternative Boundary.
$_transportType = 0
Determines the method inwhich the message are to be sent.
$_mailPath = '/usr/lib/sendmail'
If '$_transportType' is set to '1', then this variable is used to define the UNIX file system path to the sendmail execuable.
$_smtpTimeout = 10
Sets the SMTP server timeout in seconds.
$_smtpMD5 = false
Determines whether to calculate message MD5 checksum.
$_smtpsErrors = null
Class error codes and messages.
$_log_level = 0
Defines log level 0 - no logging 1 - connectivity logging 2 - message generation logging 3 - detail logging.
$_debug = false
Place Class in" debug" mode.
$_options = array()
An array of options for stream_context_create()
Detailed Description
Class to construct and send SMTP compliant email, even to a secure SMTP server, regardless of platform.
Definition at line 46 of file smtps.class.php.
Member Function Documentation
_buildAddrList()
SMTPs::_buildAddrList ($_type, $_addrList) private
Inserts given addresses into structured format.
This method takes a list of given addresses, via an array or a COMMA delimted string, and inserts them into a highly structured array. This array is designed to remove duplicate addresses and to sort them by Domain.
Parameters
string $_type TO, CC, or BCC lists to add addrresses into
mixed $_addrList Array or COMMA delimited string of addresses
Returns
void
Definition at line 1121 of file smtps.class.php.
References $_msgRecipients.
Referenced by setBCC(), setCC(), and setTO().
_getBoundary()
SMTPs::_getBoundary ($type = 'mixed') private
Retrieves the MIME message Boundary.
Parameters
string $type Type of boundary
Returns
string $_smtpsBoundary MIME message Boundary
Definition at line 1856 of file smtps.class.php.
_server_authenticate()
SMTPs::_server_authenticate () private
Attempt mail server authentication for a secure connection.
Returns
boolean|null $_retVal Boolean indicating success or failure of authentication
Definition at line 453 of file smtps.class.php.
_server_connect()
SMTPs::_server_connect () private
Attempt a connection to mail server.
Returns
mixed $_retVal Boolean indicating success or failure on connection
Definition at line 375 of file smtps.class.php.
References getHost().
_setBoundary()
SMTPs::_setBoundary () private
Generates Random string for MIME message Boundary.
Returns
void
Definition at line 1843 of file smtps.class.php.
_setErr()
SMTPs::_setErr ($_errNum, $_errMsg) private
Defines errors codes and messages for Class.
Parameters
int $_errNum Error Code Number
string $_errMsg Error Message
Returns
void
Definition at line 1943 of file smtps.class.php.
Referenced by get_email_list(), and setConfig().
_strip_email()
SMTPs::_strip_email ($_strAddr) private
Returns an array of the various parts of an email address This assumes a well formed address:
"Real name" usern.nosp@m.ame@.nosp@m.domai.nosp@m.n.tl.nosp@m.d
"Real Name" is optional
if "Real Name" does not exist, the angle brackets are optional This will split an email address into 4 or 5 parts.
$_aryEmail[org] = orignal string
$_aryEmail[real] = "real name" - if there is one
$_aryEmail[addr] = address part "username@domain.tld"
$_aryEmail[host] = "domain.tld"
$_aryEmail[user] = "userName"
Parameters
string $_strAddr Email address
Returns
array An array of the various parts of an email address
Definition at line 1188 of file smtps.class.php.
Referenced by setErrorsTo(), setFrom(), and setReplyTo().
buildRCPTlist()
SMTPs::buildRCPTlist ()
build RECIPIENT List, all addresses who will recieve this message
Returns
void
Definition at line 363 of file smtps.class.php.
get_email_list()
SMTPs::get_email_list ($_which = null)
Returns an array of addresses for a specific type; TO, CC or BCC.
Parameters
string $_which Which collection of addresses to return ('to', 'cc', 'bcc')
Returns
string|false Array of emaill address
Definition at line 1260 of file smtps.class.php.
References _setErr().
Referenced by getBCC(), getCC(), and getTo().
get_RCPT_list()
SMTPs::get_RCPT_list ()
Returns an array of bares addresses for use with 'RCPT TO:' This is a "build as you go" method.
Each time this method is called the underlaying array is destroyed and reconstructed.
Returns
array Returns an array of bares addresses
An array of bares addresses for use with 'RCPT TO:'
Definition at line 1232 of file smtps.class.php.
getBCC()
SMTPs::getBCC ()
Retrieves the BCC Address[es] inwhich to send mail to.
Returns
string BCC Address[es] inwhich to send mail to
Definition at line 1357 of file smtps.class.php.
References get_email_list().
getBodyContent()
SMTPs::getBodyContent ()
Retrieves the Message Content.
Returns
string Message Content
Definition at line 1516 of file smtps.class.php.
getCC()
SMTPs::getCC ()
Retrieves the CC Address[es] inwhich to send mail to.
Returns
string CC Address[es] inwhich to send mail to
Definition at line 1334 of file smtps.class.php.
References get_email_list().
getCharSet()
SMTPs::getCharSet ()
Retrieves the Character set used for current message.
Returns
string $_smtpsCharSet Character set used for current message
Definition at line 972 of file smtps.class.php.
References $_smtpsCharSet.
getDeliveryReceipt()
SMTPs::getDeliveryReceipt ()
get delivery receipt
Returns
int Delivery receipt
Definition at line 268 of file smtps.class.php.
getErrors()
SMTPs::getErrors ()
Returns errors codes and messages for Class.
Returns
string $_errMsg Error Message
Definition at line 1956 of file smtps.class.php.
getErrorsTo()
SMTPs::getErrorsTo ($_part = true)
Get errors to.
Parameters
boolean $_part Variant
Returns
string Errors to
Definition at line 334 of file smtps.class.php.
getFrom()
SMTPs::getFrom ($_part = true)
Retrieves the Address from which mail will be sent.
Parameters
boolean $_part To "strip" 'Real name' from address
Returns
string Address from which mail will be sent
Definition at line 1064 of file smtps.class.php.
References $_msgFrom.
getHeader()
SMTPs::getHeader ()
Constructes and returns message header.
Returns
string Complete message header
Definition at line 1390 of file smtps.class.php.
getHost()
SMTPs::getHost ()
Retrieves the Host Name or IP of the Mail Server to use This is used only with 'socket' based mail transmission.
Returns
string $_strHost Host Name or IP of the Mail Server to use
Definition at line 858 of file smtps.class.php.
References $_smtpsHost.
Referenced by _server_connect().
getID()
SMTPs::getID ()
Retrieves the User Name for authentication on Mail Server.
Returns
string User Name for authentication on Mail Server
Definition at line 906 of file smtps.class.php.
References $_smtpsID.
getMD5flag()
SMTPs::getMD5flag ()
Gets flag which determines whether to calculate message MD5 checksum.
Returns
boolean Message Priority
Definition at line 1808 of file smtps.class.php.
References $_smtpMD5.
Referenced by setAttachment(), setBodyContent(), and setImageInline().
getMoreInHeader()
SMTPs::getMoreInHeader ()
get moreInHeader
Returns
string moreInHeader
Definition at line 310 of file smtps.class.php.
getPort()
SMTPs::getPort ()
Retrieves the Port Number of the Mail Server to use This is used only with 'socket' based mail transmission.
Returns
string Port Number of the Mail Server to use
Definition at line 885 of file smtps.class.php.
References $_smtpsPort.
getPriority()
SMTPs::getPriority ()
Message Content Priority Message Priority values:
[0] 'Bulk'
[1] 'Highest'
[2] 'High'
[3] 'Normal' - default
[4] 'Low'
[5] 'Lowest'
Returns
string
Definition at line 1785 of file smtps.class.php.
References $_msgPriority.
getPW()
SMTPs::getPW ()
Retrieves the User Password for authentication on Mail Server.
Returns
string User Password for authentication on Mail Server
Definition at line 927 of file smtps.class.php.
References $_smtpsPW.
getReplyTo()
SMTPs::getReplyTo ($_part = true)
Retrieves the Address from which mail will be the reply-to.
Parameters
boolean $_part To "strip" 'Real name' from address
Returns
string Address from which mail will be the reply-to
Definition at line 1096 of file smtps.class.php.
References $_msgReplyTo.
getSensitivity()
SMTPs::getSensitivity ()
Returns Message Content Sensitivity string Message Sensitivity values:
[0] None - default
[1] Personal
[2] Private
[3] Company Confidential
Returns
string|boolean
Definition at line 1747 of file smtps.class.php.
References $_msgSensitivity.
getSubject()
SMTPs::getSubject ()
Retrieves the Message Subject.
Returns
string Message Subject
Definition at line 1380 of file smtps.class.php.
References $_msgSubject.
getTo()
SMTPs::getTo ()
Retrieves the TO Address[es] inwhich to send mail to.
Returns
string TO Address[es] inwhich to send mail to
Definition at line 1311 of file smtps.class.php.
References get_email_list().
getToken()
SMTPs::getToken ()
Retrieves the User token for OAUTH2.
Returns
string User token for OAUTH2
Definition at line 948 of file smtps.class.php.
References $_smtpsToken.
getTrackId()
SMTPs::getTrackId ()
get trackid
Returns
string Track id
Definition at line 300 of file smtps.class.php.
getTransEncode()
SMTPs::getTransEncode ()
Retrieves the Content-Transfer-Encoding.
Returns
string $_smtpsTransEncode Content-Transfer-Encoding
Definition at line 1004 of file smtps.class.php.
References $_smtpsTransEncode.
getTransEncodeType()
SMTPs::getTransEncodeType ()
Retrieves the Content-Transfer-Encoding.
Returns
string Content-Transfer-Encoding
Definition at line 1037 of file smtps.class.php.
References $_smtpsTransEncodeType.
getTransportType()
SMTPs::getTransportType ()
Return the method inwhich the message is to be sent.
'sockets' [0] - conect via network to SMTP server
'pipe [1] - use UNIX path to EXE
'phpmail [2] - use the PHP built-in mail function
Returns
int $_strHost Host Name or IP of the Mail Server to use
Definition at line 817 of file smtps.class.php.
References $_transportType.
getXheader()
SMTPs::getXheader ()
Retrieves the Message X-Header Content.
Returns
string[] $_msgContent Message X-Header Content
Definition at line 1833 of file smtps.class.php.
References $_msgXheader.
sendMsg()
SMTPs::sendMsg ()
Now send the message.
Returns
boolean|null Result
Default return value
Definition at line 628 of file smtps.class.php.
server_parse()
SMTPs::server_parse ($socket, $response)
This function has been modified as provided by SirSir to allow multiline responses when using SMTP Extensions.
Parameters
resource $socket Socket handler
string $response Response. Example: "550 5.7.1 https://support.google.com/a/answer/6140680#invalidcred j21sm814390wre.3"
Returns
boolean True or false
Returns constructed SELECT Object string or boolean upon failure Default value is set at true
Definition at line 1876 of file smtps.class.php.
Referenced by socket_send_str().
setAttachment()
SMTPs::setAttachment ($strContent, $strFileName = 'unknown', $strMimeType = 'unknown', $strCid = '')
File attachments are added to the content array as sub-arrays, allowing for multiple attachments for each outbound email.
Parameters
string $strContent File data to attach to message
string $strFileName File Name to give to attachment
string $strMimeType File Mime Type of attachment
string $strCid File Cid of attachment (if defined, to be shown inline)
Returns
void
Definition at line 1673 of file smtps.class.php.
References dol_hash(), and getMD5flag().
setBCC()
SMTPs::setBCC ($_strBCC)
BCC Address[es] inwhich to send mail to.
Parameters
string $_strBCC Recipients BCC Address[es] inwhich to send mail to
Returns
void
Definition at line 1345 of file smtps.class.php.
References _buildAddrList().
setBodyContent()
SMTPs::setBodyContent ($strContent, $strType = 'plain')
Message Content.
Parameters
string $strContent Message Content
string $strType Type
Returns
void
Definition at line 1473 of file smtps.class.php.
References dol_hash(), and getMD5flag().
setCC()
SMTPs::setCC ($_strCC)
CC Address[es] inwhich to send mail to.
Parameters
string $_strCC CC Address[es] inwhich to send mail to
Returns
void
Definition at line 1322 of file smtps.class.php.
References _buildAddrList().
setCharSet()
SMTPs::setCharSet ($_strCharSet)
Character set used for current message Character set is defaulted to 'iso-8859-1';.
Parameters
string $_strCharSet Character set used for current message
Returns
void
Definition at line 960 of file smtps.class.php.
setConfig()
SMTPs::setConfig ($_strConfigPath = null)
setConfig() is used to populate select class properties from either a user defined INI file or the systems 'php.ini' file
If a user defined INI is to be used, the files complete path is passed as the method single parameter. The INI can define any class and/or user properties. Only properties defined within this file will be setter and/or orverwritten
If the systems 'php.ini' file is to be used, the method is called without parameters. In this case, only HOST, PORT and FROM properties will be set as they are the only properties that are defined within the 'php.ini'.
If secure SMTP is to be used, the user ID and Password can be defined with the user INI file, but the properties are not defined with the systems 'php.ini'file, they must be defined via their setter methods
This method can be called twice, if desired. Once without a parameter to load the properties as defined within the systems 'php.ini' file, and a second time, with a path to a user INI file for other properties to be defined.
Parameters
mixed $_strConfigPath path to config file or VOID
Returns
boolean
Returns constructed SELECT Object string or boolean upon failure Default value is set at true
Definition at line 756 of file smtps.class.php.
References _setErr(), setFrom(), setHost(), and setPort().
setDebug()
SMTPs::setDebug ($_vDebug = false)
Set debug.
Parameters
boolean $_vDebug Value for debug
Returns
void
Definition at line 353 of file smtps.class.php.
setDeliveryReceipt()
SMTPs::setDeliveryReceipt ($_val = 0)
Set delivery receipt.
Parameters
int $_val Value
Returns
void
Definition at line 258 of file smtps.class.php.
setErrorsTo()
SMTPs::setErrorsTo ($_strErrorsTo)
Set errors to.
Parameters
string $_strErrorsTo Errors to
Returns
void
Definition at line 321 of file smtps.class.php.
References _strip_email().
setFrom()
SMTPs::setFrom ($_strFrom)
FROM Address from which mail will be sent.
Parameters
string $_strFrom Address from which mail will be sent
Returns
void
Definition at line 1051 of file smtps.class.php.
References _strip_email().
Referenced by setConfig().
setHost()
SMTPs::setHost ($_strHost)
Defines the Host Name or IP of the Mail Server to use.
This is defaulted to 'localhost' This is used only with 'socket' based mail transmission
Parameters
string $_strHost Host Name or IP of the Mail Server to use
Returns
void
Definition at line 845 of file smtps.class.php.
Referenced by setConfig().
setID()
SMTPs::setID ($_strID)
User Name for authentication on Mail Server.
Parameters
string $_strID User Name for authentication on Mail Server
Returns
void
Definition at line 896 of file smtps.class.php.
setImageInline()
SMTPs::setImageInline ($strContent, $strImageName = 'unknown', $strMimeType = 'unknown', $strImageCid = 'unknown')
Image attachments are added to the content array as sub-arrays, allowing for multiple images for each outbound email.
Parameters
string $strContent Image data to attach to message
string $strImageName Image Name to give to attachment
string $strMimeType Image Mime Type of attachment
string $strImageCid CID
Returns
void
Definition at line 1702 of file smtps.class.php.
References dol_hash(), and getMD5flag().
setMailPath()
SMTPs::setMailPath ($_path)
Path to the sendmail execuable.
Parameters
string $_path Path to the sendmail execuable
Returns
boolean
Definition at line 829 of file smtps.class.php.
setMD5flag()
SMTPs::setMD5flag ($_flag = false)
Set flag which determines whether to calculate message MD5 checksum.
Parameters
string $_flag Message Priority
Returns
void
Definition at line 1798 of file smtps.class.php.
setMoreInHeader()
SMTPs::setMoreInHeader ($_val = '')
Set moreInHeader.
Parameters
string $_val Value
Returns
void
Definition at line 290 of file smtps.class.php.
setOptions()
SMTPs::setOptions ($_options = array())
Set delivery receipt.
Parameters
array $_options An array of options for stream_context_create()
Returns
void
Definition at line 247 of file smtps.class.php.
References $_options.
setPort()
SMTPs::setPort ($_intPort)
Defines the Port Number of the Mail Server to use This is defaulted to '25' This is used only with 'socket' based mail transmission.
Parameters
int $_intPort Port Number of the Mail Server to use
Returns
void
Definition at line 871 of file smtps.class.php.
Referenced by setConfig().
setPriority()
SMTPs::setPriority ($_value = 3)
Message Content Priority Message Priority values:
[0] 'Bulk'
[1] 'Highest'
[2] 'High'
[3] 'Normal' - default
[4] 'Low'
[5] 'Lowest'
Parameters
integer $_value Message Priority
Returns
void
Definition at line 1765 of file smtps.class.php.
setPW()
SMTPs::setPW ($_strPW)
User Password for authentication on Mail Server.
Parameters
string $_strPW User Password for authentication on Mail Server
Returns
void
Definition at line 917 of file smtps.class.php.
setReplyTo()
SMTPs::setReplyTo ($_strReplyTo)
Reply-To Address from which mail will be the reply-to.
Parameters
string $_strReplyTo Address from which mail will be the reply-to
Returns
void
Definition at line 1083 of file smtps.class.php.
References _strip_email().
setSensitivity()
SMTPs::setSensitivity ($_value = 0)
Message Content Sensitivity Message Sensitivity values:
[0] None - default
[1] Personal
[2] Private
[3] Company Confidential
Parameters
integer $_value Message Sensitivity
Returns
void
Definition at line 1729 of file smtps.class.php.
setSubject()
SMTPs::setSubject ($_strSubject = '')
Message Subject.
Parameters
string $_strSubject Message Subject
Returns
void
Definition at line 1368 of file smtps.class.php.
setTO()
SMTPs::setTO ($_addrTo)
TO Address[es] inwhich to send mail to.
Parameters
string $_addrTo TO Address[es] inwhich to send mail to
Returns
void
Definition at line 1299 of file smtps.class.php.
References _buildAddrList().
setToken()
SMTPs::setToken ($_strToken)
User token for OAUTH2.
Parameters
string $_strToken User token
Returns
void
Definition at line 938 of file smtps.class.php.
setTrackId()
SMTPs::setTrackId ($_val = '')
Set trackid.
Parameters
string $_val Value
Returns
void
Definition at line 279 of file smtps.class.php.
setTransEncode()
SMTPs::setTransEncode ($_strTransEncode)
Content-Transfer-Encoding, Defaulted to '7bit' This can be changed for 2byte characers sets Known Encode Types.
7bit Simple 7-bit ASCII
8bit 8-bit coding with line termination characters
base64 3 octets encoded into 4 sextets with offset
binary Arbitrary binary stream
mac-binhex40 Macintosh binary to hex encoding
quoted-printable Mostly 7-bit, with 8-bit characters encoded as "=HH"
uuencode UUENCODE encoding
Parameters
string $_strTransEncode Content-Transfer-Encoding
Returns
void
Definition at line 992 of file smtps.class.php.
setTransEncodeType()
SMTPs::setTransEncodeType ($_strTransEncodeType)
Content-Transfer-Encoding, Defaulted to '0' [ZERO] This can be changed for 2byte characers sets Known Encode Types.
[0] 7bit Simple 7-bit ASCII
[1] 8bit 8-bit coding with line termination characters
[2] base64 3 octets encoded into 4 sextets with offset
[3] binary Arbitrary binary stream
[4] mac-binhex40 Macintosh binary to hex encoding
[5] quoted-printable Mostly 7-bit, with 8-bit characters encoded as "=HH"
[6] uuencode UUENCODE encoding
Parameters
string $_strTransEncodeType Content-Transfer-Encoding
Returns
void
Definition at line 1025 of file smtps.class.php.
setTransportType()
SMTPs::setTransportType ($_type = 0)
Determines the method inwhich the messages are to be sent.
'sockets' [0] - conect via network to SMTP server
'pipe [1] - use UNIX path to EXE
'phpmail [2] - use the PHP built-in mail function
Parameters
int $_type Interger value representing Mail Transport Type
Returns
void
Definition at line 802 of file smtps.class.php.
setXheader()
SMTPs::setXheader ($strXdata)
Message X-Header Content This is a simple "insert".
Whatever is given will be placed "as is" into the Xheader array.
Parameters
string $strXdata Message X-Header Content
Returns
void
Definition at line 1821 of file smtps.class.php.
socket_send_str()
SMTPs::socket_send_str ($_strSend, $_returnCode = null, $CRLF = "\r\n")
Send str.
Parameters
string $_strSend String to send
string $_returnCode Return code
string $CRLF CRLF
Returns
boolean|null True or false
Definition at line 1917 of file smtps.class.php.
References server_parse().
Member Data Documentation
$_smtpsPort
SMTPs::$_smtpsPort = '25' private
SMTP Server Port definition.
25 is default value This can be defined via a INI file or via a setter method
Definition at line 57 of file smtps.class.php.
Referenced by getPort().
$_transportType
SMTPs::$_transportType = 0 private
Determines the method inwhich the message are to be sent.
'sockets' [0] - conect via network to SMTP server - default
'pipe [1] - use UNIX path to EXE
'phpmail [2] - use the PHP built-in mail function NOTE: Only 'sockets' is implemented
Definition at line 191 of file smtps.class.php.
Referenced by getTransportType().
The documentation for this class was generated from the following file:
htdocs/core/class/smtps.class.php