name    'example42-yum'
version '2.1.9'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-yum'
summary 'Puppet module for nagios'
description 'This module installs and manages yum and yum repositories'
dependency 'example42/puppi', '>= 2.0.0'
