= MYMODULE =
:subtitle: MYMODULE SPECIFICATIONS



== TOPIC OF DOCUMENT

This document was build from following input:

* Date 1
...

* Date 2
...


The document includes an introductory chapter of functional specifications, presenting the different actors involved in the rebuild of the definitions
of business terms that will be used (some of which may be new or different).
The main following chapter will present the entire process, also known as *uses cases*, according to a principle of a description, in chronological sequence if possible,
to present the actor and the action performed, as in the following example:

* *X* Actor realizes Action A.
* *Y* Actor communicates Info B to Actor *Z*
* *Automaton* performs update of data for...
* Etc ...

Functional requirements are complemented by a chapter of technical requirements.
The chapter on data lists key information specific to Presto that were identified at the time of writing specification. It will be enriched as
iterations occurs.

Finally, in the Appendix, the documents known when writing this document are centralized to illustrate the existing document or inspire the new expected one.
These documents have their content directly integrated in this specification or have a reference to
external documents stored in the *Appendices* directory accompanying this document.



*Log of versions*

[options="header",format="csv"]
|=== 
Author, Date, Version
John Doe, Date YYYY-MM-DD, Version 1.0
|===



<<<


== BUSINESS SPECIFICATIONS - INTRODUCTION

=== List of actors [[actors]]

Actors are physical people or moral entities working on at least one process.
The following chart prensts list of actors or partners identified by the project for the defined scope of project. We will use then the name defined into first column to speak about roles in the rest of documents.

[options="header",format="csv"]
|===
Actor/profil/role, Description of role, Access to system or not, Example of actor
Customer Service, Receive and create Sales orders (SO), Yes, Mr Smith
Purchase, Make puchase order (PO), Yes, 5 people
Administrator - IT, Administration of users/groups and IT services, Yes, John Doe
Automaton, Execute automatic data processing, Yes, NA
|===


=== Definitions [[definitions]]

To understand the descriptions of the target process, it was necessary to define or redefine some vocabulary concepts. We must see these definitions as defined in the
new system. Indeed, some terms are already being used but have either not a definition in line with standards, or even differs between services. To bring everyone, 
and to consolidate the process, these terms are redefined here, and with their definition in the target objective.

*Definition ABC*

...

*Definition DEF*

...


[NOTE]
==============
Important information will be noticed with a notice like this one.

* Main information 1
* Main information 2
==============



== BUSINESS SPECIFICATION - PROCESS

Specifications were cut into different business process. We call a business process a workflow with a starting situation and ending situation. Between start and end, we will find actions
done by actors to bring the value of the company. This actions are described using the syntax rule:
*Actor X* do action Y, *Actor Z* do action W.

_Each process/use case is described into a separate chapter._


=== Use case / Process 1 [[process_1]]

==== Title and goals

...

==== Actors or roles

* Members of group *...*

==== Standard flow

* Members of Groupe *...*: Do ...
* Members of Groupe *...*: Do ...
* Members of Groupe *...*: Do ...

==== Alternative flow

* A user without role *...*: Can't do ...

==== Business rules

* Business rule 1
* Business rule 2


