dolibarr: Expedition Class Reference
Expedition Class Reference
Class to manage shipments.
Public Member Functions
__construct ($db)
Constructor.
getNextNumRef ($soc)
Return next expedition ref.
create ($user, $notrigger=0)
Create expedition en base.
create_line ($entrepot_id, $origin_line_id, $qty, $rang=0, $array_options=null)
Create a expedition line.
create_line_batch ($line_ext, $array_options=0)
Create the detail of the expedition line.
fetch ($id, $ref='', $ref_ext='', $notused='')
Get object and lines from database.
valid ($user, $notrigger=0)
Validate object and update stock if option enabled.
create_delivery ($user)
Create a delivery receipt from a shipment.
addline ($entrepot_id, $id, $qty, $array_options=0)
Add an expedition line.
addline_batch ($dbatch, $array_options=0)
Add a shipment line with batch record.
update ($user=null, $notrigger=0)
Update database.
cancel ($notrigger=0, $also_update_stock=false)
Cancel shipment.
delete ($notrigger=0, $also_update_stock=false)
Delete shipment.
fetch_lines ()
Load lines.
deleteline ($user, $lineid)
Delete detail line.
getNomUrl ($withpicto=0, $option='', $max=0, $short=0, $notooltip=0, $save_lastsearch_value=-1)
Return clicable link of object (with eventually picto)
getLibStatut ($mode=0)
Return status label.
LibStatut ($status, $mode)
Return label of a status.
initAsSpecimen ()
Initialise an instance with random values.
set_date_livraison ($user, $delivery_date)
Set delivery date.
setDeliveryDate ($user, $delivery_date)
Set the planned delivery date.
fetch_delivery_methods ()
Fetch deliveries method and return an array.
list_delivery_methods ($id='')
Fetch all deliveries method and return an array.
getUrlTrackingStatus ($value='')
Forge an set tracking url.
setClosed ()
Classify the shipping as closed.
setBilled ()
Classify the shipping as invoiced (used when WORKFLOW_BILL_ON_SHIPMENT is on)
reOpen ()
Classify the shipping as validated/opened.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
$date
$date_expedition
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated status.
const STATUS_CLOSED = 2
Closed status.
const STATUS_CANCELED = -1
Canceled status.
Public Attributes inherited from CommonObject
$projet
$fk_projet
$note
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage shipments.
Definition at line 52 of file expedition.class.php.
Constructor & Destructor Documentation
__construct()
Expedition::__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 207 of file expedition.class.php.
Member Function Documentation
addline()
Expedition::addline ($entrepot_id, $id, $qty, $array_options = 0)
Add an expedition line.
If STOCK_WAREHOUSE_NOT_REQUIRED_FOR_SHIPMENTS is set, you can add a shipment line, with no stock source defined If STOCK_MUST_BE_ENOUGH_FOR_SHIPMENT is not set, you can add a shipment line, even if not enough into stock Note: For product that need a batch number, you must use addline_batch()
Parameters
int $entrepot_id Id of warehouse
int $id Id of source line (order line)
int $qty Quantity
array $array_options extrafields array
Returns
int <0 if KO, >0 if OK
Definition at line 905 of file expedition.class.php.
addline_batch()
Expedition::addline_batch ($dbatch, $array_options = 0)
Add a shipment line with batch record.
Parameters
array $dbatch Array of value (key 'detail' -> Array, key 'qty' total quantity for line, key ix_l : original line index)
array $array_options extrafields array
Returns
int <0 if KO, >0 if OK
Definition at line 988 of file expedition.class.php.
cancel()
Expedition::cancel ($notrigger = 0, $also_update_stock = false)
Cancel shipment.
Parameters
int $notrigger Disable triggers
bool $also_update_stock true if the stock should be increased back (false by default)
Returns
int >0 if OK, 0 if deletion done but failed to delete files, <0 if KO
Definition at line 1193 of file expedition.class.php.
create()
Expedition::create ($user, $notrigger = 0)
Create expedition en base.
Parameters
User $user Objet du user qui cree
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 si erreur, id expedition creee si ok
Definition at line 283 of file expedition.class.php.
create_delivery()
Expedition::create_delivery ($user)
Create a delivery receipt from a shipment.
Parameters
User $user User
Returns
int <0 if KO, >=0 if OK
Definition at line 868 of file expedition.class.php.
create_line()
Expedition::create_line ($entrepot_id, $origin_line_id, $qty, $rang = 0, $array_options = null)
Create a expedition line.
Parameters
int $entrepot_id Id of warehouse
int $origin_line_id Id of source line
int $qty Quantity
int $rang Rang
array $array_options extrafields array
Returns
int <0 if KO, line_id if OK
Definition at line 446 of file expedition.class.php.
create_line_batch()
Expedition::create_line_batch ($line_ext, $array_options = 0)
Create the detail of the expedition line.
Create 1 record into expeditiondet for each warehouse and n record for each lot in this warehouse into expeditiondet_batch.
Parameters
object $line_ext Objet with full information of line. $line_ext->detail_batch must be an array of ExpeditionLineBatch
array $array_options extrafields array
Returns
int <0 if KO, >0 if OK
Definition at line 474 of file expedition.class.php.
delete()
Expedition::delete ($notrigger = 0, $also_update_stock = false)
Delete shipment.
Warning, do not delete a shipment if a delivery is linked to (with table llx_element_element)
Parameters
int $notrigger Disable triggers
bool $also_update_stock true if the stock should be increased back (false by default)
Returns
int >0 if OK, 0 if deletion done but failed to delete files, <0 if KO
Definition at line 1384 of file expedition.class.php.
deleteline()
Expedition::deleteline ($user, $lineid)
Delete detail line.
Parameters
User $user User making deletion
int $lineid Id of line to delete
Returns
int >0 if OK, <0 if KO
Definition at line 1759 of file expedition.class.php.
fetch()
Expedition::fetch ($id, $ref = '', $ref_ext = '', $notused = '')
Get object and lines from database.
Parameters
int $id Id of object to load
string $ref Ref of object
string $ref_ext External reference of object
string $notused Internal reference of other object
Returns
int >0 if OK, 0 if not found, <0 if KO
Definition at line 520 of file expedition.class.php.
fetch_delivery_methods()
Expedition::fetch_delivery_methods ()
Fetch deliveries method and return an array.
Load array this->meths(rowid=>label).
Returns
void
Definition at line 2008 of file expedition.class.php.
fetch_lines()
Expedition::fetch_lines ()
Load lines.
Returns
int >0 if OK, Otherwise if KO
Definition at line 1579 of file expedition.class.php.
generateDocument()
Expedition::generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Force the model to using ('' to not force)
Translate $outputlangs object lang to use for translations
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int 0 if KO, 1 if OK
Definition at line 2408 of file expedition.class.php.
getLibStatut()
Expedition::getLibStatut ($mode = 0)
Return status label.
Parameters
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto
Returns
string Libelle
Definition at line 1864 of file expedition.class.php.
getNextNumRef()
Expedition::getNextNumRef ($soc)
Return next expedition ref.
Parameters
Societe $soc Thirdparty object
Returns
string Free reference for expedition
Definition at line 234 of file expedition.class.php.
getNomUrl()
Expedition::getNomUrl ($withpicto = 0, $option = '', $max = 0, $short = 0, $notooltip = 0, $save_lastsearch_value = -1)
Return clicable link of object (with eventually picto)
Parameters
int $withpicto Add picto into link
string $option Where the link point to
int $max Max length to show
int $short Use short labels
int $notooltip 1=No tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 1798 of file expedition.class.php.
getUrlTrackingStatus()
Expedition::getUrlTrackingStatus ($value = '')
Forge an set tracking url.
Parameters
string $value Value
Returns
void
Definition at line 2070 of file expedition.class.php.
initAsSpecimen()
Expedition::initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 1906 of file expedition.class.php.
LibStatut()
Expedition::LibStatut ($status, $mode)
Return label of a status.
Parameters
int $status Id statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label of status
Definition at line 1877 of file expedition.class.php.
list_delivery_methods()
Expedition::list_delivery_methods ($id = '')
Fetch all deliveries method and return an array.
Load array this->listmeths.
Parameters
int $id only this carrier, all if none
Returns
void
Definition at line 2035 of file expedition.class.php.
reOpen()
Expedition::reOpen ()
Classify the shipping as validated/opened.
Returns
int <0 if KO, 0 if already open, >0 if OK
Definition at line 2283 of file expedition.class.php.
replaceThirdparty()
static Expedition::replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 2441 of file expedition.class.php.
References CommonObject\commonReplaceThirdparty().
set_date_livraison()
Expedition::set_date_livraison ($user, $delivery_date)
Set delivery date.
Parameters
User $user Object user that modify
int $delivery_date Delivery date
Returns
int <0 if ko, >0 if ok
Deprecated:
Use setDeliveryDate
Definition at line 1968 of file expedition.class.php.
References setDeliveryDate().
setBilled()
Expedition::setBilled ()
Classify the shipping as invoiced (used when WORKFLOW_BILL_ON_SHIPMENT is on)
Returns
int <0 if ko, >0 if ok
Definition at line 2242 of file expedition.class.php.
setClosed()
Expedition::setClosed ()
Classify the shipping as closed.
Returns
int <0 if KO, >0 if OK
Definition at line 2098 of file expedition.class.php.
setDeliveryDate()
Expedition::setDeliveryDate ($user, $delivery_date)
Set the planned delivery date.
Parameters
User $user Objet user that modify
integer $delivery_date Date of delivery
Returns
int <0 if KO, >0 if OK
Definition at line 1981 of file expedition.class.php.
Referenced by set_date_livraison().
update()
Expedition::update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1053 of file expedition.class.php.
valid()
Expedition::valid ($user, $notrigger = 0)
Validate object and update stock if option enabled.
Parameters
User $user Object user that validate
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if OK, >0 if KO
Definition at line 659 of file expedition.class.php.
Member Data Documentation
$date
Expedition::$date
Deprecated:
See also
$date_shipping
Definition at line 151 of file expedition.class.php.
$date_expedition
Expedition::$date_expedition
Deprecated:
See also
$date_shipping
Definition at line 157 of file expedition.class.php.
The documentation for this class was generated from the following file:
htdocs/expedition/class/expedition.class.php