dolibarr: CommandeFournisseur Class Reference
CommandeFournisseur Class Reference
Class to manage predefined suppliers products.
Public Member Functions
__construct ($db)
Constructor.
fetch ($id, $ref='')
Get object and lines from database.
fetch_lines ($only_product=0)
Load array lines.
valid ($user, $idwarehouse=0, $notrigger=0)
Validate an order.
getLibStatut ($mode=0)
Return label of the status of object.
LibStatut ($status, $mode=0, $billed=0)
Return label of a status.
getNomUrl ($withpicto=0, $option='', $notooltip=0, $save_lastsearch_value=-1, $addlinktonotes=0)
Return clicable name (with picto eventually)
getNextNumRef ($soc)
Returns the following order reference not used depending on the numbering model activated defined within COMMANDE_SUPPLIER_ADDON_NUMBER.
classifyBilled (User $user)
Class invoiced the supplier order.
approve ($user, $idwarehouse=0, $secondlevel=0)
Approve a supplier order.
refuse ($user)
Refuse an order.
Cancel ($user, $idwarehouse=-1)
Cancel an approved order.
commande ($user, $date, $methode, $comment='')
Submit a supplier order to supplier.
create ($user, $notrigger=0)
Create order with draft status.
update (User $user, $notrigger=0)
Update Supplier Order.
createFromClone (User $user, $socid=0, $notrigger=0)
Load an object from its id and create a new one in database.
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1=0.0, $txlocaltax2=0.0, $fk_product=0, $fk_prod_fourn_price=0, $ref_supplier='', $remise_percent=0.0, $price_base_type='HT', $pu_ttc=0.0, $type=0, $info_bits=0, $notrigger=false, $date_start=null, $date_end=null, $array_options=0, $fk_unit=null, $pu_ht_devise=0, $origin='', $origin_id=0, $rang=-1, $special_code=0)
Add order line.
dispatchProduct ($user, $product, $qty, $entrepot, $price=0, $comment='', $eatby='', $sellby='', $batch='', $fk_commandefourndet=0, $notrigger=0)
Save a receiving into the tracking table of receiving (commande_fournisseur_dispatch) and add product into stock warehouse.
deleteline ($idline, $notrigger=0)
Delete line.
delete (User $user, $notrigger=0)
Delete an order.
get_methodes_commande ()
Get list of order methods.
getDispachedLines ($status=-1)
Return array of dispatched lines waiting to be approved for this order.
Livraison ($user, $date, $type, $comment)
Set a delivery in database for this supplier order.
set_date_livraison ($user, $delivery_date, $notrigger=0)
Set delivery date.
setDeliveryDate ($user, $delivery_date, $notrigger=0)
Set the planned delivery date.
set_id_projet ($user, $id_projet, $notrigger=0)
Set the id projet.
updateFromCommandeClient ($user, $idc, $comclientid)
Update a supplier order from a sales order.
setStatus ($user, $status)
Tag order with a particular status.
updateline ($rowid, $desc, $pu, $qty, $remise_percent, $txtva, $txlocaltax1=0, $txlocaltax2=0, $price_base_type='HT', $info_bits=0, $type=0, $notrigger=0, $date_start='', $date_end='', $array_options=0, $fk_unit=null, $pu_ht_devise=0, $ref_supplier='')
Update line.
initAsSpecimen ()
Initialise an instance with random values.
info ($id)
Charge les informations d'ordre info dans l'objet facture.
load_state_board ()
Charge indicateurs this->nb de tableau de bord.
load_board ($user, $mode='opened')
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
getInputMethod ()
Returns the translated input method of object (defined if $this->methode_commande_id > 0).
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template model.
getMaxDeliveryTimeDay ($langs)
Return the max number delivery delay in day.
getRights ()
Returns the rights used for this class.
hasDelay ()
Is the supplier order delayed? We suppose a purchase ordered as late if a the purchase order has been sent and the delivery date is set and before the delay.
showDelay ()
Show the customer delayed info.
calcAndSetStatusDispatch (User $user, $closeopenorder=1, $comment='')
Calc status regarding to dispatched stock.
loadReceptions ($filtre_statut=-1)
Load array this->receptions of lines of shipments with nb of products sent for each order line Note: For a dedicated shipment, the fetch_lines can be used to load the qty_asked and qty_shipped.
Public Member Functions inherited from CommonOrder
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
static replaceProduct (DoliDB $db, $origin_id, $dest_id)
Function used to replace a product id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
$fields
'type' field format ('integer', 'integer:ObjectClass:PathToClass[:AddCreateButtonOrNot[:Filter[:Sortfield]]]', 'sellist:TableName:LabelFieldName[:KeyFieldName[:KeyFieldParent[:Filter[:Sortfield]]]]', 'varchar(x)', 'double(24,8)', 'real', 'price', 'text', 'text:none', 'html', 'date', 'datetime', 'timestamp', 'duration', 'mail', 'phone', 'url', 'password') Note: Filter can be a string like "(t.ref:like:'SO-%') or (t.date_creation:<:'20160101') or (t.nature:is:NULL)" 'label' the translation key.
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated status.
const STATUS_ACCEPTED = 2
Accepted.
const STATUS_ORDERSENT = 3
Order sent, shipment on process.
const STATUS_RECEIVED_PARTIALLY = 4
Received partially.
const STATUS_RECEIVED_COMPLETELY = 5
Received completely.
const STATUS_CANCELED = 6
Order canceled.
const STATUS_CANCELED_AFTER_ORDER = 7
Order canceled/never received.
const STATUS_REFUSED = 9
Refused.
const SOURCE_ID_REPLENISHMENT = 42
The constant used into source field to track the order was generated by the replenishement feature.
Public Attributes inherited from CommonObject
$projet
$fk_projet
$note
Protected Attributes
$table_ref_field = 'ref'
{}
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage predefined suppliers products.
Definition at line 48 of file fournisseur.commande.class.php.
Constructor & Destructor Documentation
__construct()
CommandeFournisseur::__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 324 of file fournisseur.commande.class.php.
References db.
Member Function Documentation
addline()
CommandeFournisseur::addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0.0, $txlocaltax2 = 0.0, $fk_product = 0, $fk_prod_fourn_price = 0, $ref_supplier = '', $remise_percent = 0.0, $price_base_type = 'HT', $pu_ttc = 0.0, $type = 0, $info_bits = 0, $notrigger = false, $date_start = null, $date_end = null, $array_options = 0, $fk_unit = null, $pu_ht_devise = 0, $origin = '', $origin_id = 0, $rang = -1, $special_code = 0)
Add order line.
Parameters
string $desc Description
float $pu_ht Unit price (used if $price_base_type is 'HT')
float $qty Quantity
float $txtva Taux tva
float $txlocaltax1 Localtax1 tax
float $txlocaltax2 Localtax2 tax
int $fk_product Id product
int $fk_prod_fourn_price Id supplier price
string $ref_supplier Supplier reference price
float $remise_percent Remise
string $price_base_type HT or TTC
float $pu_ttc Unit price TTC (used if $price_base_type is 'TTC')
int $type Type of line (0=product, 1=service)
int $info_bits More information
bool $notrigger Disable triggers
int $date_start Date start of service
int $date_end Date end of service
array $array_options extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
string $pu_ht_devise Amount in currency
string $origin 'order', ...
int $origin_id Id of origin object
int $rang Rank
int $special_code Special code
Returns
int <=0 if KO, >0 if OK
Definition at line 1753 of file fournisseur.commande.class.php.
approve()
CommandeFournisseur::approve ($user, $idwarehouse = 0, $secondlevel = 0)
Approve a supplier order.
Parameters
User $user Object user
int $idwarehouse Id of warhouse for stock change
int $secondlevel 0=Standard approval, 1=Second level approval (used when option SUPPLIER_ORDER_3_STEPS_TO_BE_APPROVED is set)
Returns
int <0 if KO, >0 if OK
Definition at line 1033 of file fournisseur.commande.class.php.
calcAndSetStatusDispatch()
CommandeFournisseur::calcAndSetStatusDispatch (User $user, $closeopenorder = 1, $comment = '')
Calc status regarding to dispatched stock.
Parameters
User $user User action
int $closeopenorder Close if received
string $comment Comment
Returns
int <0 if KO, 0 if not applicable, >0 if OK
Definition at line 3374 of file fournisseur.commande.class.php.
Cancel()
CommandeFournisseur::Cancel ($user, $idwarehouse = -1)
Cancel an approved order.
The cancellation is done after approval
Parameters
User $user User making action
int $idwarehouse Id warehouse to use for stock change (not used for supplier orders).
Returns
int >0 if Ok, <0 if Ko
Definition at line 1225 of file fournisseur.commande.class.php.
classifyBilled()
CommandeFournisseur::classifyBilled (User $user)
Class invoiced the supplier order.
Parameters
User $user Object user making the change
Returns
int <0 if KO, 0 if already billed, >0 if OK
Definition at line 985 of file fournisseur.commande.class.php.
References db.
commande()
CommandeFournisseur::commande ($user, $date, $methode, $comment = '')
Submit a supplier order to supplier.
Parameters
User $user User making change
integer $date Date
int $methode Method
string $comment Comment
Returns
int <0 if KO, >0 if OK
Definition at line 1280 of file fournisseur.commande.class.php.
create()
CommandeFournisseur::create ($user, $notrigger = 0)
Create order with draft status.
Parameters
User $user User making creation
int $notrigger Disable all triggers
Returns
int <0 if KO, Id of supplier order if OK
Definition at line 1339 of file fournisseur.commande.class.php.
createFromClone()
CommandeFournisseur::createFromClone (User $user, $socid = 0, $notrigger = 0)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $socid Id of thirdparty
int $notrigger Disable all triggers
Returns
int New id of clone
Definition at line 1648 of file fournisseur.commande.class.php.
delete()
CommandeFournisseur::delete (User $user, $notrigger = 0)
Delete an order.
Parameters
User $user Object user
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2162 of file fournisseur.commande.class.php.
deleteline()
CommandeFournisseur::deleteline ($idline, $notrigger = 0)
Delete line.
Parameters
int $idline Id of line to delete
int $notrigger 1=Disable call to triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2133 of file fournisseur.commande.class.php.
dispatchProduct()
CommandeFournisseur::dispatchProduct ($user, $product, $qty, $entrepot, $price = 0, $comment = '', $eatby = '', $sellby = '', $batch = '', $fk_commandefourndet = 0, $notrigger = 0)
Save a receiving into the tracking table of receiving (commande_fournisseur_dispatch) and add product into stock warehouse.
Parameters
User $user User object making change
int $product Id of product to dispatch
double $qty Qty to dispatch
int $entrepot Id of warehouse to add product
double $price Unit Price for PMP value calculation (Unit price without Tax and taking into account discount)
string $comment Comment for stock movement
integer $eatby eat-by date
integer $sellby sell-by date
string $batch Lot number
int $fk_commandefourndet Id of supplier order line
int $notrigger 1 = notrigger
Returns
int <0 if KO, >0 if OK
Definition at line 2037 of file fournisseur.commande.class.php.
fetch()
CommandeFournisseur::fetch ($id, $ref = '')
Get object and lines from database.
Parameters
int $id Id of order to load
string $ref Ref of object
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 337 of file fournisseur.commande.class.php.
fetch_lines()
CommandeFournisseur::fetch_lines ($only_product = 0)
Load array lines.
Parameters
int $only_product Return only physical products
Returns
int <0 if KO, >0 if OK
Definition at line 485 of file fournisseur.commande.class.php.
generateDocument()
CommandeFournisseur::generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template model.
Parameters
string $modele Force template to use ('' to not force)
Translate $outputlangs Object lang to use for traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int < 0 if KO, 0 = no doc generated, > 0 if OK
Definition at line 3194 of file fournisseur.commande.class.php.
get_methodes_commande()
CommandeFournisseur::get_methodes_commande ()
Get list of order methods.
Returns
int 0 if OK, <0 if KO
Definition at line 2290 of file fournisseur.commande.class.php.
getDispachedLines()
CommandeFournisseur::getDispachedLines ($status = -1)
Return array of dispatched lines waiting to be approved for this order.
Since
8.0 Return dispatched quantity (qty).
Parameters
int $status Filter on stats (-1 = no filter, 0 = lines draft to be approved, 1 = approved lines)
Returns
array Array of lines
Definition at line 2323 of file fournisseur.commande.class.php.
getInputMethod()
CommandeFournisseur::getInputMethod ()
Returns the translated input method of object (defined if $this->methode_commande_id > 0).
This function make a sql request to get translation. No cache yet, try to not use it inside a loop.
Returns
string
Definition at line 3155 of file fournisseur.commande.class.php.
getLibStatut()
CommandeFournisseur::getLibStatut ($mode = 0)
Return label of the status of object.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=short label + picto
Returns
string Label
Definition at line 736 of file fournisseur.commande.class.php.
getMaxDeliveryTimeDay()
CommandeFournisseur::getMaxDeliveryTimeDay ($langs)
Return the max number delivery delay in day.
Parameters
Translate $langs Language object
Returns
string Translated string
Definition at line 3225 of file fournisseur.commande.class.php.
getNextNumRef()
CommandeFournisseur::getNextNumRef ($soc)
Returns the following order reference not used depending on the numbering model activated defined within COMMANDE_SUPPLIER_ADDON_NUMBER.
Parameters
Societe $soc company object
Returns
string free reference for the invoice
Definition at line 939 of file fournisseur.commande.class.php.
getNomUrl()
CommandeFournisseur::getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $save_lastsearch_value = -1, $addlinktonotes = 0)
Return clicable name (with picto eventually)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
string $option On what the link points
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
int $addlinktonotes Add link to show notes
Returns
string Chain with URL
Definition at line 832 of file fournisseur.commande.class.php.
getRights()
CommandeFournisseur::getRights ()
Returns the rights used for this class.
Returns
stdClass
Reimplemented from CommonObject.
Definition at line 3257 of file fournisseur.commande.class.php.
hasDelay()
CommandeFournisseur::hasDelay ()
Is the supplier order delayed? We suppose a purchase ordered as late if a the purchase order has been sent and the delivery date is set and before the delay.
If order has not been sent, we use the order date.
Returns
bool True if object is delayed
Definition at line 3306 of file fournisseur.commande.class.php.
info()
CommandeFournisseur::info ($id)
Charge les informations d'ordre info dans l'objet facture.
Parameters
int $id Id de la facture a charger
Returns
void
Definition at line 3006 of file fournisseur.commande.class.php.
initAsSpecimen()
CommandeFournisseur::initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 2922 of file fournisseur.commande.class.php.
LibStatut()
CommandeFournisseur::LibStatut ($status, $mode = 0, $billed = 0)
Return label of a status.
Parameters
int $status Id statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
int $billed 1=Billed
Returns
string Label of status
Definition at line 750 of file fournisseur.commande.class.php.
Livraison()
CommandeFournisseur::Livraison ($user, $date, $type, $comment)
Set a delivery in database for this supplier order.
Parameters
User $user User that input data
integer $date Date of reception
string $type Type of receipt ('tot' = total/done, 'par' = partial, 'nev' = never, 'can' = cancel)
string $comment Comment
Returns
int <0 if KO, >0 if OK
Definition at line 2376 of file fournisseur.commande.class.php.
load_board()
CommandeFournisseur::load_board ($user, $mode = 'opened')
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Objet user
int $mode "opened", "awaiting" for orders awaiting reception
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 3092 of file fournisseur.commande.class.php.
load_state_board()
CommandeFournisseur::load_state_board ()
Charge indicateurs this->nb de tableau de bord.
Returns
int <0 si ko, >0 si ok
Definition at line 3052 of file fournisseur.commande.class.php.
loadReceptions()
CommandeFournisseur::loadReceptions ($filtre_statut = -1)
Load array this->receptions of lines of shipments with nb of products sent for each order line Note: For a dedicated shipment, the fetch_lines can be used to load the qty_asked and qty_shipped.
This function is use to return qty_shipped cumulated for the order
Parameters
int $filtre_statut Filter on shipment status
Returns
int <0 if KO, Nb of lines found if OK
Definition at line 3503 of file fournisseur.commande.class.php.
References dol_syslog().
refuse()
CommandeFournisseur::refuse ($user)
Refuse an order.
Parameters
User $user User making action
Returns
int 0 if Ok, <0 if Ko
Definition at line 1176 of file fournisseur.commande.class.php.
replaceProduct()
static CommandeFournisseur::replaceProduct (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a product id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old product id
int $dest_id New product id
Returns
bool
Definition at line 3290 of file fournisseur.commande.class.php.
References CommonObject\commonReplaceProduct().
replaceThirdparty()
static CommandeFournisseur::replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 3273 of file fournisseur.commande.class.php.
References CommonObject\commonReplaceThirdparty().
set_date_livraison()
CommandeFournisseur::set_date_livraison ($user, $delivery_date, $notrigger = 0)
Set delivery date.
Parameters
User $user Object user that modify
int $delivery_date Delivery date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Deprecated:
Use setDeliveryDate
Definition at line 2490 of file fournisseur.commande.class.php.
References setDeliveryDate().
set_id_projet()
CommandeFournisseur::set_id_projet ($user, $id_projet, $notrigger = 0)
Set the id projet.
Parameters
User $user Objet utilisateur qui modifie
int $id_projet Delivery date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 si ko, >0 si ok
Definition at line 2562 of file fournisseur.commande.class.php.
References db.
setDeliveryDate()
CommandeFournisseur::setDeliveryDate ($user, $delivery_date, $notrigger = 0)
Set the planned delivery date.
Parameters
User $user Objet user making change
integer $delivery_date Planned delivery date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2504 of file fournisseur.commande.class.php.
References db.
Referenced by set_date_livraison().
setStatus()
CommandeFournisseur::setStatus ($user, $status)
Tag order with a particular status.
Parameters
User $user Object user that change status
int $status New status
Returns
int <0 if KO, >0 if OK
Definition at line 2660 of file fournisseur.commande.class.php.
showDelay()
CommandeFournisseur::showDelay ()
Show the customer delayed info.
We suppose a purchase ordered as late if a the purchase order has been sent and the delivery date is set and before the delay. If order has not been sent, we use the order date.
Returns
string Show delayed information
Definition at line 3339 of file fournisseur.commande.class.php.
update()
CommandeFournisseur::update (User $user, $notrigger = 0)
Update Supplier Order.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1544 of file fournisseur.commande.class.php.
updateFromCommandeClient()
CommandeFournisseur::updateFromCommandeClient ($user, $idc, $comclientid)
Update a supplier order from a sales order.
Parameters
User $user User that create
int $idc Id of purchase order to update
int $comclientid Id of sale order to use as template
Returns
int <0 if KO, >0 if OK
Definition at line 2620 of file fournisseur.commande.class.php.
References db.
updateline()
CommandeFournisseur::updateline ($rowid, $desc, $pu, $qty, $remise_percent, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $price_base_type = 'HT', $info_bits = 0, $type = 0, $notrigger = 0, $date_start = '', $date_end = '', $array_options = 0, $fk_unit = null, $pu_ht_devise = 0, $ref_supplier = '')
Update line.
Parameters
int $rowid Id de la ligne de facture
string $desc Description de la ligne
double $pu Prix unitaire
double $qty Quantity
double $remise_percent Percent discount on line
double $txtva VAT rate
double $txlocaltax1 Localtax1 tax
double $txlocaltax2 Localtax2 tax
double $price_base_type Type of price base
int $info_bits Miscellaneous informations
int $type Type of line (0=product, 1=service)
int $notrigger Disable triggers
integer $date_start Date start of service
integer $date_end Date end of service
array $array_options Extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
double $pu_ht_devise Unit price in currency
string $ref_supplier Supplier ref
Returns
int < 0 if error, > 0 if ok
Definition at line 2731 of file fournisseur.commande.class.php.
valid()
CommandeFournisseur::valid ($user, $idwarehouse = 0, $notrigger = 0)
Validate an order.
Parameters
User $user Validator User
int $idwarehouse Id of warehouse to use for stock decrease
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 625 of file fournisseur.commande.class.php.
Member Data Documentation
$fields
CommandeFournisseur::$fields
'type' field format ('integer', 'integer:ObjectClass:PathToClass[:AddCreateButtonOrNot[:Filter[:Sortfield]]]', 'sellist:TableName:LabelFieldName[:KeyFieldName[:KeyFieldParent[:Filter[:Sortfield]]]]', 'varchar(x)', 'double(24,8)', 'real', 'price', 'text', 'text:none', 'html', 'date', 'datetime', 'timestamp', 'duration', 'mail', 'phone', 'url', 'password') Note: Filter can be a string like "(t.ref:like:'SO-%') or (t.date_creation:<:'20160101') or (t.nature:is:NULL)" 'label' the translation key.
'picto' is code of a picto to show before value in forms 'enabled' is a condition when the field must be managed (Example: 1 or '$conf->global->MY_SETUP_PARAM' or 'isModEnabled("multicurrency")' ...) 'position' is the sort order of field. 'notnull' is set to 1 if not null in database. Set to -1 if we must set data to null if empty ('' or 0). 'visible' says if field is visible in list (Examples: 0=Not visible, 1=Visible on list and create/update/view forms, 2=Visible on list only, 3=Visible on create/update/view form only (not list), 4=Visible on list and update/view form only (not create). 5=Visible on list and view only (not create/not update). Using a negative value means field is not shown by default on list but can be selected for viewing) 'noteditable' says if field is not editable (1 or 0) 'default' is a default value for creation (can still be overwrote by the Setup of Default Values if field is editable in creation form). Note: If default is set to '(PROV)' and field is 'ref', the default value will be set to '(PROVid)' where id is rowid when a new record is created. 'index' if we want an index in database. 'foreignkey'=>'tablename.field' if the field is a foreign key (it is recommanded to name the field fk_...). 'searchall' is 1 if we want to search in this field when making a search from the quick search button. 'isameasure' must be set to 1 or 2 if field can be used for measure. Field type must be summable like integer or double(24,8). Use 1 in most cases, or 2 if you don't want to see the column total into list (for example for percentage) 'css' and 'cssview' and 'csslist' is the CSS style to use on field. 'css' is used in creation and update. 'cssview' is used in view mode. 'csslist' is used for columns in lists. For example: 'css'=>'minwidth300 maxwidth500 widthcentpercentminusx', 'cssview'=>'wordbreak', 'csslist'=>'tdoverflowmax200' 'help' is a 'TranslationString' to use to show a tooltip on field. You can also use 'TranslationString:keyfortooltiponlick' for a tooltip on click. 'showoncombobox' if value of the field must be visible into the label of the combobox that list record 'disabled' is 1 if we want to have the field locked by a 'disabled' attribute. In most cases, this is never set into the definition of $fields into class, but is set dynamically by some part of code. 'arrayofkeyval' to set a list of values if type is a list of predefined values. For example: array("0"=>"Draft","1"=>"Active","-1"=>"Cancel"). Note that type can be 'integer' or 'varchar' 'autofocusoncreate' to have field having the focus on a create form. Only 1 field should have this property set to 1. 'comment' is not used. You can store here any text of your choice. It is not used by application. 'validate' is 1 if need to validate with $this->validateField() 'copytoclipboard' is 1 or 2 to allow to add a picto to copy value into clipboard (1=picto after label, 2=picto after value)
Note: To have value dynamic, you can set value to 0 in definition and edit the value on the fly into the constructor.
Definition at line 217 of file fournisseur.commande.class.php.
The documentation for this class was generated from the following file:
htdocs/fourn/class/fournisseur.commande.class.php