dolibarr: Propal Class Reference
Propal Class Reference
Class to manage proposals.
Public Member Functions
__construct ($db, $socid=0, $propalid=0)
Constructor.
add_product ($idproduct, $qty, $remise_percent=0)
Add line into array ->lines $this->thirdparty should be loaded.
insert_discount ($idremise)
Adding line of fixed discount in the proposal in DB.
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1=0.0, $txlocaltax2=0.0, $fk_product=0, $remise_percent=0.0, $price_base_type='HT', $pu_ttc=0.0, $info_bits=0, $type=0, $rang=-1, $special_code=0, $fk_parent_line=0, $fk_fournprice=0, $pa_ht=0, $label='', $date_start='', $date_end='', $array_options=0, $fk_unit=null, $origin='', $origin_id=0, $pu_ht_devise=0, $fk_remise_except=0, $noupdateafterinsertline=0)
Add a proposal line into database (linked to product/service or not) The parameters are already supposed to be appropriate and with final values to the call of this method.
updateline ($rowid, $pu, $qty, $remise_percent, $txtva, $txlocaltax1=0.0, $txlocaltax2=0.0, $desc='', $price_base_type='HT', $info_bits=0, $special_code=0, $fk_parent_line=0, $skip_update_total=0, $fk_fournprice=0, $pa_ht=0, $label='', $type=0, $date_start='', $date_end='', $array_options=0, $fk_unit=null, $pu_ht_devise=0, $notrigger=0, $rang=0)
Update a proposal line.
deleteline ($lineid)
Delete detail line.
create ($user, $notrigger=0)
Create commercial proposal into database this->ref can be set or empty.
createFromClone (User $user, $socid=0, $forceentity=null, $update_prices=false)
Load an object from its id and create a new one in database.
fetch ($rowid, $ref='', $ref_ext='', $forceentity=0)
Load a proposal from database.
update (User $user, $notrigger=0)
Update database.
fetch_lines ($only_product=0, $loadalsotranslation=0, $filters='')
Load array lines.
valid ($user, $notrigger=0)
Set status to validated.
set_date ($user, $date, $notrigger=0)
Define proposal date.
set_echeance ($user, $date_end_validity, $notrigger=0)
Define end validity date.
set_date_livraison ($user, $delivery_date, $notrigger=0)
Set delivery date.
setDeliveryDate ($user, $delivery_date, $notrigger=0)
Set delivery date.
set_availability ($user, $id, $notrigger=0)
Set delivery.
set_demand_reason ($user, $id, $notrigger=0)
Set source of demand.
set_ref_client ($user, $ref_client, $notrigger=0)
Set customer reference number.
set_remise_percent ($user, $remise, $notrigger=0)
Set an overall discount on the proposal.
set_remise_absolue ($user, $remise, $notrigger=0)
Set an absolute overall discount on the proposal.
reopen ($user, $status, $note='', $notrigger=0)
Reopen the commercial proposal.
closeProposal ($user, $status, $note='', $notrigger=0)
Close/set the commercial proposal to status signed or refused (fill also date signature)
classifyBilled (User $user, $notrigger=0, $note='')
Classify the proposal to status Billed.
setDraft ($user, $notrigger=0)
Set draft status.
liste_array ($shortlist=0, $draft=0, $notcurrentuser=0, $socid=0, $limit=0, $offset=0, $sortfield='p.datep', $sortorder='DESC')
Return list of proposal (eventually filtered on user) into an array.
getInvoiceArrayList ()
Returns an array with the numbers of related invoices.
InvoiceArrayList ($id)
Returns an array with id and ref of related invoices.
delete ($user, $notrigger=0)
Delete proposal.
availability ($availability_id, $notrigger=0)
Change the delivery time.
demand_reason ($demand_reason_id, $notrigger=0)
Change source demand.
info ($id)
Object Proposal Information.
getLibStatut ($mode=0)
Return label of status of proposal (draft, validated, ...)
LibStatut ($status, $mode=1)
Return label of a status (draft, validated, ...)
load_board ($user, $mode)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
initAsSpecimen ()
Initialise an instance with random values.
load_state_board ()
Charge indicateurs this->nb de tableau de bord.
getNextNumRef ($soc)
Returns the reference to the following non used Proposal used depending on the active numbering module defined into PROPALE_ADDON.
getNomUrl ($withpicto=0, $option='', $get_params='', $notooltip=0, $save_lastsearch_value=-1, $addlinktonotes=-1)
Return clicable link of object (with eventually picto)
getLinesArray ($filters='')
Retrieve an array of proposal lines.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
static replaceProduct (DoliDB $db, $origin_id, $dest_id)
Function used to replace a product id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
$datec
$datev
$datep
$price
$tva
$total
$remise
$remise_absolue
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated status.
const STATUS_SIGNED = 2
Signed quote.
const STATUS_NOTSIGNED = 3
Not signed quote.
const STATUS_BILLED = 4
Billed or processed quote.
Public Attributes inherited from CommonObject
$projet
$fk_projet
$note
Protected Attributes
$table_ref_field = 'ref'
{}
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage proposals.
Definition at line 52 of file propal.class.php.
Constructor & Destructor Documentation
__construct()
Propal::__construct ($db, $socid = 0, $propalid = 0)
Constructor.
Parameters
DoliDB $db Database handler
int $socid Id third party
int $propalid Id proposal
Definition at line 383 of file propal.class.php.
Member Function Documentation
add_product()
Propal::add_product ($idproduct, $qty, $remise_percent = 0)
Add line into array ->lines $this->thirdparty should be loaded.
Parameters
int $idproduct Product Id to add
int $qty Quantity
int $remise_percent Discount effected on Product
Returns
int <0 if KO, >0 if OK
TODO Replace calls to this function by generation objet Ligne
Definition at line 408 of file propal.class.php.
addline()
Propal::addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0.0, $txlocaltax2 = 0.0, $fk_product = 0, $remise_percent = 0.0, $price_base_type = 'HT', $pu_ttc = 0.0, $info_bits = 0, $type = 0, $rang = -1, $special_code = 0, $fk_parent_line = 0, $fk_fournprice = 0, $pa_ht = 0, $label = '', $date_start = '', $date_end = '', $array_options = 0, $fk_unit = null, $origin = '', $origin_id = 0, $pu_ht_devise = 0, $fk_remise_except = 0, $noupdateafterinsertline = 0)
Add a proposal line into database (linked to product/service or not) The parameters are already supposed to be appropriate and with final values to the call of this method.
Also, for the VAT rate, it must have already been defined by whose calling the method get_default_tva (societe_vendeuse, societe_acheteuse, '' product) and desc must already have the right value (it's up to the caller to manage multilanguage)
Parameters
string $desc Description of line
float $pu_ht Unit price
float $qty Quantity
float $txtva Force Vat rate, -1 for auto (Can contain the vat_src_code too with syntax '9.9 (CODE)')
float $txlocaltax1 Local tax 1 rate (deprecated, use instead txtva with code inside)
float $txlocaltax2 Local tax 2 rate (deprecated, use instead txtva with code inside)
int $fk_product Product/Service ID predefined
float $remise_percent Pourcentage de remise de la ligne
string $price_base_type HT or TTC
float $pu_ttc Prix unitaire TTC
int $info_bits Bits for type of lines
int $type Type of line (0=product, 1=service). Not used if fk_product is defined, the type of product is used.
int $rang Position of line
int $special_code Special code (also used by externals modules!)
int $fk_parent_line Id of parent line
int $fk_fournprice Id supplier price
int $pa_ht Buying price without tax
string $label ???
int $date_start Start date of the line
int $date_end End date of the line
array $array_options extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
string $origin Depend on global conf MAIN_CREATEFROM_KEEP_LINE_ORIGIN_INFORMATION can be 'orderdet', 'propaldet'..., else 'order','propal,'....
int $origin_id Depend on global conf MAIN_CREATEFROM_KEEP_LINE_ORIGIN_INFORMATION can be Id of origin object (aka line id), else object id
double $pu_ht_devise Unit price in currency
int $fk_remise_except Id discount if line is from a discount
int $noupdateafterinsertline No update after insert of line
Returns
int >0 if OK, <0 if KO
See also
add_product()
Definition at line 568 of file propal.class.php.
availability()
Propal::availability ($availability_id, $notrigger = 0)
Change the delivery time.
Parameters
int $availability_id Id of new delivery time
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int >0 if OK, <0 if KO
Deprecated:
use set_availability
Definition at line 3159 of file propal.class.php.
classifyBilled()
Propal::classifyBilled (User $user, $notrigger = 0, $note = '')
Classify the proposal to status Billed.
Parameters
User $user Object user
int $notrigger 1=Does not execute triggers, 0= execute triggers
string $note Complete private note with this note
Returns
int <0 if KO, 0 = nothing done, >0 if OK
Definition at line 2730 of file propal.class.php.
closeProposal()
Propal::closeProposal ($user, $status, $note = '', $notrigger = 0)
Close/set the commercial proposal to status signed or refused (fill also date signature)
Parameters
User $user Object user that close
int $status Status (self::STATUS_BILLED or self::STATUS_REFUSED)
string $note Complete private note with this note
int $notrigger 1=Does not execute triggers, 0=Execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2617 of file propal.class.php.
create()
Propal::create ($user, $notrigger = 0)
Create commercial proposal into database this->ref can be set or empty.
If empty, we will use "(PROVid)"
Parameters
User $user User that create
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >=0 if OK
Definition at line 1024 of file propal.class.php.
createFromClone()
Propal::createFromClone (User $user, $socid = 0, $forceentity = null, $update_prices = false)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $socid Id of thirdparty
int $forceentity Entity id to force
bool $update_prices [=false] Update prices if true
Returns
int New id of clone
Definition at line 1345 of file propal.class.php.
delete()
Propal::delete ($user, $notrigger = 0)
Delete proposal.
Parameters
User $user Object user that delete
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int >0 if OK, <=0 if KO
Definition at line 3037 of file propal.class.php.
deleteline()
Propal::deleteline ($lineid)
Delete detail line.
Parameters
int $lineid Id of line to delete
Returns
int >0 if OK, <0 if KO
Definition at line 986 of file propal.class.php.
demand_reason()
Propal::demand_reason ($demand_reason_id, $notrigger = 0)
Change source demand.
Parameters
int $demand_reason_id Id of new source demand
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int >0 si ok, <0 si ko
Deprecated:
use set_demand_reason
Definition at line 3222 of file propal.class.php.
fetch()
Propal::fetch ($rowid, $ref = '', $ref_ext = '', $forceentity = 0)
Load a proposal from database.
Get also lines.
Parameters
int $rowid Id of object to load
string $ref Ref of proposal
string $ref_ext Ref ext of proposal
int $forceentity Entity id to force when searching on ref or ref_ext
Returns
int >0 if OK, <0 if KO
Definition at line 1520 of file propal.class.php.
fetch_lines()
Propal::fetch_lines ($only_product = 0, $loadalsotranslation = 0, $filters = '')
Load array lines.
Parameters
int $only_product Return only physical products
int $loadalsotranslation Return translation for products
string $filters Filter on other fields
Returns
int <0 if KO, >0 if OK
Definition at line 1808 of file propal.class.php.
generateDocument()
Propal::generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Force model to use ('' to not force)
Translate $outputlangs Object langs to use for output
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int 0 if KO, 1 if OK
Definition at line 3838 of file propal.class.php.
getInvoiceArrayList()
Propal::getInvoiceArrayList ()
Returns an array with the numbers of related invoices.
Returns
array Array of invoices
Definition at line 2952 of file propal.class.php.
References InvoiceArrayList().
getLibStatut()
Propal::getLibStatut ($mode = 0)
Return label of status of proposal (draft, validated, ...)
Parameters
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label
Definition at line 3340 of file propal.class.php.
getLinesArray()
Propal::getLinesArray ($filters = '')
Retrieve an array of proposal lines.
Parameters
string $filters Filter on other fields
Returns
int >0 if OK, <0 if KO
Definition at line 3822 of file propal.class.php.
getNextNumRef()
Propal::getNextNumRef ($soc)
Returns the reference to the following non used Proposal used depending on the active numbering module defined into PROPALE_ADDON.
Parameters
Societe $soc Object thirdparty
Returns
string Reference libre pour la propale
Definition at line 3623 of file propal.class.php.
getNomUrl()
Propal::getNomUrl ($withpicto = 0, $option = '', $get_params = '', $notooltip = 0, $save_lastsearch_value = -1, $addlinktonotes = -1)
Return clicable link of object (with eventually picto)
Parameters
int $withpicto Add picto into link
string $option Where point the link ('expedition', 'document', ...)
string $get_params Parametres added to url
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
int $addlinktonotes -1=Disable, 0=Just add label show notes, 1=Add private note (only internal user), 2=Add public note (internal or external user), 3=Add private (internal user) and public note (internal and external user)
Returns
string String with URL
Definition at line 3678 of file propal.class.php.
info()
Propal::info ($id)
Object Proposal Information.
Parameters
int $id Proposal id
Returns
void
Definition at line 3284 of file propal.class.php.
initAsSpecimen()
Propal::initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 3491 of file propal.class.php.
insert_discount()
Propal::insert_discount ($idremise)
Adding line of fixed discount in the proposal in DB.
Parameters
int $idremise Id of fixed discount
Returns
int >0 if OK, <0 if KO
Definition at line 466 of file propal.class.php.
InvoiceArrayList()
Propal::InvoiceArrayList ($id)
Returns an array with id and ref of related invoices.
Parameters
int $id Id propal
Returns
array Array of invoices id
Definition at line 2964 of file propal.class.php.
References CommonObject\fetchObjectLinked().
Referenced by getInvoiceArrayList().
LibStatut()
Propal::LibStatut ($status, $mode = 1)
Return label of a status (draft, validated, ...)
Parameters
int $status Id status
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label
Definition at line 3353 of file propal.class.php.
liste_array()
Propal::liste_array ($shortlist = 0, $draft = 0, $notcurrentuser = 0, $socid = 0, $limit = 0, $offset = 0, $sortfield = 'p.datep', $sortorder = 'DESC')
Return list of proposal (eventually filtered on user) into an array.
Parameters
int $shortlist 0=Return array[id]=ref, 1=Return array[](id=>id,ref=>ref,name=>name)
int $draft 0=not draft, 1=draft
int $notcurrentuser 0=all user, 1=not current user
int $socid Id third pary
int $limit For pagination
int $offset For pagination
string $sortfield Sort criteria
string $sortorder Sort order
Returns
int -1 if KO, array with result if OK
Definition at line 2884 of file propal.class.php.
load_board()
Propal::load_board ($user, $mode)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Object user
int $mode "opened" for proposal to close, "signed" for proposal to invoice
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 3407 of file propal.class.php.
load_state_board()
Propal::load_state_board ()
Charge indicateurs this->nb de tableau de bord.
Returns
int <0 if ko, >0 if ok
Definition at line 3582 of file propal.class.php.
reopen()
Propal::reopen ($user, $status, $note = '', $notrigger = 0)
Reopen the commercial proposal.
Parameters
User $user Object user that close
int $status Status
string $note Comment
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2558 of file propal.class.php.
replaceProduct()
static Propal::replaceProduct (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a product id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old product id
int $dest_id New product id
Returns
bool
Definition at line 3885 of file propal.class.php.
References CommonObject\commonReplaceProduct().
replaceThirdparty()
static Propal::replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 3868 of file propal.class.php.
References CommonObject\commonReplaceThirdparty().
set_availability()
Propal::set_availability ($user, $id, $notrigger = 0)
Set delivery.
Parameters
User $user Object user that modify
int $id Availability id
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2249 of file propal.class.php.
References db.
set_date()
Propal::set_date ($user, $date, $notrigger = 0)
Define proposal date.
Parameters
User $user Object user that modify
int $date Date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2060 of file propal.class.php.
set_date_livraison()
Propal::set_date_livraison ($user, $delivery_date, $notrigger = 0)
Set delivery date.
Parameters
User $user Object user that modify
int $delivery_date Delivery date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Deprecated:
Use setDeliveryDate
Definition at line 2179 of file propal.class.php.
References setDeliveryDate().
set_demand_reason()
Propal::set_demand_reason ($user, $id, $notrigger = 0)
Set source of demand.
Parameters
User $user Object user that modify
int $id Input reason id
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2312 of file propal.class.php.
References db.
set_echeance()
Propal::set_echeance ($user, $date_end_validity, $notrigger = 0)
Define end validity date.
Parameters
User $user Object user that modify
int $date_end_validity End of validity date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2122 of file propal.class.php.
References db.
set_ref_client()
Propal::set_ref_client ($user, $ref_client, $notrigger = 0)
Set customer reference number.
Parameters
User $user Object user that modify
string $ref_client Customer reference
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Definition at line 2377 of file propal.class.php.
References db.
set_remise_absolue()
Propal::set_remise_absolue ($user, $remise, $notrigger = 0)
Set an absolute overall discount on the proposal.
Parameters
User $user Object user that modify
double $remise Amount discount
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Definition at line 2495 of file propal.class.php.
References $remise, db, and price2num().
set_remise_percent()
Propal::set_remise_percent ($user, $remise, $notrigger = 0)
Set an overall discount on the proposal.
Parameters
User $user Object user that modify
double $remise Amount discount
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Definition at line 2434 of file propal.class.php.
References $remise, db, and price2num().
setDeliveryDate()
Propal::setDeliveryDate ($user, $delivery_date, $notrigger = 0)
Set delivery date.
Parameters
User $user Object user that modify
int $delivery_date Delivery date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Definition at line 2193 of file propal.class.php.
References db.
Referenced by set_date_livraison().
setDraft()
Propal::setDraft ($user, $notrigger = 0)
Set draft status.
Parameters
User $user Object user that modify
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2815 of file propal.class.php.
References db, and dol_syslog().
update()
Propal::update (User $user, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1696 of file propal.class.php.
updateline()
Propal::updateline ($rowid, $pu, $qty, $remise_percent, $txtva, $txlocaltax1 = 0.0, $txlocaltax2 = 0.0, $desc = '', $price_base_type = 'HT', $info_bits = 0, $special_code = 0, $fk_parent_line = 0, $skip_update_total = 0, $fk_fournprice = 0, $pa_ht = 0, $label = '', $type = 0, $date_start = '', $date_end = '', $array_options = 0, $fk_unit = null, $pu_ht_devise = 0, $notrigger = 0, $rang = 0)
Update a proposal line.
Parameters
int $rowid Id of line
float $pu Unit price (HT or TTC depending on price_base_type)
float $qty Quantity
float $remise_percent Discount on line
float $txtva VAT Rate (Can be '1.23' or '1.23 (ABC)')
float $txlocaltax1 Local tax 1 rate
float $txlocaltax2 Local tax 2 rate
string $desc Description
string $price_base_type HT or TTC
int $info_bits Miscellaneous informations
int $special_code Special code (also used by externals modules!)
int $fk_parent_line Id of parent line (0 in most cases, used by modules adding sublevels into lines).
int $skip_update_total Keep fields total_xxx to 0 (used for special lines by some modules)
int $fk_fournprice Id of origin supplier price
int $pa_ht Price (without tax) of product when it was bought
string $label ???
int $type 0/1=Product/service
int $date_start Start date of the line
int $date_end End date of the line
array $array_options extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
double $pu_ht_devise Unit price in currency
int $notrigger disable line update trigger
integer $rang line rank
Returns
int 0 if OK, <0 if KO
Definition at line 815 of file propal.class.php.
valid()
Propal::valid ($user, $notrigger = 0)
Set status to validated.
Parameters
User $user Object user that validate
int $notrigger 1=Does not execute triggers, 0=execute triggers
Returns
int <0 if KO, 0=Nothing done, >=0 if OK
Definition at line 1941 of file propal.class.php.
Member Data Documentation
$datec
Propal::$datec
Deprecated:
See also
$date_creation
Definition at line 140 of file propal.class.php.
$datep
Propal::$datep
Deprecated:
See also
$date
Definition at line 177 of file propal.class.php.
$datev
Propal::$datev
Deprecated:
See also
$date_validation
Definition at line 151 of file propal.class.php.
$price
Propal::$price
Deprecated:
See also
$total_ht
Definition at line 201 of file propal.class.php.
$remise
Propal::$remise
Deprecated:
Definition at line 221 of file propal.class.php.
Referenced by set_remise_absolue(), and set_remise_percent().
$remise_absolue
Propal::$remise_absolue
Deprecated:
Definition at line 225 of file propal.class.php.
$total
Propal::$total
Deprecated:
See also
$total_ttc
Definition at line 211 of file propal.class.php.
$tva
Propal::$tva
Deprecated:
See also
$total_tva
Definition at line 206 of file propal.class.php.
The documentation for this class was generated from the following file:
htdocs/comm/propal/class/propal.class.php