dolibarr: ExportExcel2007 Class Reference
ExportExcel2007 Class Reference
Class to build export files with Excel format.
Public Member Functions
__construct ($db)
Constructor.
getDriverId ()
getDriverId
getDriverLabel ()
getDriverLabel
getDriverDesc ()
getDriverDesc
getDriverExtension ()
getDriverExtension
getDriverVersion ()
getDriverVersion
getLibLabel ()
getLibLabel
getLibVersion ()
getLibVersion
open_file ($file, $outputlangs)
Open output file.
write_header ($outputlangs)
Write header.
write_title ($array_export_fields_label, $array_selected_sorted, $outputlangs, $array_types)
Output title line into file.
write_record ($array_selected_sorted, $objp, $outputlangs, $array_types)
Output record line into file.
write_footer ($outputlangs)
Write footer.
close_file ()
Close Excel file.
excel_clean ($newvalue)
Clean a cell to respect rules of Excel file cells.
column2Letter ($c)
Convert a column to letter (1->A, 0->B, 27->AA, ...)
setCellValue ($val, $startCell, $endCell='')
Set cell value and automatically merge if we give an endcell.
setBorderStyle ($thickness, $color)
Set border style.
setFontStyle ($bold, $color)
Set font style.
setAlignmentStyle ($horizontal)
Set alignment style (horizontal, left, right, ...)
resetStyle ()
Reset Style.
setBlock ($startCell, $TDatas=array(), $boldTitle=false)
Make a NxN Block in sheet.
setBlock2Columns ($startCell, $TDatas=array(), $boldTitle=false)
Make a 2xN Tab in Sheet.
enableAutosize ($firstColumn, $lastColumn)
Enable auto sizing for column range.
setMergeCellValueByLength ($val, $startCell, $length, $offset=0)
Set a value cell and merging it by giving a starting cell and a length.
Public Member Functions inherited from ModeleExports
listOfAvailableExportFormat ($db, $maxfilenamelength=0)
Load into memory list of available export format.
getPictoForKey ($key)
Return picto of export driver.
getDriverLabelForKey ($key)
Renvoi libelle d'un driver export.
getDriverDescForKey ($key)
Renvoi le descriptif d'un driver export.
getDriverVersionForKey ($key)
Renvoi version d'un driver export.
getLibLabelForKey ($key)
Renvoi libelle de librairie externe du driver.
getLibVersionForKey ($key)
Renvoi version de librairie externe du driver.
Public Member Functions inherited from CommonDocGenerator
get_substitutionarray_user ($user, $outputlangs)
Define array with couple substitution key => substitution value.
getSubstitutionarrayMember ($member, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_thirdparty ($object, $outputlangs, $array_key='company')
Define array with couple substitution key => substitution value For example {company_name}, {company_name_alias}.
get_substitutionarray_contact ($object, $outputlangs, $array_key='object')
Define array with couple substitution key => substitution value.
get_substitutionarray_other ($outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_object ($object, $outputlangs, $array_key='object')
Define array with couple substitution key => substitution value.
get_substitutionarray_lines ($line, $outputlangs, $linenumber=0)
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment ($object, $outputlangs, $array_key='object')
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_each_var_object (&$object, $outputlangs, $recursive=1)
Define array with couple substitution key => substitution value.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
printRect ($pdf, $x, $y, $l, $h, $hidetop=0, $hidebottom=0)
Rect pdf.
columnSort ($a, $b)
uasort callback function to Sort columns fields
prepareArrayColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Prepare Array Column Field.
getColumnContentWidth ($colKey)
get column content width from column key
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
getColumnRank ($colKey)
get column position rank from column key
insertNewColumnDef ($newColKey, $defArray, $targetCol=false, $insertAfterTarget=false)
get column position rank from column key
printStdColumnContent ($pdf, &$curY, $colKey, $columnText='')
print standard column content
printColDescContent ($pdf, &$curY, $colKey, $object, $i, $outputlangs, $hideref=0, $hidedesc=0, $issupplierline=0)
print description column content
getExtrafieldContent ($object, $extrafieldKey, $outputlangs=null)
get extrafield content for pdf writeHtmlCell compatibility usage for PDF line columns and object note block
getColumnStatus ($colKey)
get column status from column key
pdfTabTitles (&$pdf, $tab_top, $tab_height, $outputlangs, $hidetop=0)
Print standard column content.
defineColumnExtrafield ($object, $outputlangs, $hidedetails=0)
Define Array Column Field for extrafields.
Detailed Description
Class to build export files with Excel format.
Definition at line 35 of file export_excel2007.modules.php.
Constructor & Destructor Documentation
__construct()
ExportExcel2007::__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Reimplemented from CommonDocGenerator.
Definition at line 77 of file export_excel2007.modules.php.
Member Function Documentation
close_file()
ExportExcel2007::close_file ()
Close Excel file.
Returns
int <0 if KO, >0 if OK
Definition at line 422 of file export_excel2007.modules.php.
column2Letter()
ExportExcel2007::column2Letter ($c)
Convert a column to letter (1->A, 0->B, 27->AA, ...)
Parameters
int $c Column position
Returns
string Letter
Definition at line 459 of file export_excel2007.modules.php.
enableAutosize()
ExportExcel2007::enableAutosize ($firstColumn, $lastColumn)
Enable auto sizing for column range.
Parameters
string $firstColumn first column to autosize
string $lastColumn to last column to autosize
Returns
int 1
Definition at line 644 of file export_excel2007.modules.php.
excel_clean()
ExportExcel2007::excel_clean ($newvalue)
Clean a cell to respect rules of Excel file cells.
Parameters
string $newvalue String to clean
Returns
string Value cleaned
Definition at line 443 of file export_excel2007.modules.php.
References dol_string_nohtmltag().
getDriverDesc()
ExportExcel2007::getDriverDesc ()
getDriverDesc
Returns
string
Definition at line 126 of file export_excel2007.modules.php.
getDriverExtension()
ExportExcel2007::getDriverExtension ()
getDriverExtension
Returns
string
Definition at line 136 of file export_excel2007.modules.php.
getDriverId()
ExportExcel2007::getDriverId ()
getDriverId
Returns
string
Definition at line 106 of file export_excel2007.modules.php.
getDriverLabel()
ExportExcel2007::getDriverLabel ()
getDriverLabel
Returns
string Return driver label
Definition at line 116 of file export_excel2007.modules.php.
getDriverVersion()
ExportExcel2007::getDriverVersion ()
getDriverVersion
Returns
string
Definition at line 146 of file export_excel2007.modules.php.
getLibLabel()
ExportExcel2007::getLibLabel ()
getLibLabel
Returns
string
Definition at line 156 of file export_excel2007.modules.php.
getLibVersion()
ExportExcel2007::getLibVersion ()
getLibVersion
Returns
string
Definition at line 166 of file export_excel2007.modules.php.
open_file()
ExportExcel2007::open_file ($file, $outputlangs)
Open output file.
Parameters
string $file File name to generate
Translate $outputlangs Output language object
Returns
int <0 if KO, >=0 if OK
Definition at line 180 of file export_excel2007.modules.php.
resetStyle()
ExportExcel2007::resetStyle ()
Reset Style.
Returns
int 1
Definition at line 555 of file export_excel2007.modules.php.
setAlignmentStyle()
ExportExcel2007::setAlignmentStyle ($horizontal)
Set alignment style (horizontal, left, right, ...)
Parameters
string $horizontal PhpOffice\PhpSpreadsheet\Style\Alignment
Returns
int 1
Definition at line 545 of file export_excel2007.modules.php.
setBlock()
ExportExcel2007::setBlock ($startCell, $TDatas = array(), $boldTitle = false)
Make a NxN Block in sheet.
Parameters
string $startCell starting cell
array $TDatas array(ColumnName=>array(Row value 1, row value 2, etc ...))
bool $boldTitle true if bold headers
Returns
int 1 if OK, -1 if KO
Definition at line 569 of file export_excel2007.modules.php.
References setCellValue(), and setFontStyle().
setBlock2Columns()
ExportExcel2007::setBlock2Columns ($startCell, $TDatas = array(), $boldTitle = false)
Make a 2xN Tab in Sheet.
Parameters
string $startCell A1
array $TDatas array(Title=>val)
bool $boldTitle true if bold titles
Returns
int 1 if OK, -1 if KO
Definition at line 609 of file export_excel2007.modules.php.
setBorderStyle()
ExportExcel2007::setBorderStyle ($thickness, $color)
Set border style.
Parameters
string $thickness style \PhpOffice\PhpSpreadsheet\Style\Border
string $color color \PhpOffice\PhpSpreadsheet\Style\Color
Returns
int 1 if ok
Definition at line 512 of file export_excel2007.modules.php.
setCellValue()
ExportExcel2007::setCellValue ($val, $startCell, $endCell = '')
Set cell value and automatically merge if we give an endcell.
Parameters
string $val cell value
string $startCell starting cell
string $endCell ending cell
Returns
int 1 if success -1 if failed
Definition at line 484 of file export_excel2007.modules.php.
Referenced by setBlock().
setFontStyle()
ExportExcel2007::setFontStyle ($bold, $color)
Set font style.
Parameters
bool $bold true if bold
string $color color \PhpOffice\PhpSpreadsheet\Style\Color
Returns
int 1
Definition at line 530 of file export_excel2007.modules.php.
Referenced by setBlock().
setMergeCellValueByLength()
ExportExcel2007::setMergeCellValueByLength ($val, $startCell, $length, $offset = 0)
Set a value cell and merging it by giving a starting cell and a length.
Parameters
string $val Cell value
string $startCell Starting cell
int $length Length
int $offset Starting offset
Returns
string Coordinate or -1 if KO
Definition at line 661 of file export_excel2007.modules.php.
write_footer()
ExportExcel2007::write_footer ($outputlangs)
Write footer.
Parameters
Translate $outputlangs Output language object
Returns
int <0 if KO, >0 if OK
Definition at line 409 of file export_excel2007.modules.php.
write_header()
ExportExcel2007::write_header ($outputlangs)
Write header.
Parameters
Translate $outputlangs Object lang to translate values
Returns
int <0 if KO, >0 if OK
Definition at line 229 of file export_excel2007.modules.php.
write_record()
ExportExcel2007::write_record ($array_selected_sorted, $objp, $outputlangs, $array_types)
Output record line into file.
Parameters
array $array_selected_sorted Array with list of field to export
resource $objp A record from a fetch with all fields from select
Translate $outputlangs Object lang to translate values
array $array_types Array with types of fields
Returns
int <0 if KO, >0 if OK
Definition at line 308 of file export_excel2007.modules.php.
write_title()
ExportExcel2007::write_title ($array_export_fields_label, $array_selected_sorted, $outputlangs, $array_types)
Output title line into file.
Parameters
array $array_export_fields_label Array with list of label of fields
array $array_selected_sorted Array with list of field to export
Translate $outputlangs Object lang to translate values
array $array_types Array with types of fields
Returns
int <0 if KO, >0 if OK
Definition at line 248 of file export_excel2007.modules.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/export/export_excel2007.modules.php