<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once $pathdepth ? str_repeat('../', $pathdepth) : './'.'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>about</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="about" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 17.0.0-alpha (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="152" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script async src="/javascript.js.php"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->
<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
			<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous"></script>
	<!-- Font Awesome -->
		<script
			src="https://kit.fontawesome.com/14273d579a.js"
			crossorigin="anonymous"
		></script>
		
		<title>Template 04</title>
	</head>
</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-about">
<!-- Enter here your HTML content. Add a section with an id tag and tag contenteditable="true" if you want to use the inline editor for the content  -->
<section id="mysection1" contenteditable="true">
	<nav class="navbar navbar-expand-lg bg-white shadow-lg">
			<div class="container">
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNav"
					aria-controls="navbarNav"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>

				<a class="navbar-brand" href="index.html"> Brand Name </a>

				<div class="d-lg-none">
					<button
						type="button"
						class="custom-btn btn btn-danger"
						data-bs-toggle="modal"
						data-bs-target="#BookingModal"
					>
						Reservation
					</button>
				</div>

				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav mx-auto">
						<li class="nav-item">
							<a class="nav-link active" href="index.php"
								>Home</a
							>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="about.php">About</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="menu.php">Menu</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="contact.php">Contact</a>
						</li>
					</ul>
				</div>

				<div class="d-none d-lg-block">
					<button
						type="button"
						class="custom-btn btn btn-danger"
						data-bs-toggle="modal"
						data-bs-target="#BookingModal"
					>
						Reservation
					</button>
				</div>
			</div>
		</nav>

		<main>

			<header class="site-header site-about-header">
				<div class="container">
					<div class="row">

						<div class="col-lg-10 col-12 mx-auto">
							<h1 class="text-white">About Us</h1>

							<strong class="text-white">Get to know us more</strong>
						</div>

					</div>
				</div>

				<div class="overlay"></div>
			</header>           

			<section class="about section-padding">
				<div class="container">
					<div class="row">

						<div class="col-12">
							<h2 class="mb-5">Team Members</h2>
						</div>

						<div class="col-lg-4 col-12">
							<div class="team-thumb">
								<img src="image/template04/team/matthew-hamilton-tNCH0sKSZbA-unsplash.jpg" class="img-fluid team-image" alt="">
								 
								<div class="team-info">
									<h4 class="mt-3 mb-0">Sophia</h4>

									<p>CEO &amp; Founder</p>
								</div>
							</div>
						</div>

						<div class="col-lg-4 col-12 my-lg-0 my-4">
							<div class="team-thumb">
								<img src="image/template04/team/nicolas-horn-MTZTGvDsHFY-unsplash.jpg" class="img-fluid team-image" alt="">

								<h4 class="mt-3 mb-0">Benjamin W.</h4>

								<p>Restaurant Manager</p>
							</div>
						</div>

						<div class="col-lg-4 col-12">
							<div class="team-thumb">
								<img src="image/template04/team/rc-cf-FMh5o5m5N9E-unsplash.jpg" class="img-fluid team-image" alt="">
								 
								<h4 class="mt-3 mb-0">Muchen Jack</h4>

								<p>Senior Chef</p>
							</div>
						</div>

					</div>
				</div>
			</section>
			 
			<section class="newsletter section-padding bg-white">
				<div class="container">
					<div class="row">

						<div class="col-lg-6 col-12">
							<img src="image/template04/charles-deluvio-FdDkfYFHqe4-unsplash.jpg" class="img-fluid newsletter-image" alt="">
						</div>

						<div class="col-lg-6 col-12 d-flex align-items-center mt-5 mt-lg-0 mx-auto">
							<div class="subscribe-form-wrap">
								<h4 class="mb-0">Our Newsletter</h4>

								<p>The food news every day</p>

								<form class="custom-form subscribe-form mt-4" role="form">
									<input type="email" name="subscribe-email" id="subscribe-email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Your email address" required="">

									<button type="submit" class="form-control mb-3" id="subscribe">Subscribe</button>

									<small>By signing up, you agree to our Privacy Notice and the data policy</small>
									</div>
								</form>
							</div>
						</div>

					</div>
				</div>
			</section>

		</main>

		  

		<!-- Modal -->
		<div class="modal fade" id="BookingModal" tabindex="-1" aria-labelledby="BookingModal" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered modal-xl">
				<div class="modal-content">
					<div class="modal-header">
						<h3 class="mb-0">Reserve a table</h3>

						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>

					<div class="modal-body d-flex flex-column justify-content-center">
						<div class="booking">
							 
							<form class="booking-form row" role="form" action="#" method="post">
								<div class="col-lg-6 col-12">
									<label for="name" class="form-label">Full Name</label>

									<input type="text" name="name" id="name" class="form-control" placeholder="Your Name" required>
								</div>

								<div class="col-lg-6 col-12">
									<label for="email" class="form-label">Email Address</label>

									<input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="your@email.com" required>
								</div>

								<div class="col-lg-6 col-12">
									<label for="phone" class="form-label">Phone Number</label>

									<input type="telephone" name="phone" id="phone"  class="form-control" >
								</div>

								<div class="col-lg-6 col-12">
									<label for="people" class="form-label">Number of persons</label>

									<input type="text" name="people" id="people" class="form-control" placeholder="12 persons">
								</div>

								<div class="col-lg-6 col-12">
									<label for="date" class="form-label">Date</label>

									<input type="date" name="date" id="date" value="" class="form-control">
								</div>

								<div class="col-lg-6 col-12">
									<label for="time" class="form-label">Time</label>

									<select class="form-select form-control" name="time" id="time">
									  <option value="5" selected>5:00 PM</option>
									  <option value="6">6:00 PM</option>
									  <option value="7">7:00 PM</option>
									  <option value="8">8:00 PM</option>
									  <option value="9">9:00 PM</option>
									</select>
								</div>

								<div class="col-12">
									<label for="message" class="form-label">Special Request</label>

									<textarea class="form-control" rows="4" id="message" name="message" placeholder=""></textarea>
								</div>

								<div class="col-lg-4 col-12 ms-auto">
									<button type="submit" class="form-control">Submit Request</button>
								</div>
							</form>
						</div>
					</div>

					<div class="modal-footer"></div>
					 
				</div>
				 
			</div>
		</div>

</section>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 152);
// END PHP ?>
