name: Bug report
description: Create a report to help us fix something that is broken
labels: ["Bug"]

body:
  - type: markdown
    attributes:
      value: |
        This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.
        
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Please give a short description of the bug
    validations:
      required: true

  - type: input
    id: environment-version
    attributes:
      label: Environment Version
      description: Affected Dolibarr version(s)

  - type: input
    id: environment-os
    attributes:
      label: Environment OS
      description: Server OS type and version
      
  - type: input
    id: environment-webserver
    attributes:
      label: Environment Web server
      description: Webserver type and version
      
  - type: input
    id: environment-php
    attributes:
      label: Environment PHP
      description: PHP version
      
  - type: input
    id: environment-database
    attributes:
      label: Environment Database
      description: Database type and version

  - type: input
    id: environment-urls
    attributes:
      label: Environment URL(s)
      description: Affected URL(s)

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected and actual behavior
      description: Verbose description

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Verbose description
      
  - type: textarea
    id: files
    attributes:
      label: Attached files
      description: Screenshots, screencasts, dolibarr.log, debugging informations
