name    'stahnma-epel'
version '0.1.0'
source 'http://github.com/stahnma/puppet-module-epel'
author 'stahnma'
license 'Apache License, Version 2.0'
summary 'Setup the EPEL package repo'
description 'Setup the EPEL package repo on Centos/RHEL et all'
project_page 'http://github.com/stahnma/puppet-module-epel'
