language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 1.8.7
  - 1.9.3
env:
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION=">= 3.0.0"
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=">= 3.0.0"
notifications:
  email: false
