dolibarr: EvalMath Class Reference
EvalMath Class Reference
Class EvalMath.
Public Member Functions
__construct ()
Constructor.
e ($expr)
Evaluate.
evaluate ($expr)
Evaluate.
vars ()
Function vars.
trigger ($code, $msg, $info=null)
trigger an error, but nicely, if need be
Private Member Functions
funcs ()
Function funcs.
nfx ($expr)
Convert infix to postfix notation.
pfx ($tokens, $vars=array())
Evaluate postfix notation.
Detailed Description
Class EvalMath.
Definition at line 97 of file evalmath.class.php.
Member Function Documentation
e()
EvalMath::e ($expr)
Evaluate.
Parameters
string $expr String
Returns
boolean|number|NULL|mixed Result
Definition at line 135 of file evalmath.class.php.
References evaluate().
evaluate()
EvalMath::evaluate ($expr)
Evaluate.
Parameters
string $expr String
Returns
boolean|number|NULL|mixed Result
Definition at line 146 of file evalmath.class.php.
References trigger().
Referenced by e().
funcs()
EvalMath::funcs () private
Function funcs.
Returns
array Output
Definition at line 218 of file evalmath.class.php.
nfx()
EvalMath::nfx ($expr) private
Convert infix to postfix notation.
Parameters
string $expr Expression
Returns
boolean|array Output
Definition at line 235 of file evalmath.class.php.
pfx()
EvalMath::pfx ($tokens, $vars = array()) private
Evaluate postfix notation.
Parameters
array $tokens Expression
array $vars Array
Returns
string Output
Definition at line 381 of file evalmath.class.php.
trigger()
EvalMath::trigger ($code, $msg, $info = null)
trigger an error, but nicely, if need be
Parameters
string $code Code
string $msg Msg
string | null $info String
Returns
boolean False
Definition at line 468 of file evalmath.class.php.
Referenced by evaluate().
vars()
EvalMath::vars ()
Function vars.
Returns
array Output
Definition at line 205 of file evalmath.class.php.
The documentation for this class was generated from the following file:
htdocs/core/class/evalmath.class.php