dolibarr: DoliDBMysqli Class Reference
DoliDBMysqli Class Reference
Class to manage Dolibarr database access for a MySQL database using the MySQLi extension.
Public Member Functions
__construct ($type, $host, $user, $pass, $name='', $port=0)
Constructor.
hintindex ($nameofindex)
Return SQL string to force an index.
select_db ($database)
Select a database.
connect ($host, $login, $passwd, $name, $port=0)
Connect to server.
getVersion ()
Return version of database server.
getDriverInfo ()
Return version of database client driver.
close ()
Close database connexion.
query ($query, $usesavepoint=0, $type='auto', $result_mode=0)
Execute a SQL request and return the resultset.
fetch_object ($resultset)
Returns the current line (as an object) for the resultset cursor.
fetch_array ($resultset)
Return datas as an array.
fetch_row ($resultset)
Return datas as an array.
num_rows ($resultset)
Return number of lines for result of a SELECT.
affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
free ($resultset=null)
Libere le dernier resultset utilise sur cette connexion.
escape ($stringtoencode)
Escape a string to insert data.
escapeforlike ($stringtoencode)
Escape a string to insert data into a like.
errno ()
Return generic error code of last operation.
error ()
Return description of last error.
last_insert_id ($tab, $fieldid='rowid')
Get last ID after an insert INSERT.
encrypt ($fieldorvalue, $withQuotes=1)
Encrypt sensitive data in database Warning: This function includes the escape and add the SQL simple quotes on strings.
decrypt ($value)
Decrypt sensitive data in database.
DDLGetConnectId ()
Return connexion ID.
DDLCreateDb ($database, $charset='', $collation='', $owner='')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
DDLListTables ($database, $table='')
List tables into a database.
DDLInfoTable ($table)
List information of columns into a table.
DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys=null, $fulltext_keys=null, $keys=null)
Create a table into database.
DDLDropTable ($table)
Drop a table into database.
DDLDescTable ($table, $field="")
Return a pointer of line with description of a table or field.
DDLAddField ($table, $field_name, $field_desc, $field_position="")
Create a new field into table.
DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
DDLDropField ($table, $field_name)
Drop a field from table.
DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
getDefaultCharacterSetDatabase ()
Return charset used to store data in current database Note: if we are connected to databasename, it is same result than using SELECT default_character_set_name FROM information_schema.SCHEMATA WHERE schema_name = "databasename";)
getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
getDefaultCollationDatabase ()
Return collation used in current database.
getListOfCollation ()
Return list of available collation that can be used for database.
getPathOfDump ()
Return full path of dump program.
getPathOfRestore ()
Return full path of restore program.
getServerParametersValues ($filter='')
Return value of server parameters.
getServerStatusValues ($filter='')
Return value of server status (current indicators on memory, cache...)
Public Member Functions inherited from DoliDB
prefix ()
Return the DB prefix.
ifsql ($test, $resok, $resko)
Format a SQL IF.
regexpsql ($subject, $pattern, $sqlstring=false)
Format a SQL REGEXP.
idate ($param, $gm='tzserver')
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
lasterrno ()
Return last error code.
sanitize ($stringtosanitize, $allowsimplequote=0, $allowsequals=0)
Sanitize a string for SQL forging.
begin ($textinlog='')
Start transaction.
commit ($log='')
Validate a database transaction.
rollback ($log='')
Cancel a transaction and go back to initial data values.
plimit ($limit=0, $offset=0)
Define limits and offset of request.
getVersionArray ()
Return version of database server into an array.
lastquery ()
Return last request executed with query()
order ($sortfield=null, $sortorder=null)
Define sort criteria of request.
lasterror ()
Return last error label.
jdate ($string, $gm='tzserver')
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with server TZ = +1 and $gm='tzserver' 19700101020000 -> 7200 whaterver is server TZ if $gm='gmt'.
lastqueryerror ()
Return last query in error.
getRow ($sql)
Return first result from query as object Note : This method executes a given SQL query and retrieves the first row of results as an object.
getRows ($sql)
Return all results from query as an array of objects Note : This method executes a given SQL query and retrieves all row of results as an array of objects.
Public Member Functions inherited from Database
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
sanitize ($stringtosanitize)
Sanitize a string for SQL forging.
Static Public Member Functions
static convertSQLFromMysql ($line, $type='ddl')
Convert a SQL request in Mysql syntax to native syntax.
Public Attributes
$type = 'mysqli'
Database type.
const LABEL = 'MySQL or MariaDB'
Database label.
const VERSIONMIN = '5.0.3'
Version min database.
Detailed Description
Class to manage Dolibarr database access for a MySQL database using the MySQLi extension.
Definition at line 33 of file mysqli.class.php.
Constructor & Destructor Documentation
__construct()
DoliDBMysqli::__construct ($type, $host, $user, $pass, $name = '', $port = 0)
Constructor.
This create an opened connexion to a database server and eventually to a database
Parameters
string $type Type of database (mysql, pgsql...)
string $host Address of database server
string $user Nom de l'utilisateur autorise
string $pass Mot de passe
string $name Nom de la database
int $port Port of database server
Definition at line 57 of file mysqli.class.php.
Member Function Documentation
affected_rows()
DoliDBMysqli::affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
Parameters
mysqli_result $resultset Curseur de la requete voulue
Returns
int Number of lines
See also
num_rows()
Implements Database.
Definition at line 435 of file mysqli.class.php.
References db.
close()
DoliDBMysqli::close ()
Close database connexion.
Returns
bool True if disconnect successfull, false otherwise
See also
connect()
Implements Database.
Definition at line 273 of file mysqli.class.php.
References db, and dol_syslog().
connect()
DoliDBMysqli::connect ($host, $login, $passwd, $name, $port = 0)
Connect to server.
Parameters
string $host Database server host
string $login Login
string $passwd Password
string $name Name of database (not used for mysql, used for pgsql)
integer $port Port of database server
Returns
mysqli|null Database access object
See also
close()
Implements Database.
Definition at line 228 of file mysqli.class.php.
convertSQLFromMysql()
static DoliDBMysqli::convertSQLFromMysql ($line, $type = 'ddl') static
Convert a SQL request in Mysql syntax to native syntax.
Parameters
string $line SQL request line to convert
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
Returns
string SQL request line converted
Implements Database.
Definition at line 190 of file mysqli.class.php.
DDLAddField()
DoliDBMysqli::DDLAddField ($table, $field_name, $field_desc, $field_position = "")
Create a new field into table.
Parameters
string $table Name of table
string $field_name Name of field to add
string $field_desc Tableau associatif de description du champ a inserer[nom du parametre][valeur du parametre]
string $field_position Optionnel ex.: "after champtruc"
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 879 of file mysqli.class.php.
DDLCreateDb()
DoliDBMysqli::DDLCreateDb ($database, $charset = '', $collation = '', $owner = '')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
Parameters
string $database Database name to create
string $charset Charset used to store data
string $collation Charset used to sort data
string $owner Username of database owner
Returns
bool|mysqli_result resource defined if OK, null if KO
Implements Database.
Definition at line 660 of file mysqli.class.php.
DDLCreateTable()
DoliDBMysqli::DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys = null, $fulltext_keys = null, $keys = null)
Create a table into database.
Parameters
string $table Name of table
array $fields Tableau associatif [nom champ][tableau des descriptions]
string $primary_key Nom du champ qui sera la clef primaire
string $type Type de la table
array $unique_keys Tableau associatifs Nom de champs qui seront clef unique => valeur
array $fulltext_keys Tableau des Nom de champs qui seront indexes en fulltext
array $keys Tableau des champs cles noms => valeur
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 756 of file mysqli.class.php.
DDLCreateUser()
DoliDBMysqli::DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
Parameters
string $dolibarr_main_db_host Ip server or ''
string $dolibarr_main_db_user Nom user a creer
string $dolibarr_main_db_pass Mot de passe user a creer
string $dolibarr_main_db_name Database name where user must be granted
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 994 of file mysqli.class.php.
DDLDescTable()
DoliDBMysqli::DDLDescTable ($table, $field = "")
Return a pointer of line with description of a table or field.
Parameters
string $table Name of table
string $field Optionnel : Name of field if we want description of field
Returns
bool|mysqli_result Resultset x (x->Field, x->Type, ...)
Implements Database.
Definition at line 859 of file mysqli.class.php.
DDLDropField()
DoliDBMysqli::DDLDropField ($table, $field_name)
Drop a field from table.
Parameters
string $table Name of table
string $field_name Name of field to drop
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 970 of file mysqli.class.php.
DDLDropTable()
DoliDBMysqli::DDLDropTable ($table)
Drop a table into database.
Parameters
string $table Name of table
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 837 of file mysqli.class.php.
DDLGetConnectId()
DoliDBMysqli::DDLGetConnectId ()
Return connexion ID.
Returns
string Id connexion
Implements Database.
Definition at line 636 of file mysqli.class.php.
DDLInfoTable()
DoliDBMysqli::DDLInfoTable ($table)
List information of columns into a table.
Parameters
string $table Name of table
Returns
array Tableau des informations des champs de la table
Implements Database.
Definition at line 724 of file mysqli.class.php.
DDLListTables()
DoliDBMysqli::DDLListTables ($database, $table = '')
List tables into a database.
Parameters
string $database Name of database
string $table Nmae of table filter ('xxx')
Returns
array List of tables in an array
Implements Database.
Definition at line 693 of file mysqli.class.php.
DDLUpdateField()
DoliDBMysqli::DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
Parameters
string $table Name of table
string $field_name Name of field to modify
string $field_desc Array with description of field format
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 925 of file mysqli.class.php.
decrypt()
DoliDBMysqli::decrypt ($value)
Decrypt sensitive data in database.
Parameters
string $value Value to decrypt
Returns
string Decrypted value if used
Implements Database.
Definition at line 606 of file mysqli.class.php.
encrypt()
DoliDBMysqli::encrypt ($fieldorvalue, $withQuotes = 1)
Encrypt sensitive data in database Warning: This function includes the escape and add the SQL simple quotes on strings.
Parameters
string $fieldorvalue Field name or value to encrypt
int $withQuotes Return string including the SQL simple quotes. This param must always be 1 (Value 0 is bugged and deprecated).
Returns
string XXX(field) or XXX('value') or field or 'value'
Implements Database.
Definition at line 577 of file mysqli.class.php.
errno()
DoliDBMysqli::errno ()
Return generic error code of last operation.
Returns
string Error code (Exemples: DB_ERROR_TABLE_ALREADY_EXISTS, DB_ERROR_RECORD_ALREADY_EXISTS...)
Implements Database.
Definition at line 493 of file mysqli.class.php.
error()
DoliDBMysqli::error ()
Return description of last error.
Returns
string Error text
Implements Database.
Definition at line 545 of file mysqli.class.php.
References db.
escape()
DoliDBMysqli::escape ($stringtoencode)
Escape a string to insert data.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implements Database.
Definition at line 472 of file mysqli.class.php.
References db.
escapeforlike()
DoliDBMysqli::escapeforlike ($stringtoencode)
Escape a string to insert data into a like.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implements Database.
Definition at line 483 of file mysqli.class.php.
fetch_array()
DoliDBMysqli::fetch_array ($resultset)
Return datas as an array.
Parameters
mysqli_result $resultset Resultset of request
Returns
array|null Array or null if KO or end of cursor
Implements Database.
Definition at line 377 of file mysqli.class.php.
fetch_object()
DoliDBMysqli::fetch_object ($resultset)
Returns the current line (as an object) for the resultset cursor.
Parameters
mysqli_result $resultset Curseur de la requete voulue
Returns
object|null Object result line or null if KO or end of cursor
Implements Database.
Definition at line 359 of file mysqli.class.php.
fetch_row()
DoliDBMysqli::fetch_row ($resultset)
Return datas as an array.
Parameters
mysqli_result $resultset Resultset of request
Returns
array|null|int Array or null if KO or end of cursor or 0 if resultset is bool
Implements Database.
Definition at line 394 of file mysqli.class.php.
free()
DoliDBMysqli::free ($resultset = null)
Libere le dernier resultset utilise sur cette connexion.
Parameters
mysqli_result $resultset Curseur de la requete voulue
Returns
void
Implements Database.
Definition at line 454 of file mysqli.class.php.
getDefaultCharacterSetDatabase()
DoliDBMysqli::getDefaultCharacterSetDatabase ()
Return charset used to store data in current database Note: if we are connected to databasename, it is same result than using SELECT default_character_set_name FROM information_schema.SCHEMATA WHERE schema_name = "databasename";)
Returns
string Charset
See also
getDefaultCollationDatabase()
Implements Database.
Definition at line 1039 of file mysqli.class.php.
getDefaultCollationDatabase()
DoliDBMysqli::getDefaultCollationDatabase ()
Return collation used in current database.
Returns
string Collation value
See also
getDefaultCharacterSetDatabase()
Implements Database.
Definition at line 1082 of file mysqli.class.php.
References $resql, and query().
getDriverInfo()
DoliDBMysqli::getDriverInfo ()
Return version of database client driver.
Returns
string Version string
Implements Database.
Definition at line 261 of file mysqli.class.php.
References db.
getListOfCharacterSet()
DoliDBMysqli::getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
Returns
array|null List of Charset
Implements Database.
Definition at line 1057 of file mysqli.class.php.
References $resql, and query().
getListOfCollation()
DoliDBMysqli::getListOfCollation ()
Return list of available collation that can be used for database.
Returns
array|null Liste of Collation
Implements Database.
Definition at line 1100 of file mysqli.class.php.
References $resql, and query().
getPathOfDump()
DoliDBMysqli::getPathOfDump ()
Return full path of dump program.
Returns
string Full path of dump program
Implements Database.
Definition at line 1123 of file mysqli.class.php.
References $resql, and query().
getPathOfRestore()
DoliDBMysqli::getPathOfRestore ()
Return full path of restore program.
Returns
string Full path of restore program
Implements Database.
Definition at line 1141 of file mysqli.class.php.
References $resql, and query().
getServerParametersValues()
DoliDBMysqli::getServerParametersValues ($filter = '')
Return value of server parameters.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implements Database.
Definition at line 1160 of file mysqli.class.php.
getServerStatusValues()
DoliDBMysqli::getServerStatusValues ($filter = '')
Return value of server status (current indicators on memory, cache...)
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implements Database.
Definition at line 1184 of file mysqli.class.php.
getVersion()
DoliDBMysqli::getVersion ()
Return version of database server.
Returns
string Version string
Implements Database.
Definition at line 251 of file mysqli.class.php.
References db.
hintindex()
DoliDBMysqli::hintindex ($nameofindex)
Return SQL string to force an index.
Parameters
string $nameofindex Name of index
Returns
string SQL string
Reimplemented from DoliDB.
Definition at line 177 of file mysqli.class.php.
last_insert_id()
DoliDBMysqli::last_insert_id ($tab, $fieldid = 'rowid')
Get last ID after an insert INSERT.
Parameters
string $tab Table name concerned by insert. Ne sert pas sous MySql mais requis pour compatibilite avec Postgresql
string $fieldid Field name
Returns
int|string Id of row
Implements Database.
Definition at line 563 of file mysqli.class.php.
num_rows()
DoliDBMysqli::num_rows ($resultset)
Return number of lines for result of a SELECT.
Parameters
mysqli_result $resultset Resulset of requests
Returns
int Nb of lines
See also
affected_rows()
Implements Database.
Definition at line 417 of file mysqli.class.php.
query()
bool mysqli_result Resultset of last DoliDBMysqli::query ($query, $usesavepoint = 0, $type = 'auto', $result_mode = 0)
Execute a SQL request and return the resultset.
Parameters
string $query SQL query string
int $usesavepoint 0=Default mode, 1=Run a savepoint before and a rollback to savepoint if error (this allow to have some request with errors inside global transactions). Note that with Mysql, this parameter is not used as Myssql can already commit a transaction even if one request is in error, without using savepoints.
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
int $result_mode Result mode (Using 1=MYSQLI_USE_RESULT instead of 0=MYSQLI_STORE_RESULT will not buffer the result and save memory)
Returns
bool|mysqli_result Resultset of answer
Implements Database.
Definition at line 297 of file mysqli.class.php.
Referenced by getDefaultCollationDatabase(), getListOfCharacterSet(), getListOfCollation(), getPathOfDump(), and getPathOfRestore().
select_db()
DoliDBMysqli::select_db ($database)
Select a database.
Parameters
string $database Name of database
Returns
boolean true if OK, false if KO
Implements Database.
Definition at line 203 of file mysqli.class.php.
References dol_syslog().
The documentation for this class was generated from the following file:
htdocs/core/db/mysqli.class.php