<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>Our menus</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="Our menus" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 17.0.0-beta (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="251" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script async src="/javascript.js.php"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-menu">
<!-- Enter here your HTML content. Add a section with an id tag and tag contenteditable="true" if you want to use the inline editor for the content  -->

<?php includeContainer('header'); ?>


<section id="mysection1" contenteditable="true">
        <main>
            <header class="site-header site-menu-header">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-12 mx-auto">
                            <h1 class="text-white">Our Menus</h1>

                            <strong class="text-white"
                                >Perfect for all Breakfast, Lunch and
                                Dinner</strong
                            >
                        </div>
                    </div>
                </div>

                <div class="overlay"></div>
            </header>

            <section class="menu section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="mb-lg-5 mb-4">Breakfast Menu</h2>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/breakfast/brett-jordan-8xt8-HIFqc8-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Fresh Start</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>24.50</span
                                    >
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="/image/aaab/breakfast/lucas-swennen-1W_MyJSRLuQ-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Baked Creamy</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>16.50</span
                                    >
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/breakfast/louis-hansel-dphM2U1xq0U-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Burger Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>24.50</span
                                    >

                                    <del class="ms-4"
                                        ><small>$</small>36.50</del
                                    >
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="menu section-padding bg-white">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="mb-lg-5 mb-4">Lunch Menu</h2>
                        </div>

                        <div class="col-lg-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/lunch/louis-hansel-cH5IPjaAYyo-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Super Steak Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>32.75</span
                                    >

                                    <del class="ms-4"><small>$</small>55</del>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/lunch/louis-hansel-rheOvfxOlOA-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Bread &amp; Steak Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>42.50</span
                                    >
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="menu section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="mb-lg-5 mb-4">Dinner Menu</h2>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/dinner/farhad-ibrahimzade-ZipYER3NLhY-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Seafood Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>65.50</span
                                    >
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/dinner/keriliwi-c3mFafsFz2w-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Premium Steak</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>74.25</span
                                    >
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/aaab/dinner/farhad-ibrahimzade-isHUj3N0194-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Salmon Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>60</span
                                    >
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>

</section>


<?php includeContainer('footer'); ?>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 251);
// END PHP ?>
