<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>Our menus</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="Our menus" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 17.0.0-alpha (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="172" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script async src="/javascript.js.php"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-menu">
<!-- Enter here your HTML content. Add a section with an id tag and tag contenteditable="true" if you want to use the inline editor for the content  -->
<section id="mysection1" contenteditable="true">
       <nav class="navbar navbar-expand-lg bg-white shadow-lg">
            <div class="container">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>

                <a class="navbar-brand" href="index.html"><?php echo $mysoc->name; ?></a>

                <div class="d-lg-none">
                    <a href="contact.php#reservation"
                        type="button"
                        class="custom-btn btn btn-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#BookingModal"
                    >
                        Reservation
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="index.php">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="about.php">About</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active" href="menu.php">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="contact.php">Contact</a>
                        </li>
                    </ul>
                </div>

                <div class="d-none d-lg-block">
                    <a href="contact.php#reservation"
                        type="button"
                        class="custom-btn btn btn-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#BookingModal"
                    >
                        Reservation
                    </a>
                </div>
            </div>
        </nav>

        <main>
            <header class="site-header site-menu-header">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-12 mx-auto">
                            <h1 class="text-white">Our Menus</h1>

                            <strong class="text-white"
                                >Perfect for all Breakfast, Lunch and
                                Dinner</strong
                            >
                        </div>
                    </div>
                </div>

                <div class="overlay"></div>
            </header>

            <section class="menu section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="mb-lg-5 mb-4">Breakfast Menu</h2>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/breakfast/brett-jordan-8xt8-HIFqc8-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Fresh Start</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>24.50</span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            4.4/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            128 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="/image/mypersonalsite/breakfast/lucas-swennen-1W_MyJSRLuQ-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Baked Creamy</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>16.50</span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            3/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            64 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/breakfast/louis-hansel-dphM2U1xq0U-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Burger Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>24.50</span
                                    >

                                    <del class="ms-4"
                                        ><small>$</small>36.50</del
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            3/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            32 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="menu section-padding bg-white">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="mb-lg-5 mb-4">Lunch Menu</h2>
                        </div>

                        <div class="col-lg-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/lunch/louis-hansel-cH5IPjaAYyo-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Super Steak Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>32.75</span
                                    >

                                    <del class="ms-4"><small>$</small>55</del>

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            4.2/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            66 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/lunch/louis-hansel-rheOvfxOlOA-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Bread &amp; Steak Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>42.50</span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            3/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            84 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="menu section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="mb-lg-5 mb-4">Dinner Menu</h2>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/dinner/farhad-ibrahimzade-ZipYER3NLhY-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Seafood Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>65.50</span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            4.4/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            102 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/dinner/keriliwi-c3mFafsFz2w-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Premium Steak</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>74.25</span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            3/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            56 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <img
                                    src="image/mypersonalsite/dinner/farhad-ibrahimzade-isHUj3N0194-unsplash.jpg"
                                    class="img-fluid menu-image"
                                    alt=""
                                />

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Salmon Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        ><small>$</small>60</span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <h6 class="reviews-text mb-0 me-3">
                                            3/5
                                        </h6>

                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>

                                        <p class="reviews-text mb-0 ms-4">
                                            76 Reviews
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>

         <footer class="site-footer section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h4 class="text-white mb-4 me-5"><?php echo $mysoc->name; ?></h4>
                    </div>

                    <div class="col-lg-4 col-md-7 col-xs-12 tooplate-mt30">
                        <h6 class="text-white mb-lg-4 mb-3">Location</h6>

                        <p><?php echo $mysoc->getFullAddress(); ?></p>

                        <a
                            href="https://goo.gl/maps/CJ8FfebWZHLQBA2r5"
                            class="custom-btn btn btn-dark mt-2"
                            >Directions</a
                        >
                    </div>

                    <div class="col-lg-4 col-md-5 col-xs-12 tooplate-mt30">
                        <h6 class="text-white mb-lg-4 mb-3">Opening Hours</h6>

         
                        <?php $days = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"];
                        foreach ($days as $day){
                            echo "<p> $day : " .getDolGlobalString("MAIN_INFO_OPENINGHOURS_$day")  ."</p>";    
                        }
                        ?>

                        <p>
                            Tel:
                            <a href="tel: 010-02-0340" class="tel-link"
                                ><?php echo $mysoc->phone ?></a
                            >
                        </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-xs-12 tooplate-mt30">
                        <h6 class="text-white mb-lg-4 mb-3">Social</h6>

                        <ul class="social-icon">
                             <?php foreach($mysoc->socialnetworks as $key => $value) {
                                print '<li> <a class="btn btn-perso2 btn-floating m-1" href="'. (preg_match('/^http/', $value) ? $value : 'https://www.'.$key.'.com/'.$value).'"><span class="fab fa-'.$key.'"></i></a> </li>';
                             } ?>

                       
                        </ul>

                        <p class="copyright-text tooplate-mt60">
                            Copyright © <?php echo $mysoc->name; ?>
                        </p>
                    </div>
                </div>
                <!-- row ending -->
            </div>
            <!-- container ending -->
        </footer>

</section>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 172);
// END PHP ?>
