name 'puppetlabs-postgresql'
version '3.3.3'
source 'git://github.com/puppetlabs/puppet-postgresql.git'
author 'Inkling/Puppet Labs'
description 'PostgreSQL defined resource types'
summary 'PostgreSQL defined resource types'
license 'ASL 2.0'
project_page 'https://github.com/puppetlabs/puppet-postgresql'

dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/firewall', '>= 0.0.4'
dependency 'puppetlabs/apt', '>=1.1.0 <2.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0 <2.0.0'
