language: ruby
rvm:
  - "1.8.7"
# life with later versions of ruby gets interesting with 2.6..so lets
# ignore them for now
#  - "1.9.2"
#  - "1.9.3"
#  - ruby-head ..that doesnt work. would be nice to do "current"

env:
#find versions here https://rubygems.org/gems/puppet/versions
# spec_helper pretty much fails on these earlier versions.
#  - PUPPET_VERSION=0.24.5
#  - PUPPET_VERSION=0.25.5 
  - PUPPET_VERSION=2.6.18
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.1.1
 

before_script: 
 - cd beanstalkd
 - bundle install
 - bundle show

script: 
 - bundle exec rake
