#!/bin/bash
# File Managed by Puppet
PATH=$PATH:/usr/local/bin

if [ ! $2 ] ; then
    echo "Provide the hostname and the project you want to deploy:"
    echo "superdeploy web01.example42.com myapp"
    exit 1
fi

filtered=$(echo $* | sed "s/[^a-Z0-9= _.\-]//Ig")

randfile="$(mktemp)"

trap "rm -f $randfile" SIGINT SIGTERM EXIT

myarg=$(echo $filtered | sed -e "s/ / -F /g")

mc-puppi deploy -I $1 $2 | tee $randfile
grep FAILED $randfile && exit 1
exit 0

