<?php
/* Copyright (C) 2026 ATM Consulting <support@atm-consulting.fr>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * \file    htdocs/modulebuilder/class/AccessRuleExpression.class.php
 * \ingroup modulebuilder
 * \brief   Node of the access rule tree of the pages generated by ModuleBuilder.
 */

/**
 * Node of the access rule tree of the pages generated by ModuleBuilder.
 *
 * A tree is made of AndRule and OrRule nodes whose leaves are whitelisted PredicateRule: there is no
 * way to inject a free PHP expression in the generated pages.
 */
interface AccessRuleExpression
{
	/**
	 * Render the node as a PHP boolean expression, composite nodes being wrapped in parentheses.
	 *
	 * @return string
	 */
	public function toPhp(): string;

	/**
	 * Return the node as an array, ready to be JSON encoded.
	 *
	 * @return array<string,mixed>
	 */
	public function toArray(): array;
}
