<?php
/* Copyright (C) 2026 ATM Consulting <support@atm-consulting.fr>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * \file    htdocs/modulebuilder/class/AccessPolicyConfig.class.php
 * \ingroup modulebuilder
 * \brief   Access policy of the pages generated by ModuleBuilder: a rule tree and a deny message.
 */

require_once DOL_DOCUMENT_ROOT.'/modulebuilder/class/AccessRuleExpression.class.php';
require_once DOL_DOCUMENT_ROOT.'/modulebuilder/class/PredicateRule.class.php';
require_once DOL_DOCUMENT_ROOT.'/modulebuilder/class/AndRule.class.php';
require_once DOL_DOCUMENT_ROOT.'/modulebuilder/class/OrRule.class.php';

/**
 * Immutable access policy of the pages generated by ModuleBuilder: a rule tree and a deny message.
 *
 * A policy is always valid once built: every way in (constructor, fromJson(), fromAlternatives())
 * rejects an unknown node, an unknown predicate, a tree out of bounds or a message that is not a
 * translation key.
 */
final class AccessPolicyConfig
{
	const MAX_DEPTH = 4;
	const MAX_NODES = 32;
	const MAX_ALTERNATIVES = 3;
	const MAX_MESSAGE_LENGTH = 128;

	/** @var AccessRuleExpression */
	private $expression;

	/** @var string Translation key passed to accessforbidden(), empty for the default message */
	private $message;

	/**
	 * @param	AccessRuleExpression	$expression	Root of the rule tree
	 * @param	string					$message	Translation key shown on deny, empty for the default message
	 * @throws	\InvalidArgumentException	When the tree is out of bounds or the message is not a translation key
	 */
	public function __construct(AccessRuleExpression $expression, string $message = '')
	{
		if (strlen($message) > self::MAX_MESSAGE_LENGTH || !preg_match('/^[A-Za-z0-9_]*$/D', $message)) {
			throw new \InvalidArgumentException('The access policy message must be a translation key');
		}
		$nodecount = 0;
		self::checkBounds($expression, 1, $nodecount);

		$this->expression = $expression;
		$this->message = $message;
	}

	/**
	 * Build a policy from the editor of ModuleBuilder: the predicates of an alternative are combined
	 * with AND, the alternatives with OR. Empty alternatives are ignored.
	 *
	 * @param	array<int,string[]>	$alternatives	List of alternatives, each one a list of predicate names
	 * @param	string				$message		Translation key shown on deny
	 * @return	AccessPolicyConfig|null				Null when no predicate is selected at all
	 * @throws	\InvalidArgumentException			When there are too many alternatives or a predicate is unknown
	 */
	public static function fromAlternatives(array $alternatives, string $message = ''): ?self
	{
		if (count($alternatives) > self::MAX_ALTERNATIVES) {
			throw new \InvalidArgumentException('An access policy accepts at most '.self::MAX_ALTERNATIVES.' alternatives');
		}

		$rules = array();
		foreach ($alternatives as $alternative) {
			if (!is_array($alternative)) {
				throw new \InvalidArgumentException('An access policy alternative must be a list of predicates');
			}
			if (empty($alternative)) {
				continue;
			}
			$predicates = array();
			foreach (array_values(array_unique($alternative, SORT_REGULAR)) as $name) {
				if (!is_string($name)) {
					throw new \InvalidArgumentException('An access policy predicate name must be a string');
				}
				$predicates[] = new PredicateRule($name);
			}
			$rules[] = (count($predicates) == 1) ? $predicates[0] : new AndRule($predicates);
		}

		if (empty($rules)) {
			return null;
		}
		return new self((count($rules) == 1) ? $rules[0] : new OrRule($rules), $message);
	}

	/**
	 * Load a serialized policy, as produced by toJson().
	 *
	 * @param	string	$json	Serialized policy
	 * @return	AccessPolicyConfig
	 * @throws	\InvalidArgumentException	When the content is not a valid policy
	 */
	public static function fromJson(string $json): self
	{
		$data = json_decode($json, true);
		if (!is_array($data) || json_last_error() !== JSON_ERROR_NONE) {
			throw new \InvalidArgumentException('The serialized access policy is not a JSON object');
		}
		if (!isset($data['expression'])) {
			throw new \InvalidArgumentException('The serialized access policy has no expression');
		}
		$message = isset($data['message']) ? $data['message'] : '';
		if (!is_string($message)) {
			throw new \InvalidArgumentException('The access policy message must be a translation key');
		}

		return new self(self::buildNode($data['expression'], 1), $message);
	}

	/**
	 * Serialize the policy. The order of the rules is kept, so the output is deterministic.
	 *
	 * @return string
	 */
	public function toJson(): string
	{
		return (string) json_encode(array('expression' => $this->expression->toArray(), 'message' => $this->message), JSON_UNESCAPED_SLASHES);
	}

	/**
	 * @return AccessRuleExpression	Root of the rule tree
	 */
	public function getExpression(): AccessRuleExpression
	{
		return $this->expression;
	}

	/**
	 * @return string	Translation key shown on deny, empty for the default message
	 */
	public function getMessage(): string
	{
		return $this->message;
	}

	/**
	 * Build a node of the tree from its serialized form.
	 *
	 * @param	mixed	$data	Serialized node
	 * @param	int		$depth	Depth of the node, 1 for the root
	 * @return	AccessRuleExpression
	 * @throws	\InvalidArgumentException	When the node is invalid or too deep
	 */
	private static function buildNode($data, int $depth): AccessRuleExpression
	{
		if ($depth > self::MAX_DEPTH) {
			throw new \InvalidArgumentException('The access policy is deeper than '.self::MAX_DEPTH.' levels');
		}
		if (!is_array($data) || !isset($data['type']) || !is_string($data['type'])) {
			throw new \InvalidArgumentException('An access policy node must have a type');
		}

		if ($data['type'] === PredicateRule::TYPE) {
			if (!isset($data['name']) || !is_string($data['name'])) {
				throw new \InvalidArgumentException('An access policy predicate must have a name');
			}
			return new PredicateRule($data['name']);
		}

		if ($data['type'] !== AndRule::TYPE && $data['type'] !== OrRule::TYPE) {
			throw new \InvalidArgumentException('Unknown access policy node type: '.$data['type']);
		}
		if (!isset($data['rules']) || !is_array($data['rules'])) {
			throw new \InvalidArgumentException('An access policy '.$data['type'].' node must have a list of rules');
		}
		$rules = array();
		foreach ($data['rules'] as $child) {
			$rules[] = self::buildNode($child, $depth + 1);
		}
		return ($data['type'] === AndRule::TYPE) ? new AndRule($rules) : new OrRule($rules);
	}

	/**
	 * Check that a tree stays within MAX_DEPTH and MAX_NODES.
	 *
	 * @param	AccessRuleExpression	$node		Node to check
	 * @param	int						$depth		Depth of the node, 1 for the root
	 * @param	int						$nodecount	Number of nodes met so far, updated
	 * @return	void
	 * @throws	\InvalidArgumentException	When the tree is out of bounds
	 */
	private static function checkBounds(AccessRuleExpression $node, int $depth, int &$nodecount)
	{
		$nodecount++;
		if ($depth > self::MAX_DEPTH) {
			throw new \InvalidArgumentException('The access policy is deeper than '.self::MAX_DEPTH.' levels');
		}
		if ($nodecount > self::MAX_NODES) {
			throw new \InvalidArgumentException('The access policy has more than '.self::MAX_NODES.' nodes');
		}
		if ($node instanceof AndRule || $node instanceof OrRule) {
			foreach ($node->getRules() as $child) {
				self::checkBounds($child, $depth + 1, $nodecount);
			}
		}
	}
}
