language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini; true

install:
  - composer install

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/sabre-cs-fixer fix . --dry-run --diff

