-- Generated by dolibarr_mysql2pgsql
-- (c) 2004, PostgreSQL Inc.
-- (c) 2005, Laurent Destailleur.

-- ===================================================================
-- Copyright (C) 2003 Rodolphe Quiedeville <rodolphe@quiedeville.org>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
--
-- Id: llx_livraisondet.sql,v 1.3 2007/12/02 21:37:40 eldy Exp 
-- ===================================================================

create table llx_livraisondet
(
  rowid SERIAL PRIMARY KEY,
  "fk_livraison"      integer,
  "fk_commande_ligne" integer NOT NULL,
  "qty"               real              -- quantité
);

CREATE INDEX idx_llx_livraisondet_fk_livraison ON llx_livraisondet (fk_livraison);
CREATE INDEX idx_llx_livraisondet_fk_commande_ligne ON llx_livraisondet (fk_commande_ligne);
