-- Generated by dolibarr_mysql2pgsql
-- (c) 2004, PostgreSQL Inc.
-- (c) 2005, Laurent Destailleur.

-- ===================================================================
-- Copyright (C) 2002-2003 Rodolphe Quiedeville <rodolphe@quiedeville.org>
-- Copyright (C) 2002-2003 Jean-Louis Bergamo <jlb@j1b.org>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
--
-- Id: llx_adherent_type.sql,v 1.10 2007/12/02 21:51:12 eldy Exp 
-- ===================================================================
--
-- statut
-- 0 : actif
-- 1 : inactif

create table llx_adherent_type
(
  rowid SERIAL PRIMARY KEY,
  "tms"              timestamp,
  "statut"           smallint NOT NULL DEFAULT 0,
  "libelle"          varchar(50) NOT NULL,
  "cotisation" varchar(3) CHECK (cotisation IN ('yes','no'))  NOT NULL DEFAULT 'yes',
  "vote" varchar(3) CHECK (vote IN ('yes','no'))  NOT NULL DEFAULT 'yes',
  "note"             text,
  "mail_valid"       text -- mail envoye a la validation
);
