-- Generated by dolibarr_mysql2pgsql
-- (c) 2004, PostgreSQL Inc.
-- (c) 2005, Laurent Destailleur.

-- ============================================================================
-- Copyright (C) 2006 Rodolphe Quiedeville <rodolphe@quiedeville.org>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
--
-- Id: llx_entrepot_valorisation.sql,v 1.3 2007/12/02 21:58:49 eldy Exp 
-- ============================================================================

create table llx_entrepot_valorisation
(
  rowid SERIAL PRIMARY KEY,
  "tms"             timestamp,      -- date technique mise à jour automatiquement
  "date_calcul"     date,           -- date auquel a ete calcule la valeur
  "fk_entrepot"     integer NOT NULL ,
  "valo_pmp"        float(12,4)    -- valoristaion du stock en PMP
);

CREATE INDEX idx_llx_entrepot_valorisation_fk_entrepot ON llx_entrepot_valorisation (fk_entrepot);

