-- Generated by dolibarr_mysql2pgsql
-- (c) 2004, PostgreSQL Inc.
-- (c) 2005, Laurent Destailleur.

-- ============================================================================
-- Copyright (C) 2002-2003 Rodolphe Quiedeville <rodolphe@quiedeville.org>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
--
-- Id: llx_cond_reglement.sql,v 1.8 2007/12/02 22:03:23 eldy Exp 
-- ============================================================================

create table llx_cond_reglement
(
  rowid           integer PRIMARY KEY,
  "code"            varchar(16),
  "sortorder"       smallint,
  "active"          smallint DEFAULT 1,
  "libelle"         varchar(255),
  "libelle_facture" text,
  "fdm"             smallint,    -- reglement fin de mois
  "nbjour"          smallint,
  "decalage"		  smallint
);
