-- Generated by dolibarr_mysql2pgsql
-- (c) 2004, PostgreSQL Inc.
-- (c) 2005, Laurent Destailleur.

-- ===================================================================
-- Copyright (C) 2003-2004 Rodolphe Quiedeville <rodolphe@quiedeville.org>
-- Copyright (C) 2004 Laurent Destailleur  <eldy@users.sourceforge.net>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
--
-- Id: llx_paiementfourn.sql,v 1.8 2007/12/02 21:37:41 eldy Exp 
-- ===================================================================

create table llx_paiementfourn
(
  rowid SERIAL PRIMARY KEY,
  "tms"               timestamp,
  "datec"             timestamp,          -- date de creation de l'enregistrement
  "fk_facture_fourn"  integer,           -- facture
  "datep"             timestamp,          -- date de paiement
  "amount"            real DEFAULT 0,    -- montant
  "fk_user_author"    integer,           -- auteur
  "fk_paiement"       integer NOT NULL,  -- moyen de paiement
  "num_paiement"      varchar(50),       -- numéro de paiement (cheque)
  "note"              text,
  "fk_bank"           integer NOT NULL,
  "statut"			int2 NOT NULL DEFAULT 0
);
