-- Generated by dolibarr_mysql2pgsql
-- (c) 2004, PostgreSQL Inc.
-- (c) 2005, Laurent Destailleur.

-- ========================================================================
-- Copyright (C) 2001-2002 Rodolphe Quiedeville <rodolphe@quiedeville.org>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
--
-- Id: llx_chargesociales.sql,v 1.8 2007/12/16 20:40:10 eldy Exp 
-- ========================================================================

create table llx_chargesociales
(
  rowid SERIAL PRIMARY KEY,
  "date_ech"   timestamp, -- date d'echeance
  "libelle"    varchar(80) NOT NULL,
  "fk_type"    integer NOT NULL,
  "amount"     real     default 0 NOT NULL,
  "paye"       smallint default 0 NOT NULL,
  "periode"    date
);



