dolibarr: htdocs/admin/system/modules.php File Reference
modules.php File Reference
File to list all Dolibarr modules.
Functions
compareIdAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
compareIdDesc (stdClass $a, stdClass $b)
Compare two modules by their ID for a descending order.
comparePermissionIdsAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
comparePermissionIdsDesc (stdClass $a, stdClass $b)
Compare two modules by their permissions for a descending order.
Detailed Description
File to list all Dolibarr modules.
Definition in file modules.php.
Function Documentation
compareIdAsc()
compareIdAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 393 of file modules.php.
Referenced by comparePermissionIdsAsc().
compareIdDesc()
compareIdDesc (stdClass $a, stdClass $b)
Compare two modules by their ID for a descending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 409 of file modules.php.
Referenced by comparePermissionIdsDesc().
comparePermissionIdsAsc()
comparePermissionIdsAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 425 of file modules.php.
References compareIdAsc().
comparePermissionIdsDesc()
comparePermissionIdsDesc (stdClass $a, stdClass $b)
Compare two modules by their permissions for a descending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 452 of file modules.php.
References compareIdDesc().