dolibarr: htdocs/core/class/vcard.class.php File Reference
vcard.class.php File Reference
Class to manage vCard files.
Classes
class vCard
Class to buld vCard files.
Functions
encode ($string)
Encode a string for vCard.
dol_quoted_printable_encode ($input, $line_max=76)
Taken from php documentation comments No more used.
Detailed Description
Class to manage vCard files.
Definition in file vcard.class.php.
Function Documentation
dol_quoted_printable_encode()
dol_quoted_printable_encode ($input, $line_max = 76)
Taken from php documentation comments No more used.
Parameters
string $input String
int $line_max Max length of lines
Returns
string Encoded string
Definition at line 46 of file vcard.class.php.
encode()
encode ($string)
Encode a string for vCard.
Parameters
string $string String to encode
Returns
string String encoded
Definition at line 32 of file vcard.class.php.
Referenced by vCard\setOrg(), vCard\setProdId(), and vCard\setUID().