dolibarr: Facture Class Reference
Facture Class Reference
Class to manage invoices.
Public Member Functions
__construct (DoliDB $db)
Constructor.
create (User $user, $notrigger=0, $forceduedate=0)
Create invoice in database.
createFromCurrent (User $user, $invertdetail=0)
Create a new invoice in database from current invoice.
createFromClone (User $user, $fromid=0)
Load an object from its id and create a new one in database.
createFromOrder ($object, User $user)
Load an object from an order and create a new invoice into database.
getNomUrl ($withpicto=0, $option='', $max=0, $short=0, $moretitle='', $notooltip=0, $addlinktonotes=0, $save_lastsearch_value=-1, $target='')
Return clicable link of object (with eventually picto)
fetch ($rowid, $ref='', $ref_ext='', $notused='', $fetch_situation=false)
Get object from database.
fetch_lines ($only_product=0, $loadalsotranslation=0)
Load all detailed lines into this->lines.
fetchPreviousNextSituationInvoice ()
Fetch previous and next situations invoices.
update (User $user, $notrigger=0)
Update database.
insert_discount ($idremise)
Add a discount line into an invoice (as an invoice line) using an existing absolute discount (Consume the discount)
set_ref_client ($ref_client, $notrigger=0)
Set customer ref.
delete ($user, $notrigger=0, $idwarehouse=-1)
Delete invoice.
set_paid ($user, $close_code='', $close_note='')
Tag the invoice as paid completely (if close_code is filled) => this->fk_statut=2, this->paye=1 or partialy (if close_code filled) + appel trigger BILL_PAYED => this->fk_statut=2, this->paye stay 0.
setPaid ($user, $close_code='', $close_note='')
Tag the invoice as paid completely (if close_code is filled) => this->fk_statut=2, this->paye=1 or partially (if close_code filled) + appel trigger BILL_PAYED => this->fk_statut=2, this->paye stay 0.
set_unpaid ($user)
Tag la facture comme non payee completement + appel trigger BILL_UNPAYED Fonction utilisee quand un paiement prelevement est refuse, ou quand une facture annulee et reouverte.
setUnpaid ($user)
Tag la facture comme non payee completement + appel trigger BILL_UNPAYED Fonction utilisee quand un paiement prelevement est refuse, ou quand une facture annulee et reouverte.
set_canceled ($user, $close_code='', $close_note='')
Tag invoice as canceled, with no payment on it (example for replacement invoice or payment never received) + call trigger BILL_CANCEL Warning, if option to decrease stock on invoice was set, this function does not change stock (it might be a cancel because of no payment even if merchandises were sent).
setCanceled ($user, $close_code='', $close_note='')
Tag invoice as canceled, with no payment on it (example for replacement invoice or payment never received) + call trigger BILL_CANCEL Warning, if option to decrease stock on invoice was set, this function does not change stock (it might be a cancel because of no payment even if merchandises were sent).
validate ($user, $force_number='', $idwarehouse=0, $notrigger=0, $batch_rule=0)
Tag invoice as validated + call trigger BILL_VALIDATE Object must have lines loaded with fetch_lines.
updatePriceNextInvoice (&$langs)
Update price of next invoice.
setDraft ($user, $idwarehouse=-1)
Set draft status.
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1=0, $txlocaltax2=0, $fk_product=0, $remise_percent=0, $date_start='', $date_end='', $ventil=0, $info_bits=0, $fk_remise_except='', $price_base_type='HT', $pu_ttc=0, $type=0, $rang=-1, $special_code=0, $origin='', $origin_id=0, $fk_parent_line=0, $fk_fournprice=null, $pa_ht=0, $label='', $array_options=0, $situation_percent=100, $fk_prev_id=0, $fk_unit=null, $pu_ht_devise=0, $ref_ext='', $noupdateafterinsertline=0)
Add an invoice line into database (linked to product/service or not).
updateline ($rowid, $desc, $pu, $qty, $remise_percent, $date_start, $date_end, $txtva, $txlocaltax1=0, $txlocaltax2=0, $price_base_type='HT', $info_bits=0, $type=self::TYPE_STANDARD, $fk_parent_line=0, $skip_update_total=0, $fk_fournprice=null, $pa_ht=0, $label='', $special_code=0, $array_options=0, $situation_percent=100, $fk_unit=null, $pu_ht_devise=0, $notrigger=0, $ref_ext='', $rang=0)
Update a detail line.
checkProgressLine ($idline, $situation_percent)
Check if the percent edited is lower of next invoice line.
update_percent ($line, $percent, $update_price=true)
Update invoice line with percentage.
deleteline ($rowid, $id=0)
Delete line in database.
set_remise ($user, $remise, $notrigger=0)
Set percent discount.
setDiscount ($user, $remise, $notrigger=0)
Set percent discount.
set_remise_absolue ($user, $remise, $notrigger=0)
Set absolute discount.
getNextNumRef ($soc, $mode='next')
Return next reference of customer invoice not already used (or last reference) according to numbering module defined into constant FACTURE_ADDON.
info ($id)
Load miscellaneous information for tab "Info".
liste_array ($shortlist=0, $draft=0, $excluser='', $socid=0, $limit=0, $offset=0, $sortfield='f.datef, f.rowid', $sortorder='DESC')
Return list of invoices (eventually filtered on a user) into an array.
list_replacable_invoices ($socid=0)
Return list of invoices qualified to be replaced by another invoice.
list_qualified_avoir_invoices ($socid=0)
Return list of invoices qualified to be corrected by a credit note.
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
getIdBillingContact ()
Retourne id des contacts clients de facturation.
getIdShippingContact ()
Retourne id des contacts clients de livraison.
initAsSpecimen ($option='')
Initialise an instance with random values.
load_state_board ()
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
getLinesArray ()
Create an array of invoice lines.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
newCycle ()
Gets the smallest reference available for a new cycle.
is_first ()
Checks if the invoice is the first of a cycle.
get_prev_sits ()
Returns an array containing the previous situations as Facture objects.
setFinal (User $user, $notrigger=0)
Sets the invoice as a final situation.
is_last_in_cycle ()
Checks if the invoice is the last in its cycle.
hasDelay ()
Is the customer invoice delayed?
displayRetainedWarranty ()
Currently used for documents generation : to know if retained warranty need to be displayed.
getRetainedWarrantyAmount ($rounding=-1)
setRetainedWarranty ($value)
Change the retained warranty.
setRetainedWarrantyDateLimit ($timestamp, $dateYmd=false)
Change the retained_warranty_date_limit.
sendEmailsRemindersOnInvoiceDueDate ($nbdays=0, $paymentmode='all', $template='', $forcerecipient='')
Send reminders by emails for ivoices that are due CAN BE A CRON TASK.
willBeLastOfSameType ($allow_validated_drafts=false)
See if current invoice date is posterior to the last invoice date among validated invoices of same type.
Public Member Functions inherited from CommonInvoice
getRemainToPay ($multicurrency=0)
Return remain amount to pay.
getSommePaiement ($multicurrency=0)
Return amount of payments already done.
getSumDepositsUsed ($multicurrency=0)
Return amount (with tax) of all deposits invoices used by invoice.
getSumCreditNotesUsed ($multicurrency=0)
Return amount (with tax) of all credit notes invoices + excess received used by invoice.
getSumFromThisCreditNotesNotUsed ($multicurrency=0)
Return amount (with tax) of all converted amount for this credit note.
getListIdAvoirFromInvoice ()
Returns array of credit note ids from the invoice.
getIdReplacingInvoice ($option='')
Returns the id of the invoice that replaces it.
getListOfPayments ($filtertype='')
Return list of payments.
is_erasable ()
Return if an invoice can be deleted Rule is: If invoice is draft and has a temporary ref -> yes (1) If hidden option INVOICE_CAN_NEVER_BE_REMOVED is on -> no (0) If invoice is dispatched in bookkeeping -> no (-1) If invoice has a definitive ref, is not last and INVOICE_CAN_ALWAYS_BE_REMOVED off -> no (-2) If invoice not last in a cycle -> no (-3) If there is payment -> no (-4) Otherwise -> yes (2)
getVentilExportCompta ()
Return if an invoice was dispatched into bookkeeping.
getLibType ($withbadge=0)
Return label of type of invoice.
getLibStatut ($mode=0, $alreadypaid=-1)
Return label of object status.
LibStatut ($paye, $status, $mode=0, $alreadypaid=-1, $type=-1)
Return label of a status.
calculate_date_lim_reglement ($cond_reglement=0)
Returns an invoice payment deadline based on the invoice settlement conditions and billing date.
demande_prelevement ($fuser, $amount=0, $type='direct-debit', $sourcetype='facture')
Create a withdrawal request for a direct debit order or a credit transfer order.
makeStripeSepaRequest ($fuser, $did=0, $type='direct-debit', $sourcetype='facture')
Create a withdrawal request for a direct debit order or a credit transfer order.
demande_prelevement_delete ($fuser, $did)
Remove a direct debit request or a credit transfer request.
buildZATCAQRString ()
Build string for ZATCA QR Code (Arabi Saudia)
buildSwitzerlandQRString ()
Build string for QR-Bill (Switzerland)
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static createDepositFromOrigin (CommonObject $origin, $date, $payment_terms_id, User $user, $notrigger=0, $autoValidateDeposit=false, $overrideFields=array())
Creates a deposit from a proposal or an order by grouping lines by VAT rates.
static replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
static replaceProduct (DoliDB $db, $origin_id, $dest_id)
Function used to replace a product id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
$paye
1 if invoice paid COMPLETELY, 0 otherwise (do not use it anymore, use statut and close_code)
$module_source
key of module source when invoice generated from a dedicated module ('cashdesk', 'takepos', ...)
$pos_source
key of pos source ('0', '1', ...)
$fk_fac_rec_source
id of template invoice when generated from a template invoice
$fk_facture_source
id of source invoice if replacement invoice or credit note
const TYPE_STANDARD = 0
Standard invoice.
const TYPE_REPLACEMENT = 1
Replacement invoice.
const TYPE_CREDIT_NOTE = 2
Credit note invoice.
const TYPE_DEPOSIT = 3
Deposit invoice.
const TYPE_PROFORMA = 4
Proforma invoice (should not be used.
const TYPE_SITUATION = 5
Situation invoice.
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated (need to be paid)
const STATUS_CLOSED = 2
Classified paid.
const STATUS_ABANDONED = 3
Classified abandoned and no payment done.
Public Attributes inherited from CommonInvoice
const TYPE_STANDARD = 0
Standard invoice.
const TYPE_REPLACEMENT = 1
Replacement invoice.
const TYPE_CREDIT_NOTE = 2
Credit note invoice.
const TYPE_DEPOSIT = 3
Deposit invoice.
const TYPE_PROFORMA = 4
Proforma invoice.
const TYPE_SITUATION = 5
Situation invoice.
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated (need to be paid)
const STATUS_CLOSED = 2
Classified paid.
const STATUS_ABANDONED = 3
Classified abandoned and no payment done.
Public Attributes inherited from CommonObject
$projet
$fk_projet
$note
Protected Attributes
$table_ref_field = 'ref'
{}
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage invoices.
Definition at line 60 of file facture.class.php.
Constructor & Destructor Documentation
__construct()
Facture::__construct (DoliDB $db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 446 of file facture.class.php.
References db.
Member Function Documentation
addline()
Facture::addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $fk_product = 0, $remise_percent = 0, $date_start = '', $date_end = '', $ventil = 0, $info_bits = 0, $fk_remise_except = '', $price_base_type = 'HT', $pu_ttc = 0, $type = 0, $rang = -1, $special_code = 0, $origin = '', $origin_id = 0, $fk_parent_line = 0, $fk_fournprice = null, $pa_ht = 0, $label = '', $array_options = 0, $situation_percent = 100, $fk_prev_id = 0, $fk_unit = null, $pu_ht_devise = 0, $ref_ext = '', $noupdateafterinsertline = 0)
Add an invoice line into database (linked to product/service or not).
Les parametres sont deja cense etre juste et avec valeurs finales a l'appel de cette methode. Aussi, pour le taux tva, il doit deja avoir ete defini par l'appelant par la methode get_default_tva(societe_vendeuse,societe_acheteuse,produit) et le desc doit deja avoir la bonne valeur (a l'appelant de gerer le multilangue)
Parameters
string $desc Description of line
double $pu_ht Unit price without tax (> 0 even for credit note)
double $qty Quantity
double $txtva Force Vat rate, -1 for auto (Can contain the vat_src_code too with syntax '9.9 (CODE)')
double $txlocaltax1 Local tax 1 rate (deprecated, use instead txtva with code inside)
double $txlocaltax2 Local tax 2 rate (deprecated, use instead txtva with code inside)
int $fk_product Id of predefined product/service
double $remise_percent Percent of discount on line
int $date_start Date start of service
int $date_end Date end of service
int $ventil Code of dispatching into accountancy
int $info_bits Bits of type of lines
int $fk_remise_except Id discount used
string $price_base_type 'HT' or 'TTC'
double $pu_ttc Unit price with tax (> 0 even for credit note)
int $type Type of line (0=product, 1=service). Not used if fk_product is defined, the type of product is used.
int $rang Position of line (-1 means last value + 1)
int $special_code Special code (also used by externals modules!)
string $origin Depend on global conf MAIN_CREATEFROM_KEEP_LINE_ORIGIN_INFORMATION can be 'orderdet', 'propaldet'..., else 'order','propal,'....
int $origin_id Depend on global conf MAIN_CREATEFROM_KEEP_LINE_ORIGIN_INFORMATION can be Id of origin object (aka line id), else object id
int $fk_parent_line Id of parent line
int $fk_fournprice Supplier price id (to calculate margin) or ''
int $pa_ht Buying price of line (to calculate margin) or ''
string $label Label of the line (deprecated, do not use)
array $array_options extrafields array
int $situation_percent Situation advance percentage
int $fk_prev_id Previous situation line id reference
string $fk_unit Code of the unit to use. Null to use the default one
double $pu_ht_devise Unit price in foreign currency
string $ref_ext External reference of the line
int $noupdateafterinsertline No update after insert of line
Returns
int <0 if KO, Id of line if OK
Definition at line 3575 of file facture.class.php.
checkProgressLine()
Facture::checkProgressLine ($idline, $situation_percent)
Check if the percent edited is lower of next invoice line.
Parameters
int $idline id of line to check
float $situation_percent progress percentage need to be test
Returns
false if KO, true if OK
Definition at line 4083 of file facture.class.php.
create()
Facture::create (User $user, $notrigger = 0, $forceduedate = 0)
Create invoice in database.
Note: this->ref can be set or empty. If empty, we will use "(PROV999)" Note: this->fac_rec must be set to create invoice from a recurring invoice
Parameters
User $user Object user that create
int $notrigger 1=Does not execute triggers, 0 otherwise
int $forceduedate If set, do not recalculate due date from payment condition but force it with value
Returns
int <0 if KO, >0 if OK
Definition at line 461 of file facture.class.php.
createDepositFromOrigin()
static Facture::createDepositFromOrigin (CommonObject $origin, $date, $payment_terms_id, User $user, $notrigger = 0, $autoValidateDeposit = false, $overrideFields = array()) static
Creates a deposit from a proposal or an order by grouping lines by VAT rates.
Parameters
Propal | Commande $origin The original proposal or order
int $date Invoice date
int $payment_terms_id Invoice payment terms
User $user Object user
int $notrigger 1=Does not execute triggers, 0= execute triggers
bool $autoValidateDeposit Whether to aumatically validate the deposit created
array $overrideFields Array of fields to force values
Returns
Facture|null The deposit created, or null if error (populates $origin->error in this case)
Definition at line 1491 of file facture.class.php.
createFromClone()
Facture::createFromClone (User $user, $fromid = 0)
Load an object from its id and create a new one in database.
Parameters
User $user User that clone
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 1217 of file facture.class.php.
createFromCurrent()
Facture::createFromCurrent (User $user, $invertdetail = 0)
Create a new invoice in database from current invoice.
Parameters
User $user Object user that ask creation
int $invertdetail Reverse sign of amounts for lines
Returns
int <0 if KO, >0 if OK
Definition at line 1124 of file facture.class.php.
createFromOrder()
Facture::createFromOrder ($object, User $user)
Load an object from an order and create a new invoice into database.
Parameters
Object $object Object source
User $user Object user
Returns
int <0 if KO, 0 if nothing done, 1 if OK
Definition at line 1357 of file facture.class.php.
delete()
Facture::delete ($user, $notrigger = 0, $idwarehouse = -1)
Delete invoice.
Parameters
User $user User making the deletion.
int $notrigger 1=Does not execute triggers, 0= execute triggers
int $idwarehouse Id warehouse to use for stock change.
Returns
int <0 if KO, 0=Refused, >0 if OK
Definition at line 2561 of file facture.class.php.
deleteline()
Facture::deleteline ($rowid, $id = 0)
Delete line in database.
Parameters
int $rowid Id of line to delete
int $id Id of object (for a check)
Returns
int <0 if KO, >0 if OK
Definition at line 4154 of file facture.class.php.
displayRetainedWarranty()
Facture::displayRetainedWarranty ()
Currently used for documents generation : to know if retained warranty need to be displayed.
Returns
bool
Definition at line 5274 of file facture.class.php.
fetch()
Facture::fetch ($rowid, $ref = '', $ref_ext = '', $notused = '', $fetch_situation = false)
Get object from database.
Get also lines.
Parameters
int $rowid Id of object to load
string $ref Reference of invoice
string $ref_ext External reference of invoice
int $notused Not used
bool $fetch_situation Load also the previous and next situation invoice into $tab_previous_situation_invoice and $tab_next_situation_invoice
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 1927 of file facture.class.php.
fetch_lines()
Facture::fetch_lines ($only_product = 0, $loadalsotranslation = 0)
Load all detailed lines into this->lines.
Parameters
int $only_product Return only physical products
int $loadalsotranslation Return translation for products
Returns
int 1 if OK, < 0 if KO
Definition at line 2105 of file facture.class.php.
Referenced by getLinesArray().
fetchPreviousNextSituationInvoice()
Facture::fetchPreviousNextSituationInvoice ()
Fetch previous and next situations invoices.
Return all previous and next invoices (both standard and credit notes).
Returns
void
Definition at line 2224 of file facture.class.php.
generateDocument()
Facture::generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Generator to use. Caller must set it to obj->model_pdf or GETPOST('model','alpha') for example.
Translate $outputlangs Object lang to use for translation
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int <0 if KO, >0 if OK
Definition at line 5027 of file facture.class.php.
get_prev_sits()
Facture::get_prev_sits ()
Returns an array containing the previous situations as Facture objects.
Returns
mixed -1 if error, array of previous situations
Definition at line 5098 of file facture.class.php.
getIdBillingContact()
Facture::getIdBillingContact ()
Retourne id des contacts clients de facturation.
Returns
array Liste des id contacts facturation
Definition at line 4793 of file facture.class.php.
References CommonObject\getIdContact().
getIdShippingContact()
Facture::getIdShippingContact ()
Retourne id des contacts clients de livraison.
Returns
array Liste des id contacts livraison
Definition at line 4803 of file facture.class.php.
References CommonObject\getIdContact().
getLinesArray()
Facture::getLinesArray ()
Create an array of invoice lines.
Returns
int >0 if OK, <0 if KO
Definition at line 5011 of file facture.class.php.
References fetch_lines().
getNextNumRef()
Facture::getNextNumRef ($soc, $mode = 'next')
Return next reference of customer invoice not already used (or last reference) according to numbering module defined into constant FACTURE_ADDON.
Parameters
Societe $soc object company
string $mode 'next' for next value or 'last' for last value
Returns
string free ref or last ref
$numref can be empty in case we ask for the last value because if there is no invoice created with the set up mask.
Definition at line 4369 of file facture.class.php.
getNomUrl()
Facture::getNomUrl ($withpicto = 0, $option = '', $max = 0, $short = 0, $moretitle = '', $notooltip = 0, $addlinktonotes = 0, $save_lastsearch_value = -1, $target = '')
Return clicable link of object (with eventually picto)
Parameters
int $withpicto Add picto into link
string $option Where point the link
int $max Maxlength of ref
int $short 1=Return just URL
string $moretitle Add more text to title tooltip
int $notooltip 1=Disable tooltip
int $addlinktonotes 1=Add link to notes
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
string $target Target of link ('', '_self', '_blank', '_parent', '_backoffice', ...)
Returns
string String with URL
Definition at line 1779 of file facture.class.php.
getRetainedWarrantyAmount()
Facture::getRetainedWarrantyAmount ($rounding = -1)
Parameters
int $rounding Minimum number of decimal to show. If 0, no change, if -1, we use min($conf->global->MAIN_MAX_DECIMALS_UNIT,$conf->global->MAIN_MAX_DECIMALS_TOT)
Returns
float or -1 if not available
Definition at line 5312 of file facture.class.php.
hasDelay()
Facture::hasDelay ()
Is the customer invoice delayed?
Returns
bool
Definition at line 5240 of file facture.class.php.
info()
Facture::info ($id)
Load miscellaneous information for tab "Info".
Parameters
int $id Id of object to load
Returns
void
Definition at line 4474 of file facture.class.php.
initAsSpecimen()
Facture::initAsSpecimen ($option = '')
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Parameters
string $option ''=Create a specimen invoice with lines, 'nolines'=No lines
Returns
void
Definition at line 4817 of file facture.class.php.
insert_discount()
Facture::insert_discount ($idremise)
Add a discount line into an invoice (as an invoice line) using an existing absolute discount (Consume the discount)
Parameters
int $idremise Id of absolute discount
Returns
int >0 if OK, <0 if KO
Definition at line 2403 of file facture.class.php.
is_first()
Facture::is_first ()
Checks if the invoice is the first of a cycle.
Returns
boolean
Definition at line 5086 of file facture.class.php.
is_last_in_cycle()
Facture::is_last_in_cycle ()
Checks if the invoice is the last in its cycle.
Returns
bool Last of the cycle status
Definition at line 5175 of file facture.class.php.
list_qualified_avoir_invoices()
Facture::list_qualified_avoir_invoices ($socid = 0)
Return list of invoices qualified to be corrected by a credit note.
Invoices matching the following rules are returned: (validated + payment on process) or classified (payed completely or payed partiely) + not already replaced + not already a credit note
Parameters
int $socid Id thirdparty
Returns
array Array of invoices ($id => array('ref'=>,'paymentornot'=>,'status'=>,'paye'=>)
Definition at line 4653 of file facture.class.php.
list_replacable_invoices()
Facture::list_replacable_invoices ($socid = 0)
Return list of invoices qualified to be replaced by another invoice.
Invoices matching the following rules are returned: (Status validated or abandonned for a reason 'other') + not payed + no payment at all + not already replaced
Parameters
int $socid Id thirdparty
Returns
array|int Array of invoices ('id'=>id, 'ref'=>ref, 'status'=>status, 'paymentornot'=>0/1)
Definition at line 4599 of file facture.class.php.
liste_array()
Facture::liste_array ($shortlist = 0, $draft = 0, $excluser = '', $socid = 0, $limit = 0, $offset = 0, $sortfield = 'f.datef, f.rowid' , $sortorder = 'DESC')
Return list of invoices (eventually filtered on a user) into an array.
Parameters
int $shortlist 0=Return array[id]=ref, 1=Return array[](id=>id,ref=>ref,name=>name)
int $draft 0=not draft, 1=draft
User $excluser Objet user to exclude
int $socid Id third pary
int $limit For pagination
int $offset For pagination
string $sortfield Sort criteria
string $sortorder Sort order
Returns
array|int -1 if KO, array with result if OK
Definition at line 4529 of file facture.class.php.
load_board()
Facture::load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Object user
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 4728 of file facture.class.php.
load_state_board()
Facture::load_state_board ()
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Returns
int <0 if KO, >0 if OK
Definition at line 4973 of file facture.class.php.
newCycle()
Facture::newCycle ()
Gets the smallest reference available for a new cycle.
Returns
int >= 1 if OK, -1 if error
Definition at line 5058 of file facture.class.php.
replaceProduct()
static Facture::replaceProduct (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a product id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old product id
int $dest_id New product id
Returns
bool
Definition at line 5226 of file facture.class.php.
References CommonObject\commonReplaceProduct().
replaceThirdparty()
static Facture::replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 5209 of file facture.class.php.
References CommonObject\commonReplaceThirdparty().
sendEmailsRemindersOnInvoiceDueDate()
Facture::sendEmailsRemindersOnInvoiceDueDate ($nbdays = 0, $paymentmode = 'all', $template = '', $forcerecipient = '')
Send reminders by emails for ivoices that are due CAN BE A CRON TASK.
Parameters
int $nbdays Delay after due date (or before if delay is negative)
string $paymentmode '' or 'all' by default (no filter), or 'LIQ', 'CHQ', CB', ...
int | string $template Name (or id) of email template (Must be a template of type 'facture_send')
string $forcerecipient Force email of recipient (for example to send the email to an accountant supervisor instead of the customer)
Returns
int 0 if OK, <>0 if KO (this function is used also by cron so only 0 is OK)
Definition at line 5443 of file facture.class.php.
set_canceled()
Facture::set_canceled ($user, $close_code = '', $close_note = '')
Tag invoice as canceled, with no payment on it (example for replacement invoice or payment never received) + call trigger BILL_CANCEL Warning, if option to decrease stock on invoice was set, this function does not change stock (it might be a cancel because of no payment even if merchandises were sent).
Deprecated:
See also
setCanceled()
Parameters
User $user Object user making change
string $close_code Code of closing invoice (CLOSECODE_REPLACED, CLOSECODE_...)
string $close_note Comment
Returns
int <0 if KO, >0 if OK
Definition at line 2898 of file facture.class.php.
References dol_syslog(), and setCanceled().
set_paid()
Facture::set_paid ($user, $close_code = '', $close_note = '')
Tag the invoice as paid completely (if close_code is filled) => this->fk_statut=2, this->paye=1 or partialy (if close_code filled) + appel trigger BILL_PAYED => this->fk_statut=2, this->paye stay 0.
Deprecated:
See also
setPaid()
Parameters
User $user Object user that modify
string $close_code Code renseigne si on classe a payee completement alors que paiement incomplet (cas escompte par exemple)
string $close_note Commentaire renseigne si on classe a payee alors que paiement incomplet (cas escompte par exemple)
Returns
int <0 if KO, >0 if OK
Definition at line 2754 of file facture.class.php.
References dol_syslog(), and setPaid().
set_ref_client()
Facture::set_ref_client ($ref_client, $notrigger = 0)
Set customer ref.
Parameters
string $ref_client Customer ref
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2501 of file facture.class.php.
set_remise()
Facture::set_remise ($user, $remise, $notrigger = 0)
Set percent discount.
Deprecated:
See also
setDiscount()
Parameters
User $user User that set discount
double $remise Discount
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Definition at line 4229 of file facture.class.php.
References dol_syslog(), and setDiscount().
set_remise_absolue()
Facture::set_remise_absolue ($user, $remise, $notrigger = 0)
Set absolute discount.
Parameters
User $user User that set discount
double $remise Discount
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 4306 of file facture.class.php.
References db, and price2num().
set_unpaid()
Facture::set_unpaid ($user)
Tag la facture comme non payee completement + appel trigger BILL_UNPAYED Fonction utilisee quand un paiement prelevement est refuse, ou quand une facture annulee et reouverte.
Deprecated:
See also
setUnpaid()
Parameters
User $user Object user that change status
Returns
int <0 if KO, >0 if OK
Definition at line 2833 of file facture.class.php.
References dol_syslog(), and setUnpaid().
setCanceled()
Facture::setCanceled ($user, $close_code = '', $close_note = '')
Tag invoice as canceled, with no payment on it (example for replacement invoice or payment never received) + call trigger BILL_CANCEL Warning, if option to decrease stock on invoice was set, this function does not change stock (it might be a cancel because of no payment even if merchandises were sent).
Parameters
User $user Object user making change
string $close_code Code of closing invoice (CLOSECODE_REPLACED, CLOSECODE_...)
string $close_note Comment
Returns
int <0 if KO, >0 if OK
Definition at line 2915 of file facture.class.php.
References db, and dol_syslog().
Referenced by set_canceled().
setDiscount()
Facture::setDiscount ($user, $remise, $notrigger = 0)
Set percent discount.
Parameters
User $user User that set discount
double $remise Discount
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if ko, >0 if ok
Definition at line 4244 of file facture.class.php.
References db, and price2num().
Referenced by set_remise().
setDraft()
Facture::setDraft ($user, $idwarehouse = -1)
Set draft status.
Parameters
User $user Object user that modify
int $idwarehouse Id warehouse to use for stock change.
Returns
int <0 if KO, >0 if OK
Definition at line 3453 of file facture.class.php.
setFinal()
Facture::setFinal (User $user, $notrigger = 0)
Sets the invoice as a final situation.
Parameters
User $user Object user
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 5132 of file facture.class.php.
References db.
setPaid()
Facture::setPaid ($user, $close_code = '', $close_note = '')
Tag the invoice as paid completely (if close_code is filled) => this->fk_statut=2, this->paye=1 or partially (if close_code filled) + appel trigger BILL_PAYED => this->fk_statut=2, this->paye stay 0.
Parameters
User $user Object user that modify
string $close_code Code renseigne si on classe a payee completement alors que paiement incomplet (cas escompte par exemple)
string $close_note Commentaire renseigne si on classe a payee alors que paiement incomplet (cas escompte par exemple)
Returns
int <0 if KO, >0 if OK
Definition at line 2770 of file facture.class.php.
References db.
Referenced by set_paid().
setRetainedWarranty()
Facture::setRetainedWarranty ($value)
Change the retained warranty.
Parameters
float $value value of retained warranty
Returns
int >0 if OK, <0 if KO
Definition at line 5370 of file facture.class.php.
setRetainedWarrantyDateLimit()
Facture::setRetainedWarrantyDateLimit ($timestamp, $dateYmd = false)
Change the retained_warranty_date_limit.
Parameters
int $timestamp date limit of retained warranty in timestamp format
string $dateYmd date limit of retained warranty in Y m d format
Returns
int >0 if OK, <0 if KO
Definition at line 5403 of file facture.class.php.
setUnpaid()
Facture::setUnpaid ($user)
Tag la facture comme non payee completement + appel trigger BILL_UNPAYED Fonction utilisee quand un paiement prelevement est refuse, ou quand une facture annulee et reouverte.
Parameters
User $user Object user that change status
Returns
int <0 if KO, >0 if OK
Definition at line 2848 of file facture.class.php.
References db.
Referenced by set_unpaid().
update()
Facture::update (User $user, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2262 of file facture.class.php.
update_percent()
Facture::update_percent ($line, $percent, $update_price = true)
Update invoice line with percentage.
Parameters
FactureLigne $line Invoice line
int $percent Percentage
boolean $update_price Update object price
Returns
void
Definition at line 4113 of file facture.class.php.
updateline()
Facture::updateline ($rowid, $desc, $pu, $qty, $remise_percent, $date_start, $date_end, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $price_base_type = 'HT', $info_bits = 0, $type = self::TYPE_STANDARD, $fk_parent_line = 0, $skip_update_total = 0, $fk_fournprice = null, $pa_ht = 0, $label = '', $special_code = 0, $array_options = 0, $situation_percent = 100, $fk_unit = null, $pu_ht_devise = 0, $notrigger = 0, $ref_ext = '', $rang = 0)
Update a detail line.
Parameters
int $rowid Id of line to update
string $desc Description of line
double $pu Prix unitaire (HT ou TTC selon price_base_type) (> 0 even for credit note lines)
double $qty Quantity
double $remise_percent Percentage discount of the line
int $date_start Date de debut de validite du service
int $date_end Date de fin de validite du service
double $txtva VAT Rate (Can be '8.5', '8.5 (ABC)')
double $txlocaltax1 Local tax 1 rate
double $txlocaltax2 Local tax 2 rate
string $price_base_type HT or TTC
int $info_bits Miscellaneous informations
int $type Type of line (0=product, 1=service)
int $fk_parent_line Id of parent line (0 in most cases, used by modules adding sublevels into lines).
int $skip_update_total Keep fields total_xxx to 0 (used for special lines by some modules)
int $fk_fournprice Id of origin supplier price
int $pa_ht Price (without tax) of product when it was bought
string $label Label of the line (deprecated, do not use)
int $special_code Special code (also used by externals modules!)
array $array_options extrafields array
int $situation_percent Situation advance percentage
string $fk_unit Code of the unit to use. Null to use the default one
double $pu_ht_devise Unit price in currency
int $notrigger disable line update trigger
string $ref_ext External reference of the line
integer $rang rank of line
Returns
int < 0 if KO, > 0 if OK
Definition at line 3871 of file facture.class.php.
updatePriceNextInvoice()
Facture::updatePriceNextInvoice (& $langs)
Update price of next invoice.
Parameters
Translate $langs Translate object
Returns
bool false if KO, true if OK
Definition at line 3396 of file facture.class.php.
validate()
Facture::validate ($user, $force_number = '', $idwarehouse = 0, $notrigger = 0, $batch_rule = 0)
Tag invoice as validated + call trigger BILL_VALIDATE Object must have lines loaded with fetch_lines.
Parameters
User $user Object user that validate
string $force_number Reference to force on invoice
int $idwarehouse Id of warehouse to use for stock decrease if option to decreasenon stock is on (0=no decrease)
int $notrigger 1=Does not execute triggers, 0= execute triggers
int $batch_rule 0=do not decrement batch, else batch rule to use, 1=take in batches ordered by sellby and eatby dates
Returns
int <0 if KO, 0=Nothing done because invoice is not a draft, >0 if OK
Definition at line 2974 of file facture.class.php.
willBeLastOfSameType()
Facture::willBeLastOfSameType ($allow_validated_drafts = false)
See if current invoice date is posterior to the last invoice date among validated invoices of same type.
Parameters
boolean $allow_validated_drafts return true if the invoice has been validated before returning to DRAFT state.
Returns
array return array
Definition at line 5715 of file facture.class.php.
Member Data Documentation
STATUS_ABANDONED
const Facture::STATUS_ABANDONED = 3
Classified abandoned and no payment done.
$this->close_code can be:
CLOSECODE_BADDEBT
CLOSECODE_ABANDONED
CLOSECODE_REPLACED
Definition at line 430 of file facture.class.php.
STATUS_CLOSED
const Facture::STATUS_CLOSED = 2
Classified paid.
If paid partially, $this->close_code can be:
CLOSECODE_DISCOUNTVAT
CLOSECODE_BADDEBT If paid completely, this->close_code will be null
Definition at line 421 of file facture.class.php.
TYPE_PROFORMA
const Facture::TYPE_PROFORMA = 4
Proforma invoice (should not be used.
a proforma is an order)
Definition at line 397 of file facture.class.php.
The documentation for this class was generated from the following file:
htdocs/compta/facture/class/facture.class.php