/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function A(a){return{allowedContent:{div:{match:q(a),styles:"text-align"},figcaption:!0,figure:{classes:"!caption",styles:"float,display"},img:{attributes:"!src,alt,width,height",styles:"float"},p:{match:q(a),styles:"text-align"}},requiredContent:"img[src,alt]",features:{dimension:{requiredContent:"img[width,height]"},align:{requiredContent:"img{float}"},caption:{requiredContent:"figcaption"}},contentTransformations:[["img[width]: sizeToAttribute"]],editables:{caption:{selector:"figcaption",
allowedContent:"br em strong sub sup u s; a[!href]"}},parts:{image:"img",caption:"figcaption"},dialog:"image2",template:u,data:function(){var a=this,b=a.editor,e=b.document,f=b.editable(),g=a.oldData,d=a.data,k=this.features;d.hasCaption&&!b.filter.checkFeature(k.caption)&&(d.hasCaption=!1);"none"!=d.align&&!b.filter.checkFeature(k.align)&&(d.align="none");a.shiftState({element:a.element,oldState:g,newState:d,destroy:function(){if(!this.destroyed){if(b.widgets.focused==a)this.focused=true;b.widgets.destroy(a);
this.destroyed=true}},init:function(h){if(this.destroyed){a=b.widgets.initOn(h,"image",a.data);if(a.inline&&!(new CKEDITOR.dom.elementPath(a.wrapper,f)).block){h=e.createElement(b.activeEnterMode==CKEDITOR.ENTER_P?"p":"div");h.replace(a.wrapper);a.wrapper.move(h)}if(this.focused){a.focus();delete this.focused}delete this.destroyed}else{var h=a,i=h.wrapper,d=h.data.align;if(d=="center"){h.inline||i.setStyle("text-align","center");i.removeStyle("float")}else{h.inline||i.removeStyle("text-align");d==
"none"?i.removeStyle("float"):i.setStyle("float",d)}}}});a.parts.image.setAttributes({src:a.data.src,"data-cke-saved-src":a.data.src,alt:a.data.alt});b.filter.checkFeature(k.dimension)&&B(a);a.oldData=CKEDITOR.tools.extend({},a.data)},init:function(){var c=CKEDITOR.plugins.image2,b=this.parts.image,e={hasCaption:!!this.parts.caption,src:b.getAttribute("src"),alt:b.getAttribute("alt")||"",width:b.getAttribute("width")||"",height:b.getAttribute("height")||"",lock:this.ready?c.checkHasNaturalRatio(b):
!0};e.align||(e.align=this.element.getStyle("float")||b.getStyle("float")||"none",this.element.removeStyle("float"),b.removeStyle("float"));e.hasCaption||this.wrapper.setStyle("line-height","0");this.setData(e);a.filter.checkFeature(this.features.dimension)&&C(this);this.shiftState=c.stateShifter(this.editor);this.on("contextMenu",function(a){a.data.image=CKEDITOR.TRISTATE_OFF});this.on("dialog",function(a){a.data.widget=this},this)},upcast:D(a),downcast:E}}function D(a){var c=q(a);return function(a,
e){var f={width:1,height:1},g=a.name,d;if(!a.attributes["data-cke-realelement"]){if(c(a)){if("div"==g&&(d=a.getFirst("figure")))a.replaceWith(d),a=d;e.align="center";d=a.getFirst("img")}else"figure"==g&&a.hasClass("caption")?d=a.getFirst("img"):"img"==g&&(d=a);if(d){for(var k in f)(g=d.attributes[k])&&g.match(F)&&delete d.attributes[k];return a}}}}function E(a){var c=a.attributes,b=this.data.align;if(!this.inline){var e=a.getFirst("span"),f;e?(f=e.getFirst("img"),e.replaceWith(f)):a.getFirst("img")}b&&
"none"!=b&&(e=CKEDITOR.tools.parseCssText(c.style||""),"center"==b&&"figure"==a.name?a=a.wrapWith(new CKEDITOR.htmlParser.element("div",{style:"text-align:center"})):b in{left:1,right:1}&&(e["float"]=b),CKEDITOR.tools.isEmpty(e)||(c.style=CKEDITOR.tools.writeCssText(e)));return a}function q(a){return function(c){if(!(c.name in{div:1,p:1}))return!1;var b=c.children;if(1!==b.length)return!1;var b=b[0],e=b.name;if("figure"!=e&&"img"!=e)return!1;if("p"==c.name){if("img"!=e)return!1}else if("figure"==
e&&!b.hasClass("caption")||"img"==e&&a.enterMode==CKEDITOR.ENTER_P)return!1;return"center"==CKEDITOR.tools.parseCssText(c.attributes.style||"",!0)["text-align"]?!0:!1}}function B(a){var c=a.data,c={width:c.width,height:c.height},a=a.parts.image,b;for(b in c)c[b]?a.setAttribute(b,c[b]):a.removeAttribute(b)}function C(a){var c=a.editor,b=c.editable(),e=c.document,f=a.resizer=e.createElement("span");f.addClass("cke_image_resizer");f.setAttribute("title",c.lang.image2.resizer);f.append(new CKEDITOR.dom.text("​",
e));if(a.inline)a.wrapper.append(f);else{var g=a.element.getFirst(),d=e.createElement("span");d.addClass("cke_image_resizer_wrapper");d.append(a.parts.image);d.append(f);a.element.append(d,!0);g.is("span")&&g.remove()}f.on("mousedown",function(d){function h(a,b,c){var h=CKEDITOR.document,d=[];e.equals(h)||d.push(h.on(a,b));d.push(e.on(a,b));if(c)for(a=d.length;a--;)c.push(d.pop())}function i(){n=t+j*r;o=Math.round(n/p)}function m(){o=y-l;n=Math.round(o*p)}var g=a.parts.image,j="right"==a.data.align?
-1:1,q=d.data.$.screenX,u=d.data.$.screenY,t=g.$.clientWidth,y=g.$.clientHeight,p=t/y,w=[],z="cke_image_s"+(!~j?"w":"e"),x,n,o,v,r,l,s;c.fire("saveSnapshot");h("mousemove",function(a){x=a.data.$;r=x.screenX-q;l=u-x.screenY;s=Math.abs(r/l);1==j?0>=r?0>=l?i():s>=p?i():m():0>=l?s>=p?m():i():m():0>=r?0>=l?s>=p?m():i():m():0>=l?i():s>=p?i():m();15<=n&&15<=o?(g.setAttributes({width:n,height:o}),v=!0):v=!1},w);h("mouseup",function(){for(var h;h=w.pop();)h.removeListener();b.removeClass(z);f.removeClass("cke_image_resizing");
v&&(a.setData({width:n,height:o}),c.fire("saveSnapshot"));v=!1},w);b.addClass(z);f.addClass("cke_image_resizing")});a.on("data",function(){f["right"==a.data.align?"addClass":"removeClass"]("cke_image_resizer_left")})}function G(a){var c=[],b;return function(e){var f=a.getCommand("justify"+e);if(f){c.push(function(){f.refresh(a,a.elementPath())});if(e in{right:1,left:1,center:1})f.on("exec",function(b){var d=t(a);if(d){d.setData("align",e);for(d=c.length;d--;)c[d]();b.cancel()}});f.on("refresh",function(c){var d=
t(a),f={right:1,left:1,center:1};d&&(void 0==b&&(b=a.filter.checkFeature(a.widgets.registered.image.features.align)),b?this.setState(d.data.align==e?CKEDITOR.TRISTATE_ON:e in f?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED):this.setState(CKEDITOR.TRISTATE_DISABLED),c.cancel())})}}}function t(a){return(a=a.widgets.focused)&&"image"==a.name?a:null}var u='<img alt="" src="" />',H='<figure class="caption">'+u+"<figcaption>Caption</figcaption></figure>",F=/^\s*(\d+\%)\s*$/i;CKEDITOR.plugins.add("image2",
{lang:"af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,ug,uk,vi,zh,zh-cn",requires:"widget,dialog",icons:"image",hidpi:!0,onLoad:function(){CKEDITOR.addCss(".cke_editable.cke_image_sw, .cke_editable.cke_image_sw *{cursor:sw-resize !important}.cke_editable.cke_image_se, .cke_editable.cke_image_se *{cursor:se-resize !important}.cke_image_resizer{display:none;position:absolute;width:10px;height:10px;bottom:-5px;right:-5px;background:#000;outline:1px solid #fff;line-height:0;cursor:se-resize;}.cke_image_resizer_wrapper{position:relative;display:inline-block;line-height:0;}.cke_image_resizer.cke_image_resizer_left{right:auto;left:-5px;cursor:sw-resize;}.cke_widget_wrapper:hover .cke_image_resizer,.cke_image_resizer.cke_image_resizing{display:block}")},
init:function(a){var c=a.config,b=a.lang.image2,e=A(a);c.filebrowserImage2BrowseUrl=c.filebrowserImageBrowseUrl;c.filebrowserImage2UploadUrl=c.filebrowserImageUploadUrl;e.pathName=b.pathName;e.editables.caption.pathName=b.pathNameCaption;a.widgets.add("image",e);a.ui.addButton&&a.ui.addButton("Image",{label:a.lang.common.image,command:"image",toolbar:"insert,10"});a.contextMenu&&(a.addMenuGroup("image",10),a.addMenuItem("image",{label:b.menu,command:"image",group:"image"}));CKEDITOR.dialog.add("image2",
this.path+"dialogs/image2.js")},afterInit:function(a){var c={left:1,right:1,center:1,block:1},a=G(a),b;for(b in c)a(b)}});CKEDITOR.plugins.image2={stateShifter:function(a){function c(a,b){return a.oldState?a.oldState[b]!==a.newState[b]:!1}function b(a,b){var c=f.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div",{styles:{"text-align":"center"}});e(c,b);b.move(c);return c}function e(b,c){if(c.getParent()){var d=a.createRange();d.moveToPosition(c,CKEDITOR.POSITION_BEFORE_START);c.remove();
g.insertElementIntoRange(b,d)}else b.replace(c)}var f=a.document,g=a.editable(),d=["hasCaption","align"],k={align:function(d,e,f){var g=d.newState.hasCaption,j=d.element;if(c(d,"align")){if(!g&&("center"==f&&(d.destroy(),d.element=b(a,j)),!c(d,"hasCaption")&&"center"==e&&"center"!=f))d.destroy(),e=j.findOne("img"),e.replace(j),d.element=e}else"center"==f&&(c(d,"hasCaption")&&!g)&&(d.destroy(),d.element=b(a,j));j.is("figure")&&("center"==f?j.setStyle("display","inline-block"):j.removeStyle("display"))},
hasCaption:function(a,b,d){if(c(a,"hasCaption"))if(b=a.element,a.destroy(),d){var d=b.findOne("img")||b,g=CKEDITOR.dom.element.createFromHtml(H,f);e(g,b);d.replace(g.findOne("img"));a.element=g}else d=b.findOne("img"),d.replace(b),a.element=d}};return function(a){for(var b=a.oldState,c=a.newState,e,f=0;f<d.length;f++)e=d[f],k[e](a,b?b[e]:null,c[e]);a.init(a.element)}},checkHasNaturalRatio:function(a){var c=a.$,a=this.getNatural(a);return Math.round(c.clientWidth/a.width*a.height)==c.clientHeight||
Math.round(c.clientHeight/a.height*a.width)==c.clientWidth},getNatural:function(a){if(a.$.naturalWidth)a={width:a.$.naturalWidth,height:a.$.naturalHeight};else{var c=new Image;c.src=a.getAttribute("src");a={width:c.width,height:c.height}}return a}}})();