<?php return array(
    'root' => array(
        'pretty_version' => 'dev-develop',
        'version' => 'dev-develop',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'a2df2f2553a3f36892665f58c0e5a115a4d56038',
        'name' => '__root__',
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'a2df2f2553a3f36892665f58c0e5a115a4d56038',
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'sabre/dav' => array(
            'pretty_version' => '4.6.0',
            'version' => '4.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/dav',
            'aliases' => array(),
            'reference' => '554145304b4a026477d130928d16e626939b0b2a',
            'dev_requirement' => false,
        ),
        'sabre/event' => array(
            'pretty_version' => '5.1.4',
            'version' => '5.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/event',
            'aliases' => array(),
            'reference' => 'd7da22897125d34d7eddf7977758191c06a74497',
            'dev_requirement' => false,
        ),
        'sabre/http' => array(
            'pretty_version' => '5.1.10',
            'version' => '5.1.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/http',
            'aliases' => array(),
            'reference' => 'f9f3d1fba8916fa2f4ec25636c4fedc26cb94e02',
            'dev_requirement' => false,
        ),
        'sabre/uri' => array(
            'pretty_version' => '2.2.4',
            'version' => '2.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/uri',
            'aliases' => array(),
            'reference' => 'c0c9af9f7754e60a49ebd760e1708adc6d1510c0',
            'dev_requirement' => false,
        ),
        'sabre/vobject' => array(
            'pretty_version' => '4.5.4',
            'version' => '4.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/vobject',
            'aliases' => array(),
            'reference' => 'a6d53a3e5bec85ed3dd78868b7de0f5b4e12f772',
            'dev_requirement' => false,
        ),
        'sabre/xml' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/xml',
            'aliases' => array(),
            'reference' => '9cde7cdab1e50893cc83b037b40cd47bfde42a2b',
            'dev_requirement' => false,
        ),
    ),
);
