source 'https://rubygems.org'

group :rake do
  gem 'puppetlabs_spec_helper'
  gem 'librarian-puppet-maestrodev'
  gem 'open3_backport', :platforms => :ruby_18
  gem 'json',           :platforms => :ruby_18
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end
