require 'puppetlabs_spec_helper/rake_tasks'

# use librarian-puppet to manage fixtures instead of .fixtures.yml
# offers more possibilities like explicit version management, forge downloads,...
task :librarian_spec_prep do
  sh "librarian-puppet install --path=$PWD/spec/fixtures/modules/"
end
task :spec_prep => :librarian_spec_prep
