<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once $pathdepth ? str_repeat('../', $pathdepth) : './'.'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>My personal blog</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="My personal blog" />
<meta name="title" content="My personal blog" />
<meta name="description" content="Home page or my personal Blog" />
<meta name="generator" content="Dolibarr 16.0.0-alpha (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="23" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script async src="/javascript.js.php"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-home">
<!-- Wrapper -->
<div id="wrapper">

	<!-- Header -->
		<header id="header">
			<section id="sectionheader" contenteditable="true">
			<h1>David Doe</h1>
			<p>Welcome on my website<br>
			</p>
			</section>
		</header>

	<!-- Nav -->
	<?php includeContainer('menu'); ?>

	<!-- Main -->
		<div id="main">

			<!-- Introduction -->
				<section id="sectionintro" class="main" contenteditable="true">
					<div class="spotlight">
						<div class="content">
							<header class="major">
								<h2>Ipsum sed adipiscing</h2>
							</header>
							<p>Sed lorem ipsum dolor sit amet nullam consequat feugiat consequat magna
							adipiscing magna etiam amet veroeros. Lorem ipsum dolor tempus sit cursus.
							Tempus nisl et nullam lorem ipsum dolor sit amet aliquam.</p>
							<ul class="actions">
								<li><a href="generic.php" class="buttonwebsite">Learn More</a></li>
							</ul>
						</div>
						<span class="image"><img class="logowebsite" src="medias/image/template-stellar/daviddoe.png" alt="" /></span>
					</div>
				</section>

			<!-- First Section -->
				<section id="sectionfirst" id="first" class="main special" contenteditable="true">
					<header class="major">
						<h2>Magna veroeros</h2>
					</header>
					<ul class="features">
						<li>
							<span class="icon solid major style1 fa-code"><!-- keep this comment --></span>
							<h3>Ipsum consequat</h3>
							<p>Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat.</p>
						</li>
						<li>
							<span class="icon major style3 fa-copy"><!-- keep this comment  --></span>
							<h3>Amed sed feugiat</h3>
							<p>Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat.</p>
						</li>
						<li>
							<span class="icon major style5 fa-at"><!-- keep this comment  --></span>
							<h3>Dolor nullam</h3>
							<p>Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat.</p>
						</li>
					</ul>
					<footer class="major">
						<ul class="actions special">
							<li><a href="generic.php" class="buttonwebsite">Learn More</a></li>
						</ul>
					</footer>
				</section>

			<!-- Second Section -->
				<section id="sectionsecond" class="main special" contenteditable="true">
					<header class="major">
						<h2>Ipsum consequat</h2>
						<p>Donec imperdiet consequat consequat. Suspendisse feugiat congue<br>
						posuere. Nulla massa urna, fermentum eget quam aliquet.</p>
					</header>
					<ul class="statistics">
						<li class="style1">
							<span class="icon solid fa-code-branch"><!-- keep this comment  --></span>
							<strong>5,120</strong> Etiam
						</li>
						<li class="style2">
							<span class="icon fa-folder-open"><!-- keep this comment  --></span>
							<strong>8,192</strong> Magna
						</li>
						<li class="style3">
							<span class="icon solid fa-signal"><!-- keep this comment  --></span>
							<strong>2,048</strong> Tempus
						</li>
						<li class="style4">
							<span class="icon solid fa-laptop"><!-- keep this comment  --></span>
							<strong>4,096</strong> Aliquam
						</li>
						<li class="style5">
							<span class="icon fa-gem"><!-- keep this comment  --></span>
							<strong>1,024</strong> Nullam
						</li>
					</ul>
					<p class="content">Nam elementum nisl et mi a commodo porttitor. Morbi sit amet nisl eu arcu faucibus hendrerit vel a risus. Nam a orci mi, elementum ac arcu sit amet, fermentum pellentesque et purus. Integer maximus varius lorem, sed convallis diam accumsan sed. Etiam porttitor placerat sapien, sed eleifend a enim pulvinar faucibus semper quis ut arcu. Ut non nisl a mollis est efficitur vestibulum. Integer eget purus nec nulla mattis et accumsan ut magna libero. Morbi auctor iaculis porttitor. Sed ut magna ac risus et hendrerit scelerisque. Praesent eleifend lacus in lectus aliquam porta. Cras eu ornare dui curabitur lacinia.</p>
					<footer class="major">
						<ul class="actions special">
							<li><a href="generic.php" class="buttonwebsite">Learn More</a></li>
						</ul>
					</footer>
				</section>

			<!-- Get Started -->
				<section id="sectioncta" class="main special" contenteditable="true">
					<header class="major">
						<h2>Congue imperdiet</h2>
						<p>Donec imperdiet consequat consequat. Suspendisse feugiat congue<br>
						posuere. Nulla massa urna, fermentum eget quam aliquet.</p>
					</header>
					<footer class="major">
						<ul class="actions special">
							<li><a href="generic.php" class="buttonwebsite primary">Get Started</a></li>
							<li><a href="generic.php" class="buttonwebsite">Learn More</a></li>
						</ul>
					</footer>
				</section>

		</div>

	<?php includeContainer('footer'); ?>

</div>


</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 23);
// END PHP ?>
