dolibarr: Societe Class Reference
Societe Class Reference
Class to manage third parties objects (customers, suppliers, prospects...)
Public Member Functions
__construct ($db)
Constructor.
create (User $user)
Create third party in database.
create_individual (User $user, $no_email=0, $tags=array())
Create a contact/address from thirdparty.
verify ()
Check properties of third party are ok (like name, third party codes, ...) Used before an add or update.
update ($id, $user='', $call_trigger=1, $allowmodcodeclient=0, $allowmodcodefournisseur=0, $action='update', $nosyncmember=1)
Update parameters of third party.
fetch ($rowid, $ref='', $ref_ext='', $barcode='', $idprof1='', $idprof2='', $idprof3='', $idprof4='', $idprof5='', $idprof6='', $email='', $ref_alias='')
Load a third party from database into memory.
delete ($id, User $fuser=null, $call_trigger=1)
Delete a third party from database and all its dependencies (contacts, rib...)
set_as_client ()
Define third party as a customer.
set_remise_client ($remise, $note, User $user)
Defines the company as a customer.
set_remise_supplier ($remise, $note, User $user)
Defines the company as a customer.
set_remise_except ($remise, User $user, $desc, $vatrate='', $discount_type=0, $price_base_type='HT')
Add a discount for third party.
getAvailableDiscounts ($user='', $filter='', $maxvalue=0, $discount_type=0)
Returns amount of included taxes of the current discounts/credits available from the company.
getSalesRepresentatives (User $user, $mode=0, $sortfield=null, $sortorder=null)
Return array of sales representatives.
setPriceLevel ($price_level, User $user)
Set the price level.
add_commercial (User $user, $commid)
Add link to sales representative.
del_commercial (User $user, $commid)
Add link to sales representative.
getNomUrl ($withpicto=0, $option='', $maxlen=0, $notooltip=0, $save_lastsearch_value=-1, $noaliasinname=0, $target='')
Return a link on thirdparty (with picto)
getTypeUrl ($withpicto=0, $option='', $notooltip=0, $tag='a')
Return link(s) on type of thirdparty (with picto)
getLibStatut ($mode=0)
Return label of status (activity, closed)
LibStatut ($status, $mode=0)
Return the label of a given status.
thirdparty_and_contact_email_array ($addthirdparty=0)
Return list of contacts emails existing for third party.
thirdparty_and_contact_phone_array ()
Return list of contacts mobile phone existing for third party.
contact_property_array ($mode='email', $hidedisabled=0)
Return list of contacts emails or mobile existing for third party.
contact_array ()
Returns the contact list of this company.
contact_array_objects ()
Returns the contact list of this company.
contact_get_property ($rowid, $mode)
Return property of contact from its id.
display_rib ($mode='label')
Return bank number property of thirdparty (label or rum)
get_all_rib ()
Return Array of RIB.
get_codeclient ($objsoc=0, $type=0)
Assigns a customer code from the code control module.
get_codefournisseur ($objsoc=0, $type=1)
Assigns a vendor code from the code control module.
codeclient_modifiable ()
Check if a client code is editable based on the parameters of the code control module.
codefournisseur_modifiable ()
Check if a vendor code is editable in the code control module configuration.
check_codeclient ()
Check customer code.
check_codefournisseur ()
Check supplier code.
get_codecompta ($type)
Assigns a accounting code from the accounting code module.
setParent ($id)
Define parent company of current company.
validateFamilyTree ($idparent, $idchild, $counter=0)
Check if a thirdparty $idchild is or not inside the parents (or grand parents) of another thirdparty id $idparent.
getParentsForCompany ($company_id, $parents=[])
Get parents for company.
id_prof_verifiable ($idprof)
Returns if a profid sould be verified to be unique.
id_prof_exists ($idprof, $value, $socid=0)
Verify if a profid exists into database for others thirds.
id_prof_check ($idprof, $soc)
Check the validity of a professional identifier according to the country of the company (siren, siret, ...)
id_prof_url ($idprof, $thirdparty)
Return an url to check online a professional id or empty string.
has_projects ()
Indicates if the company has projects.
info ($id)
Load information for tab info.
isACompany ()
Return if third party is a company (Business) or an end user (Consumer)
isInEEC ()
Return if a company is inside the EEC (European Economic Community)
LoadSupplierCateg ()
Load the list of provider categories.
AddFournisseurInCategory ($categorie_id)
Insert link supplier - category.
getNbOfEMailings ()
Return number of mass Emailing received by this contacts with its email.
setNoEmail ($no_email)
Set "blacklist" mailing status.
getNoEmail ()
get "blacklist" mailing status set no_email attribut to 1 or 0
create_from_member (Adherent $member, $socname='', $socalias='', $customercode='')
Create a third party into database from a member object.
setMysoc (Conf $conf)
Set properties with value into $conf.
initAsSpecimen ()
Initialise an instance with random values.
useLocalTax ($localTaxNum=0)
Check if we must use localtax feature or not according to country (country of $mysoc in most cases).
useNPR ()
Check if we must use NPR Vat (french stupid rule) or not according to country (country of $mysoc in most cases).
useRevenueStamp ()
Check if we must use revenue stamps feature or not according to country (country of $mysocin most cases).
getLibProspLevel ()
Return prostect level.
LibProspLevel ($fk_prospectlevel)
Return label of prospect level.
getLibProspCommStatut ($mode=0, $label='')
Return status of prospect.
LibProspCommStatut ($status, $mode=0, $label='', $picto='')
Return label of a given status.
getOutstandingProposals ($mode='customer')
Return amount of proposal not yet paid and total an dlist of all proposals.
getOutstandingOrders ($mode='customer')
Return amount of order not yet paid and total and list of all orders.
getOutstandingBills ($mode='customer', $late=0)
Return amount of bill not yet paid and total of all invoices.
getLibCustProspStatut ()
Return label of status customer is prospect/customer.
LibCustProspStatut ($status)
Return the label of the customer/prospect status.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
setCategories ($categories, $type_categ)
Sets object to supplied categories.
setSalesRep ($salesrep, $onlyAdd=false)
Sets sales representatives of the thirdparty.
setThirdpartyType ($typent_id)
Define third-party type of current company.
setAccountancyCode ($type, $value)
Sets an accountancy code for a thirdparty.
fetchPartnerships ($mode)
Function to get partnerships array.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
const NO_CUSTOMER = 0
Third party type is no customer.
const CUSTOMER = 1
Third party type is a customer.
const PROSPECT = 2
Third party type is a prospect.
const CUSTOMER_AND_PROSPECT = 3
Third party type is a customer and a prospect.
const NO_SUPPLIER = 0
Third party supplier flag is not supplier.
const SUPPLIER = 1
Third party supplier flag is a supplier.
Public Attributes inherited from CommonObject
$projet
$fk_projet
$note
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage third parties objects (customers, suppliers, prospects...)
Definition at line 49 of file societe.class.php.
Constructor & Destructor Documentation
__construct()
Societe::__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Reimplemented in Client, and Fournisseur.
Definition at line 839 of file societe.class.php.
Member Function Documentation
add_commercial()
Societe::add_commercial (User $user, $commid)
Add link to sales representative.
Parameters
User $user Object user
int $commid Id of user
Returns
int <=0 if KO, >0 if OK
Definition at line 2492 of file societe.class.php.
References db.
AddFournisseurInCategory()
Societe::AddFournisseurInCategory ($categorie_id)
Insert link supplier - category.
Parameters
int $categorie_id Id of category
Returns
int 0 if success, <> 0 if error
Definition at line 4018 of file societe.class.php.
check_codeclient()
Societe::check_codeclient ()
Check customer code.
Returns
int 0 if OK -1 ErrorBadCustomerCodeSyntax -2 ErrorCustomerCodeRequired -3 ErrorCustomerCodeAlreadyUsed -4 ErrorPrefixRequired -5 NotConfigured - Setup empty so any value may be ok or not -6 Other (see this->error)
Definition at line 3319 of file societe.class.php.
check_codefournisseur()
Societe::check_codefournisseur ()
Check supplier code.
Returns
int 0 if OK -1 ErrorBadCustomerCodeSyntax -2 ErrorCustomerCodeRequired -3 ErrorCustomerCodeAlreadyUsed -4 ErrorPrefixRequired -5 NotConfigured - Setup empty so any value may be ok or not -6 Other (see this->error)
Definition at line 3360 of file societe.class.php.
codeclient_modifiable()
Societe::codeclient_modifiable ()
Check if a client code is editable based on the parameters of the code control module.
Returns
int 0=No, 1=Yes
Definition at line 3233 of file societe.class.php.
codefournisseur_modifiable()
Societe::codefournisseur_modifiable ()
Check if a vendor code is editable in the code control module configuration.
Returns
int 0=No, 1=Yes
Definition at line 3273 of file societe.class.php.
contact_array()
Societe::contact_array ()
Returns the contact list of this company.
Returns
array array of contacts
Definition at line 3001 of file societe.class.php.
contact_array_objects()
Societe::contact_array_objects ()
Returns the contact list of this company.
Returns
array $contacts array of contacts
Definition at line 3030 of file societe.class.php.
contact_get_property()
Societe::contact_get_property ($rowid, $mode)
Return property of contact from its id.
Parameters
int $rowid id of contact
string $mode 'email' or 'mobile'
Returns
string Email of contact with format: "Full name <email>"
Definition at line 3064 of file societe.class.php.
contact_property_array()
Societe::contact_property_array ($mode = 'email', $hidedisabled = 0)
Return list of contacts emails or mobile existing for third party.
Parameters
string $mode 'email' or 'mobile'
int $hidedisabled 1=Hide contact if disabled
Returns
array Array of contacts emails or mobile. Example: array(id=>'Name <email>')
Definition at line 2936 of file societe.class.php.
create()
Societe::create (User $user)
Create third party in database.
$this->code_client = -1 and $this->code_fournisseur = -1 means automatic assignement.
Parameters
User $user Object of user that ask creation
Returns
int >=0 if OK, <0 if KO
Definition at line 870 of file societe.class.php.
create_from_member()
Societe::create_from_member (Adherent $member, $socname = '', $socalias = '', $customercode = '')
Create a third party into database from a member object.
Parameters
Adherent $member Object member
string $socname Name of third party to force
string $socalias Alias name of third party to force
string $customercode Customer code
Returns
int <0 if KO, id of created account if OK
Definition at line 4150 of file societe.class.php.
create_individual()
Societe::create_individual (User $user, $no_email = 0, $tags = array())
Create a contact/address from thirdparty.
Parameters
User $user Object user
int $no_email 1=Do not send mailing, 0=Ok to recieve mailling
array $tags Array of tag to affect to contact
Returns
int <0 if KO, >0 if OK
Definition at line 1052 of file societe.class.php.
del_commercial()
Societe::del_commercial (User $user, $commid)
Add link to sales representative.
Parameters
User $user Object user
int $commid Id of user
Returns
void
Definition at line 2552 of file societe.class.php.
delete()
Societe::delete ($id, User $fuser = null, $call_trigger = 1)
Delete a third party from database and all its dependencies (contacts, rib...)
Parameters
int $id Id of third party to delete
User $fuser User who ask to delete thirdparty
int $call_trigger 0=No, 1=yes
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 1991 of file societe.class.php.
display_rib()
Societe::display_rib ($mode = 'label')
Return bank number property of thirdparty (label or rum)
Parameters
string $mode 'label' or 'rum' or 'format'
Returns
string Bank label or RUM or '' if no bank account found
Definition at line 3104 of file societe.class.php.
fetch()
Societe::fetch ($rowid, $ref = '', $ref_ext = '', $barcode = '', $idprof1 = '', $idprof2 = '', $idprof3 = '', $idprof4 = '', $idprof5 = '', $idprof6 = '', $email = '', $ref_alias = '')
Load a third party from database into memory.
Parameters
int $rowid Id of third party to load
string $ref Reference of third party, name (Warning, this can return several records)
string $ref_ext External reference of third party (Warning, this information is a free field not provided by Dolibarr)
string $barcode Barcode of third party to load
string $idprof1 Prof id 1 of third party (Warning, this can return several records)
string $idprof2 Prof id 2 of third party (Warning, this can return several records)
string $idprof3 Prof id 3 of third party (Warning, this can return several records)
string $idprof4 Prof id 4 of third party (Warning, this can return several records)
string $idprof5 Prof id 5 of third party (Warning, this can return several records)
string $idprof6 Prof id 6 of third party (Warning, this can return several records)
string $email Email of third party (Warning, this can return several records)
string $ref_alias Name_alias of third party (Warning, this can return several records)
Returns
int >0 if OK, <0 if KO or if two records found for same ref or idprof, 0 if not found.
Definition at line 1703 of file societe.class.php.
fetchPartnerships()
Societe::fetchPartnerships ($mode)
Function to get partnerships array.
Parameters
string $mode 'member' or 'thirdparty'
Returns
int <0 if KO, >0 if OK
Definition at line 5084 of file societe.class.php.
generateDocument()
Societe::generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Generator to use. Caller must set it to obj->model_pdf or GETPOST('model','alpha') for example.
Translate $outputlangs objet lang a utiliser pour traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int <0 if KO, >0 if OK
Definition at line 4836 of file societe.class.php.
get_all_rib()
Societe::get_all_rib ()
Return Array of RIB.
Returns
array|int 0 if KO, Array of CompanyBanckAccount if OK
Definition at line 3139 of file societe.class.php.
get_codeclient()
Societe::get_codeclient ($objsoc = 0, $type = 0)
Assigns a customer code from the code control module.
Return value is stored into this->code_client
Parameters
Societe $objsoc Object thirdparty
int $type Should be 0 to say customer
Returns
void
Definition at line 3172 of file societe.class.php.
get_codecompta()
Societe::get_codecompta ($type)
Assigns a accounting code from the accounting code module.
Computed value is stored into this->code_compta or this->code_compta_fournisseur according to $type. May be identical to the one entered or generated automatically. Currently, only the automatic generation is implemented.
Parameters
string $type Type of thirdparty ('customer' or 'supplier')
Returns
int 0 if OK, <0 if $type is not valid
Definition at line 3398 of file societe.class.php.
get_codefournisseur()
Societe::get_codefournisseur ($objsoc = 0, $type = 1)
Assigns a vendor code from the code control module.
Return value is stored into this->code_fournisseur
Parameters
Societe $objsoc Object thirdparty
int $type Should be 1 to say supplier
Returns
void
Definition at line 3204 of file societe.class.php.
getAvailableDiscounts()
Societe::getAvailableDiscounts ($user = '', $filter = '', $maxvalue = 0, $discount_type = 0)
Returns amount of included taxes of the current discounts/credits available from the company.
Parameters
User $user Filter on a user author of discounts
string $filter Other filter
integer $maxvalue Filter on max value for discount
int $discount_type 0 => customer discount, 1 => supplier discount
Returns
int <0 if KO, Credit note amount otherwise
Definition at line 2366 of file societe.class.php.
getLibCustProspStatut()
Societe::getLibCustProspStatut ()
Return label of status customer is prospect/customer.
Returns
string Label
See also
getTypeUrl()
Definition at line 4795 of file societe.class.php.
References LibCustProspStatut().
getLibProspCommStatut()
Societe::getLibProspCommStatut ($mode = 0, $label = '')
Return status of prospect.
Parameters
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long
string $label Label to use for status for added status
Returns
string Libelle
Definition at line 4538 of file societe.class.php.
getLibProspLevel()
Societe::getLibProspLevel ()
Return prostect level.
Returns
string Libelle
Definition at line 4506 of file societe.class.php.
References LibProspLevel().
getLibStatut()
Societe::getLibStatut ($mode = 0)
Return label of status (activity, closed)
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label of status
Definition at line 2848 of file societe.class.php.
getNbOfEMailings()
Societe::getNbOfEMailings ()
Return number of mass Emailing received by this contacts with its email.
Returns
int Number of EMailings
Definition at line 4039 of file societe.class.php.
getNoEmail()
Societe::getNoEmail ()
get "blacklist" mailing status set no_email attribut to 1 or 0
Returns
int <0 if KO, >0 if OK
Definition at line 4122 of file societe.class.php.
getNomUrl()
Societe::getNomUrl ($withpicto = 0, $option = '', $maxlen = 0, $notooltip = 0, $save_lastsearch_value = -1, $noaliasinname = 0, $target = '')
Return a link on thirdparty (with picto)
Parameters
int $withpicto Add picto into link (0=No picto, 1=Include picto with link, 2=Picto only)
string $option Target of link ('', 'customer', 'prospect', 'supplier', 'project')
int $maxlen Max length of name
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
int $noaliasinname 1=Do not add alias into the link ref
string $target add attribute target
Returns
string String with URL
Definition at line 2586 of file societe.class.php.
getOutstandingBills()
Societe::getOutstandingBills ($mode = 'customer', $late = 0)
Return amount of bill not yet paid and total of all invoices.
Parameters
string $mode 'customer' or 'supplier'
int $late 0 => all invoice, 1=> only late
Returns
array array('opened'=>Amount including tax that remains to pay, 'total_ht'=>Total amount without tax of all objects paid or not, 'total_ttc'=>Total amunt including tax of all object paid or not)
Definition at line 4704 of file societe.class.php.
getOutstandingOrders()
Societe::getOutstandingOrders ($mode = 'customer')
Return amount of order not yet paid and total and list of all orders.
Parameters
string $mode 'customer' or 'supplier'
Returns
array array('opened'=>Amount including tax that remains to pay, 'total_ht'=>Total amount without tax of all objects paid or not, 'total_ttc'=>Total amunt including tax of all object paid or not)
Definition at line 4660 of file societe.class.php.
getOutstandingProposals()
Societe::getOutstandingProposals ($mode = 'customer')
Return amount of proposal not yet paid and total an dlist of all proposals.
Parameters
string $mode 'customer' or 'supplier'
Returns
array array('opened'=>Amount including tax that remains to pay, 'total_ht'=>Total amount without tax of all objects paid or not, 'total_ttc'=>Total amunt including tax of all object paid or not)
Definition at line 4616 of file societe.class.php.
getParentsForCompany()
Societe::getParentsForCompany ($company_id, $parents = [])
Get parents for company.
Parameters
int $company_id ID of company to search parent
array $parents List of companies ID found
Returns
array
Definition at line 3522 of file societe.class.php.
getSalesRepresentatives()
Societe::getSalesRepresentatives (User $user, $mode = 0, $sortfield = null, $sortorder = null)
Return array of sales representatives.
Parameters
User $user Object user (not used)
int $mode 0=Array with properties, 1=Array of id.
string $sortfield List of sort fields, separated by comma. Example: 't1.fielda,t2.fieldb'
string $sortorder Sort order, separated by comma. Example: 'ASC,DESC';
Returns
array Array of sales representatives of third party
Definition at line 2389 of file societe.class.php.
getTypeUrl()
Societe::getTypeUrl ($withpicto = 0, $option = '', $notooltip = 0, $tag = 'a')
Return link(s) on type of thirdparty (with picto)
Parameters
int $withpicto Add picto into link (0=No picto, 1=Include picto with link, 2=Picto only)
string $option ''=All
int $notooltip 1=Disable tooltip
string $tag Tag 'a' or 'span'
Returns
string String with URL
Definition at line 2818 of file societe.class.php.
has_projects()
Societe::has_projects ()
Indicates if the company has projects.
Returns
bool true if the company has projects, false otherwise
Definition at line 3897 of file societe.class.php.
id_prof_check()
Societe::id_prof_check ($idprof, $soc)
Check the validity of a professional identifier according to the country of the company (siren, siret, ...)
Parameters
int $idprof 1,2,3,4 (Exemple: 1=siren,2=siret,3=naf,4=rcs/rm)
Societe $soc Objet societe
Returns
int <=0 if KO, >0 if OK TODO better to have this in a lib than into a business class
Definition at line 3654 of file societe.class.php.
id_prof_exists()
Societe::id_prof_exists ($idprof, $value, $socid = 0)
Verify if a profid exists into database for others thirds.
Parameters
string $idprof 'idprof1','idprof2','idprof3','idprof4','idprof5','idprof6','email' (Example: idprof1=siren, idprof2=siret, idprof3=naf, idprof4=rcs/rm)
string $value Value of profid
int $socid Id of thirdparty to exclude (if update)
Returns
boolean True if exists, False if not
Definition at line 3593 of file societe.class.php.
id_prof_url()
Societe::id_prof_url ($idprof, $thirdparty)
Return an url to check online a professional id or empty string.
Parameters
int $idprof 1,2,3,4 (Example: 1=siren,2=siret,3=naf,4=rcs/rm)
Societe $thirdparty Object thirdparty
Returns
string Url or empty string if no URL known TODO better in a lib than into business class
Definition at line 3844 of file societe.class.php.
id_prof_verifiable()
Societe::id_prof_verifiable ($idprof)
Returns if a profid sould be verified to be unique.
Parameters
int $idprof 1,2,3,4,5,6 (Example: 1=siren, 2=siret, 3=naf, 4=rcs/rm, 5=eori, 6=idprof6)
Returns
boolean true if the ID must be unique
Definition at line 3553 of file societe.class.php.
info()
Societe::info ($id)
Load information for tab info.
Parameters
int $id Id of thirdparty to load
Returns
void
Definition at line 3920 of file societe.class.php.
initAsSpecimen()
Societe::initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
int >0 if ok
Definition at line 4377 of file societe.class.php.
isACompany()
Societe::isACompany ()
Return if third party is a company (Business) or an end user (Consumer)
Returns
boolean true=is a company, false=a and user
Definition at line 3953 of file societe.class.php.
isInEEC()
Societe::isInEEC ()
Return if a company is inside the EEC (European Economic Community)
Returns
boolean true = country inside EEC, false = country outside EEC
Definition at line 3980 of file societe.class.php.
LibCustProspStatut()
Societe::LibCustProspStatut ($status)
Return the label of the customer/prospect status.
Parameters
int $status Id of prospection status
Returns
string Label of prospection status
Definition at line 4807 of file societe.class.php.
Referenced by getLibCustProspStatut().
LibProspCommStatut()
Societe::LibProspCommStatut ($status, $mode = 0, $label = '', $picto = '')
Return label of a given status.
Parameters
int | string $status Id or code for prospection status
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
string $label Label to use for status for added status
string $picto Name of image file to show ('filenew', ...) If no extension provided, we use '.png'. Image must be stored into theme/xxx/img directory. Example: picto.png if picto.png is stored into htdocs/theme/mytheme/img Example: picto.png@mymodule if picto.png is stored into htdocs/mymodule/img Example: /mydir/mysubdir/picto.png if picto.png is stored into htdocs/mydir/mysubdir (pictoisfullpath must be set to 1)
Returns
string Label of prospection status
Definition at line 4557 of file societe.class.php.
LibProspLevel()
Societe::LibProspLevel ($fk_prospectlevel)
Return label of prospect level.
Parameters
int $fk_prospectlevel Prospect level
Returns
string label of level
Definition at line 4518 of file societe.class.php.
Referenced by getLibProspLevel().
LibStatut()
Societe::LibStatut ($status, $mode = 0)
Return the label of a given status.
Parameters
int $status Status id
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Status label
Definition at line 2861 of file societe.class.php.
LoadSupplierCateg()
Societe::LoadSupplierCateg ()
Load the list of provider categories.
Returns
int 0 if success, <> 0 if error
Definition at line 3992 of file societe.class.php.
replaceThirdparty()
static Societe::replaceThirdparty (DoliDB $dbs, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
It must be used within a transaction to avoid trouble
Parameters
DoliDB $dbs Database handler, because function is static we name it $dbs not $db to avoid breaking coding test
int $origin_id Old thirdparty id (will be removed)
int $dest_id New thirdparty id
Returns
bool True if success, False if error
Thirdparty commercials cannot be the same in both thirdparties so we look for them and remove some to avoid duplicate. Because this function is meant to be executed within a transaction, we won't take care of begin/commit.
llx_societe_extrafields table must not be here because we don't care about the old thirdparty data Do not include llx_societe because it will be replaced later
Reimplemented in Fournisseur.
Definition at line 4987 of file societe.class.php.
References dol_syslog().
set_as_client()
Societe::set_as_client ()
Define third party as a customer.
Returns
int <0 if KO, >0 if OK
Definition at line 2142 of file societe.class.php.
set_remise_client()
Societe::set_remise_client ($remise, $note, User $user)
Defines the company as a customer.
Parameters
float $remise Value in % of the discount
string $note Note/Reason for changing the discount
User $user User who sets the discount
Returns
int <0 if KO, >0 if OK
Definition at line 2174 of file societe.class.php.
set_remise_except()
Societe::set_remise_except ($remise, User $user, $desc, $vatrate = '', $discount_type = 0, $price_base_type = 'HT')
Add a discount for third party.
Parameters
float $remise Amount of discount
User $user User adding discount
string $desc Reason of discount
string $vatrate VAT rate (may contain the vat code too). Exemple: '1.23', '1.23 (ABC)', ...
int $discount_type 0 => customer discount, 1 => supplier discount
string $price_base_type Price base type 'HT' or 'TTC'
Returns
int <0 if KO, id of discount record if OK
Definition at line 2295 of file societe.class.php.
set_remise_supplier()
Societe::set_remise_supplier ($remise, $note, User $user)
Defines the company as a customer.
Parameters
float $remise Value in % of the discount
string $note Note/Reason for changing the discount
User $user User who sets the discount
Returns
int <0 if KO, >0 if OK
Definition at line 2233 of file societe.class.php.
setAccountancyCode()
Societe::setAccountancyCode ($type, $value)
Sets an accountancy code for a thirdparty.
Also calls COMPANY_MODIFY trigger when modified
Parameters
string $type It can be only 'buy' or 'sell'
string $value Accountancy code
Returns
int <0 KO >0 OK
Definition at line 5033 of file societe.class.php.
setCategories()
Societe::setCategories ($categories, $type_categ)
Sets object to supplied categories.
Deletes object from existing categories not supplied. Adds it to non existing supplied categories. Existing categories are left untouch.
Parameters
int[] | int $categories Category ID or array of Categories IDs
string $type_categ Category type ('customer' or 'supplier')
Returns
int <0 if KO, >0 if OK
Definition at line 4892 of file societe.class.php.
setMysoc()
Societe::setMysoc (Conf $conf)
Set properties with value into $conf.
Parameters
Conf $conf Conf object (possibility to use another entity)
Returns
void
Definition at line 4249 of file societe.class.php.
setNoEmail()
Societe::setNoEmail ($no_email)
Set "blacklist" mailing status.
Parameters
int $no_email 1=Do not send mailing, 0=Ok to recieve mailling
Returns
int <0 if KO, >0 if OK
Definition at line 4065 of file societe.class.php.
setParent()
Societe::setParent ($id)
Define parent company of current company.
Parameters
int $id Id of thirdparty to set or '' to remove
Returns
int <0 if KO, >0 if OK
Definition at line 3450 of file societe.class.php.
References dol_syslog(), setEventMessages(), and validateFamilyTree().
setPriceLevel()
Societe::setPriceLevel ($price_level, User $user)
Set the price level.
Parameters
int $price_level Level of price
User $user Use making change
Returns
int <0 if KO, >0 if OK
Definition at line 2457 of file societe.class.php.
setSalesRep()
Societe::setSalesRep ($salesrep, $onlyAdd = false)
Sets sales representatives of the thirdparty.
Parameters
int[] | int $salesrep User ID or array of user IDs
bool $onlyAdd Only add (no delete before)
Returns
int <0 if KO, >0 if OK
Definition at line 4912 of file societe.class.php.
setThirdpartyType()
Societe::setThirdpartyType ($typent_id)
Define third-party type of current company.
Parameters
int $typent_id third party type rowid in llx_c_typent
Returns
int <0 if KO, >0 if OK
Definition at line 4957 of file societe.class.php.
thirdparty_and_contact_email_array()
Societe::thirdparty_and_contact_email_array ($addthirdparty = 0)
Return list of contacts emails existing for third party.
Parameters
int $addthirdparty 1=Add also a record for thirdparty email
Returns
array Array of contacts emails
Definition at line 2889 of file societe.class.php.
thirdparty_and_contact_phone_array()
Societe::thirdparty_and_contact_phone_array ()
Return list of contacts mobile phone existing for third party.
Returns
array Array of contacts emails
Definition at line 2911 of file societe.class.php.
update()
Societe::update ($id, $user = '', $call_trigger = 1, $allowmodcodeclient = 0, $allowmodcodefournisseur = 0, $action = 'update', $nosyncmember = 1)
Update parameters of third party.
Parameters
int $id Id of company (deprecated, use 0 here and call update on an object loaded by a fetch)
User $user User who requests the update
int $call_trigger 0=no, 1=yes
int $allowmodcodeclient Inclut modif code client et code compta
int $allowmodcodefournisseur Inclut modif code fournisseur et code compta fournisseur
string $action 'add' or 'update' or 'merge'
int $nosyncmember Do not synchronize info of linked member
Returns
int <0 if KO, >=0 if OK
Definition at line 1255 of file societe.class.php.
useLocalTax()
Societe::useLocalTax ($localTaxNum = 0)
Check if we must use localtax feature or not according to country (country of $mysoc in most cases).
Parameters
int $localTaxNum To get info for only localtax1 or localtax2
Returns
boolean true or false
Definition at line 4434 of file societe.class.php.
useNPR()
Societe::useNPR ()
Check if we must use NPR Vat (french stupid rule) or not according to country (country of $mysoc in most cases).
Returns
boolean true or false
Definition at line 4461 of file societe.class.php.
useRevenueStamp()
Societe::useRevenueStamp ()
Check if we must use revenue stamps feature or not according to country (country of $mysocin most cases).
Table c_revenuestamp contains the country and value of stamp per invoice.
Returns
boolean true or false
Definition at line 4483 of file societe.class.php.
validateFamilyTree()
Societe::validateFamilyTree ($idparent, $idchild, $counter = 0)
Check if a thirdparty $idchild is or not inside the parents (or grand parents) of another thirdparty id $idparent.
Parameters
int $idparent Id of thirdparty to check
int $idchild Id of thirdparty to compare to
int $counter Counter to protect against infinite loops
Returns
int <0 if KO, 0 if OK or 1 if at some level a parent company was the child to compare to
Definition at line 3489 of file societe.class.php.
Referenced by setParent().
verify()
Societe::verify ()
Check properties of third party are ok (like name, third party codes, ...) Used before an add or update.
Returns
int 0 if OK, <0 if KO
Definition at line 1125 of file societe.class.php.
The documentation for this class was generated from the following file:
htdocs/societe/class/societe.class.php