<?php
/* Copyright (C) 2007-2011 Laurent Destailleur  <eldy@users.sourceforge.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * or see http://www.gnu.org/
 */

/**
 *		\file       htdocs/core/modules/security/generate/modules_genpassword.php
 *		\ingroup    core
 *		\brief      File with parent class for password generating classes
 */
require_once DOL_DOCUMENT_ROOT.'/core/lib/functions.lib.php';


/**
 *  \class      ModeleGenPassword
 *  \brief      Parent class for password rules/management modules
 */
abstract class ModeleGenPassword
{
<<<<<<< HEAD
    var $error='';
=======
    /**
	 * @var string Error code (or message)
	 */
	public $error='';
>>>>>>> fed598236c185406f59a504ed57181464c26b1b9

    /**
     * 		Return if a module can be used or not
     *
     *      @return		boolean     true if module can be used
     */
<<<<<<< HEAD
    function isEnabled()
=======
    public function isEnabled()
>>>>>>> fed598236c185406f59a504ed57181464c26b1b9
    {
        return true;
    }

    /**
     *		Return description of module
     *
     *      @return     string      Description of text
     */
<<<<<<< HEAD
    function getDescription()
=======
    public function getDescription()
>>>>>>> fed598236c185406f59a504ed57181464c26b1b9
    {
        global $langs;
        return $langs->trans("NoDescription");
    }

    /**
<<<<<<< HEAD
     * 		Return an example of password generated by this module
     *
     *      @return     string      Example of password
     */
    function getExample()
=======
     *  Return an example of password generated by this module
     *
     *  @return     string      Example of password
     */
    public function getExample()
>>>>>>> fed598236c185406f59a504ed57181464c26b1b9
    {
        global $langs;
        $langs->load("bills");
        return $langs->trans("NoExample");
    }

	/**
<<<<<<< HEAD
	 * 		Build new password
	 *
 	 *      @return     string      Return a new generated password
	 */
    function getNewGeneratedPassword()
=======
	 *  Build new password
	 *
 	 *  @return     string      Return a new generated password
	 */
    public function getNewGeneratedPassword()
>>>>>>> fed598236c185406f59a504ed57181464c26b1b9
    {
        global $langs;
        return $langs->trans("NotAvailable");
    }

	/**
	 * 		Validate a password
	 *
	 *		@param		string	$password	Password to check
 	 *      @return     int					0 if KO, >0 if OK
	 */
<<<<<<< HEAD
    function validatePassword($password)
    {
        return 1;
    }

}

=======
    public function validatePassword($password)
    {
        return 1;
    }
}
>>>>>>> fed598236c185406f59a504ed57181464c26b1b9
