language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/sabre-cs-fixer fix lib/ --dry-run --diff

before_script: composer install --dev

