dolibarr: CommonObject Class Reference
CommonObject Class Reference
Parent class of all other business classes (invoices, contracts, proposals, orders, ...)
Public Member Functions
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($statusoflink=-1, $source='external', $list=0, $code='', $status=-1)
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid, $notrigger=0)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id, $deposit_percent=null)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add an object link into llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='', $fieldstatus='fk_statut')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0, $entity=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
clearFieldError ($fieldKey)
clear validation message result for a field
setFieldError ($fieldKey, $msg='')
set validation error message a field
getFieldError ($fieldKey)
get field error message
validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='', $filter=array(), $filtermode="AND")
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
static commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a product id with another one.
Public Attributes
$projet
$fk_projet
$note
Protected Member Functions
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert by returning an array with all properties of object.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Parent class of all other business classes (invoices, contracts, proposals, orders, ...)
Definition at line 44 of file commonobject.class.php.
Member Function Documentation
__clone()
CommonObject::__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
Returns
void
Definition at line 5377 of file commonobject.class.php.
add_contact()
CommonObject::add_contact ($fk_socpeople, $type_contact, $source = 'external', $notrigger = 0)
Add a link between element $this->element and a contact.
Parameters
int $fk_socpeople Id of thirdparty contact (if source = 'external') or id of user (if souce = 'internal') to link
int | string $type_contact Type of contact (code or id). Must be id or code found into table llx_c_type_contact. For example: SALESREPFOLL
string $source external=Contact extern (llx_socpeople), internal=Contact intern (llx_user)
int $notrigger Disable all triggers
Returns
int <0 if KO, 0 if already added, >0 if OK
Definition at line 1119 of file commonobject.class.php.
add_element_resource()
CommonObject::add_element_resource ($resource_id, $resource_type, $busy = 0, $mandatory = 0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
Parameters
int $resource_id Resource id
string $resource_type 'resource'
int $busy Busy or not
int $mandatory Mandatory or not
Returns
int <=0 if KO, >0 if OK
Definition at line 5300 of file commonobject.class.php.
add_object_linked()
CommonObject::add_object_linked ($origin = null, $origin_id = null, $f_user = null, $notrigger = 0)
Add an object link into llx_element_element.
Parameters
string $origin Linked element type
int $origin_id Linked element id
User $f_user User that create
int $notrigger 1=Does not execute triggers, 0=execute triggers
Returns
int <=0 if KO, >0 if OK
See also
fetchObjectLinked(), updateObjectLinked(), deleteObjectLinked()
Definition at line 3808 of file commonobject.class.php.
addThumbs()
CommonObject::addThumbs ($file)
Build thumb.
Parameters
string $file Path file in UTF8 to original file to create thumbs from.
Returns
void
Definition at line 5702 of file commonobject.class.php.
call_trigger()
CommonObject::call_trigger ($triggerName, $user)
Call trigger based on this instance.
Some context information may also be provided into array property this->context. NB: Error from trigger are stacked in interface->errors NB2: If return code of triggers are < 0, action calling trigger should cancel all transaction.
Parameters
string $triggerName trigger's name to execute
User $user Object user
Returns
int Result of run_triggers
Reimplemented in EcmDirectory.
Definition at line 5786 of file commonobject.class.php.
canBeNull()
CommonObject::canBeNull ($info) protected
Function test if field can be null.
Parameters
array $info content informations of field
Returns
bool true if it can be null
Definition at line 8912 of file commonobject.class.php.
clearFieldError()
CommonObject::clearFieldError ($fieldKey)
clear validation message result for a field
Parameters
string $fieldKey Key of attribute to clear
Returns
null
Definition at line 7827 of file commonobject.class.php.
clearObjectLinkedCache()
CommonObject::clearObjectLinkedCache ()
Clear the cache saying that all linked object were already loaded.
So next fetchObjectLinked will reload all links.
Returns
int <0 if KO, >0 if OK
See also
fetchObjectLinked()
Definition at line 4127 of file commonobject.class.php.
cloneCategories()
CommonObject::cloneCategories ($fromId, $toId, $type = '')
Copy related categories to another object.
Parameters
int $fromId Id object source
int $toId Id object cible
string $type Type of category ('product', ...)
Returns
int < 0 if error, > 0 if ok
Definition at line 10037 of file commonobject.class.php.
commonGenerateDocument()
CommonObject::commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams = null) protected
Common function for all objects extending CommonObject for generating documents.
Parameters
string $modelspath Relative folder where generators are placed
string $modele Generator to use. Caller must set it to obj->model_pdf or GETPOST('model_pdf','alpha') for example.
Translate $outputlangs Output language to use
int $hidedetails 1 to hide details. 0 by default
int $hidedesc 1 to hide product description. 0 by default
int $hideref 1 to hide product reference. 0 by default
null | array $moreparams Array to provide more information
Returns
int >0 if OK, <0 if KO
See also
addFileIntoDatabaseIndex()
Definition at line 5401 of file commonobject.class.php.
commonReplaceProduct()
static CommonObject::commonReplaceProduct (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors = 0) static
Function used to replace a product id with another one.
This function is meant to be called from replaceProduct with the appropriate tables Column name fk_product MUST be used to identify products
Parameters
DoliDB $dbs Database handler
int $origin_id Old product id (the product to delete)
int $dest_id New product id (the product that will received element of the other)
string[] $tables Tables that need to be changed
int $ignoreerrors Ignore errors. Return true even if errors. We need this when replacement can fails like for categories (categorie of old product may already exists on new one)
Returns
bool True if success, False if error
Definition at line 8485 of file commonobject.class.php.
Referenced by BOM\replaceProduct(), Propal\replaceProduct(), Commande\replaceProduct(), Facture\replaceProduct(), Contrat\replaceProduct(), Delivery\replaceProduct(), FichinterRec\replaceProduct(), CommandeFournisseur\replaceProduct(), FactureFournisseur\replaceProduct(), SupplierProposal\replaceProduct(), FactureRec\replaceProduct(), ProductFournisseur\replaceProduct(), and Reception\replaceProduct().
commonReplaceThirdparty()
static CommonObject::commonReplaceThirdparty (DoliDB $dbs, $origin_id, $dest_id, array $tables, $ignoreerrors = 0) static
Function used to replace a thirdparty id with another one.
This function is meant to be called from replaceThirdparty with the appropriate tables Column name fk_soc MUST be used to identify thirdparties
Parameters
DoliDB $dbs Database handler
int $origin_id Old thirdparty id (the thirdparty to delete)
int $dest_id New thirdparty id (the thirdparty that will received element of the other)
string[] $tables Tables that need to be changed
int $ignoreerrors Ignore errors. Return true even if errors. We need this when replacement can fails like for categories (categorie of old thirdparty may already exists on new one)
Returns
bool True if success, False if error
Definition at line 8456 of file commonobject.class.php.
Referenced by Mo\replaceThirdparty(), Bookmark\replaceThirdparty(), Categorie\replaceThirdparty(), ActionComm\replaceThirdparty(), Propal\replaceThirdparty(), Commande\replaceThirdparty(), FactureRec\replaceThirdparty(), Facture\replaceThirdparty(), Contact\replaceThirdparty(), Contrat\replaceThirdparty(), Delivery\replaceThirdparty(), Don\replaceThirdparty(), Expedition\replaceThirdparty(), Fichinter\replaceThirdparty(), FichinterRec\replaceThirdparty(), Fournisseur\replaceThirdparty(), CommandeFournisseur\replaceThirdparty(), FactureFournisseurRec\replaceThirdparty(), FactureFournisseur\replaceThirdparty(), ProductFournisseur\replaceThirdparty(), Product\replaceThirdparty(), Project\replaceThirdparty(), Reception\replaceThirdparty(), and SupplierProposal\replaceThirdparty().
copy_linked_contact()
CommonObject::copy_linked_contact ($objFrom, $source = 'internal')
Copy contact from one element to current.
Parameters
CommonObject $objFrom Source element
string $source Nature of contact ('internal' or 'external')
Returns
int >0 if OK, <0 if KO
Definition at line 1228 of file commonobject.class.php.
createCommon()
CommonObject::createCommon (User $user, $notrigger = false)
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 9145 of file commonobject.class.php.
Referenced by AssetModel\create(), BOM\create(), BOMLine\create(), Availabilities\create(), Booking\create(), ActionCommReminder\create(), DefaultValues\create(), EmailSenderProfile\create(), ExpenseReportIk\create(), ExpenseReportRule\create(), Evaluation\create(), Evaluationline\create(), Job\create(), Position\create(), Skilldet\create(), KnowledgeRecord\create(), MyObject\create(), PartnershipType\create(), ProductFournisseurPrice\create(), InventoryLine\create(), StockTransfer\create(), StockTransferLine\create(), RecruitmentCandidature\create(), RecruitmentJobPosition\create(), CompanyPaymentMode\create(), SocieteAccount\create(), CTicketCategory\create(), Target\create(), WebsitePage\create(), and Hook\create().
defineBuyPrice()
CommonObject::defineBuyPrice ($unitPrice = 0.0, $discountPercent = 0.0, $fk_product = 0)
Get buy price to use for margin calculation.
This function is called when buy price is unknown. Set buy price = sell price if ForceBuyingPriceIfNull configured, elseif calculation MARGIN_TYPE = 'costprice' and costprice is defined, use costprice as buyprice elseif calculation MARGIN_TYPE = 'pmp' and pmp is calculated, use pmp as buyprice else set min buy price as buy price
Parameters
float $unitPrice Product unit price
float $discountPercent Line discount percent
int $fk_product Product id
Returns
float <0 if KO, buyprice if OK
Definition at line 8514 of file commonobject.class.php.
delete_contact()
CommonObject::delete_contact ($rowid, $notrigger = 0)
Delete a link to contact line.
Parameters
int $rowid Id of contact link line to delete
int $notrigger Disable all triggers
Returns
int >0 if OK, <0 if KO
Definition at line 1280 of file commonobject.class.php.
delete_linked_contact()
CommonObject::delete_linked_contact ($source = '', $code = '')
Delete all links between an object $this and all its contacts.
Parameters
string $source '' or 'internal' or 'external'
string $code Type of contact (code or id)
Returns
int >0 if OK, <0 if KO
Definition at line 1318 of file commonobject.class.php.
delete_resource()
CommonObject::delete_resource ($rowid, $element, $notrigger = 0)
Delete a link to resource line.
Parameters
int $rowid Id of resource line to delete
int $element element name (for trigger) TODO: use $this->element into commonobject class
int $notrigger Disable all triggers
Returns
int >0 if OK, <0 if KO
Definition at line 5341 of file commonobject.class.php.
deleteAllItemsLinkedByObjectID()
static CommonObject::deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element) static
Function used to remove all items linked to an object id in association table.
Parameters
int $fk_object_where id of object we need to remove linked items
string $field_where name of field of object we need to delete linked items
string $table_element name of association table
Returns
int <0 if KO, 0 if nothing done, >0 if OK and something done
Definition at line 4326 of file commonobject.class.php.
deleteByParentField()
CommonObject::deleteByParentField ($parentId = 0, $parentField = '', $filter = array(), $filtermode = "AND")
Delete all child object from a parent ID.
Parameters
int $parentId Parent Id
string $parentField Name of Foreign key parent column
array $filter an array filter
string $filtermode AND or OR
Returns
int <0 if KO, >0 if OK
Exceptions
Exception
Definition at line 9661 of file commonobject.class.php.
deleteCommon()
CommonObject::deleteCommon (User $user, $notrigger = false, $forcechilddeletion = 0)
Delete object in database.
Parameters
User $user User that deletes
bool $notrigger false=launch triggers after, true=disable triggers
int $forcechilddeletion 0=no, 1=Force deletion of children
Returns
int <0 if KO, 0=Nothing done because object has child, >0 if OK
Definition at line 9522 of file commonobject.class.php.
Referenced by UserGroup\delete(), Asset\delete(), AssetModel\delete(), BOM\delete(), BOMLine\delete(), Availabilities\delete(), Booking\delete(), ActionCommReminder\delete(), CashControl\delete(), DefaultValues\delete(), EmailSenderProfile\delete(), EmailCollector\delete(), EmailCollectorAction\delete(), EmailCollectorFilter\delete(), ConferenceOrBoothAttendee\delete(), ExpenseReportIk\delete(), ExpenseReportRule\delete(), Evaluation\delete(), Evaluationline\delete(), Job\delete(), Position\delete(), Skill\delete(), Skilldet\delete(), SkillRank\delete(), MyObject\delete(), Mo\delete(), MoLine\delete(), Partnership\delete(), PartnershipType\delete(), ProductFournisseurPrice\delete(), Inventory\delete(), InventoryLine\delete(), MouvementStock\delete(), StockTransfer\delete(), StockTransferLine\delete(), RecruitmentCandidature\delete(), RecruitmentJobPosition\delete(), CompanyPaymentMode\delete(), SocieteAccount\delete(), CTicketCategory\delete(), Target\delete(), Workstation\delete(), and Hook\delete().
deleteEcmFiles()
CommonObject::deleteEcmFiles ($mode = 0)
Delete related files of object in database.
Parameters
integer $mode 0=Use path to find record, 1=Use src_object_xxx fields (Mode 1 is recommanded for new objects)
Returns
bool True if OK, False if KO
Definition at line 10068 of file commonobject.class.php.
deleteExtraFields()
CommonObject::deleteExtraFields ()
Delete all extra fields values for the current object.
Returns
int <0 if KO, >0 if OK
See also
deleteExtraLanguages(), insertExtraField(), updateExtraField(), setValueFrom()
Definition at line 6109 of file commonobject.class.php.
deleteLineCommon()
CommonObject::deleteLineCommon (User $user, $idline, $notrigger = false)
Delete a line of object in database.
Parameters
User $user User that delete
int $idline Id of line to delete
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int >0 if OK, <0 if KO
Definition at line 9738 of file commonobject.class.php.
deleteObjectLinked()
CommonObject::deleteObjectLinked ($sourceid = null, $sourcetype = '', $targetid = null, $targettype = '', $rowid = '', $f_user = null, $notrigger = 0)
Delete all links between an object $this.
Parameters
int $sourceid Object source id
string $sourcetype Object source type
int $targetid Object target id
string $targettype Object target type
int $rowid Row id of line to delete. If defined, other parameters are not used.
User $f_user User that create
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int >0 if OK, <0 if KO
See also
add_object_linked(), updateObjectLinked(), fetchObjectLinked()
Definition at line 4218 of file commonobject.class.php.
errorsToString()
CommonObject::errorsToString ()
Method to output saved errors.
Returns
string String with errors
Definition at line 664 of file commonobject.class.php.
fetch_barcode()
CommonObject::fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
Type is used to find other properties, but if it is not defined, ->element must be defined to know default barcode type.
Returns
int <0 if KO, 0 if can't guess type of barcode (ISBN, EAN13...), >0 if OK (all barcode properties loaded)
Definition at line 1806 of file commonobject.class.php.
fetch_contact()
CommonObject::fetch_contact ($contactid = null)
Load object contact with id=$this->contact_id into $this->contact.
Parameters
int $contactid Id du contact. Use this->contact_id if empty.
Returns
int <0 if KO, >0 if OK
Definition at line 1711 of file commonobject.class.php.
fetch_optionals()
CommonObject::fetch_optionals ($rowid = null, $optionsArray = null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
Parameters
int $rowid Id of line. Use the id of object if not defined. Deprecated. Function must be called without parameters.
array $optionsArray Array resulting of call of extrafields->fetch_name_optionals_label(). Deprecated. Function must be called without parameters.
Returns
int <0 if error, 0 if no values of extrafield to find nor found, 1 if an attribute is found and value loaded
See also
fetchValuesForExtraLanguages()
Definition at line 6002 of file commonobject.class.php.
fetch_origin()
CommonObject::fetch_origin ()
Read linked origin object.
Returns
void
Definition at line 1929 of file commonobject.class.php.
fetch_product()
CommonObject::fetch_product ()
Load the product with id $this->fk_product into this->product.
Returns
int <0 if KO, >=0 if OK
Definition at line 1891 of file commonobject.class.php.
fetch_project()
CommonObject::fetch_project ()
Load the project with id $this->fk_project into this->project.
Returns
int <0 if KO, >=0 if OK
Definition at line 1853 of file commonobject.class.php.
fetch_projet()
CommonObject::fetch_projet ()
Load the project with id $this->fk_project into this->project.
Returns
int <0 if KO, >=0 if OK
Reimplemented in ConferenceOrBoothAttendee.
Definition at line 1865 of file commonobject.class.php.
fetch_thirdparty()
CommonObject::fetch_thirdparty ($force_thirdparty_id = 0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
Parameters
int $force_thirdparty_id Force thirdparty id
Returns
int <0 if KO, >0 if OK
Reimplemented in PaiementFourn, and Paiement.
Definition at line 1736 of file commonobject.class.php.
fetch_user()
CommonObject::fetch_user ($userid)
Load the user with id $userid into this->user.
Parameters
int $userid Id du contact
Returns
int <0 if KO, >0 if OK
Definition at line 1914 of file commonobject.class.php.
fetchComments()
CommonObject::fetchComments ()
Load comments linked with current task.
Returns
boolean 1 if ok
Definition at line 9884 of file commonobject.class.php.
fetchCommon()
CommonObject::fetchCommon ($id, $ref = null, $morewhere = '')
Load object in memory from the database.
Parameters
int $id Id object
string $ref Ref
string $morewhere More SQL filters (' AND ...')
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 9312 of file commonobject.class.php.
Referenced by ProductFournisseurPrice\fetch().
fetchLinesCommon()
CommonObject::fetchLinesCommon ($morewhere = '')
Load object in memory from the database.
Parameters
string $morewhere More SQL filters (' AND ...')
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 9368 of file commonobject.class.php.
fetchNoCompute()
CommonObject::fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
Parameters
int $id ID of object
Returns
int >0 if OK, 0 if not found, <0 if KO
Definition at line 5978 of file commonobject.class.php.
fetchObjectFrom()
CommonObject::fetchObjectFrom ($table, $field, $key, $element = null)
Load object from specific field.
Parameters
string $table Table element or element line
string $field Field selected
string $key Import key
string $element Element name
Returns
int <0 if KO, >0 if OK
Definition at line 1958 of file commonobject.class.php.
fetchObjectLinked()
mixed Array of linked objects Loaded by CommonObject::fetchObjectLinked ($sourceid = null, $sourcetype = '', $targetid = null, $targettype = '', $clause = 'OR', $alsosametype = 1, $orderby = 'sourcetype', $loadalsoobjects = 1)
Fetch array of objects linked to current object (object of enabled modules only).
Links are loaded into this->linkedObjectsIds array + this->linkedObjects array if $loadalsoobjects = 1 or $loadalsoobjects = type Possible usage for parameters:
all parameters empty -> we look all link to current object (current object can be source or target)
source id+type -> will get list of targets linked to source
target id+type -> will get list of sources linked to target
source id+type + target type -> will get list of targets of the type linked to source
target id+type + source type -> will get list of sources of the type linked to target
Parameters
int $sourceid Object source id (if not defined, id of object)
string $sourcetype Object source type (if not defined, element name of object)
int $targetid Object target id (if not defined, id of object)
string $targettype Object target type (if not defined, element name of object)
string $clause 'OR' or 'AND' clause used when both source id and target id are provided
int $alsosametype 0=Return only links to object that differs from source type. 1=Include also link to objects of same type.
string $orderby SQL 'ORDER BY' clause
int | string $loadalsoobjects Load also array this->linkedObjects. Use 0 to increase performances, Use 1 to load all, Use value of type ('facture', 'facturerec', ...) to load only a type of object.
Returns
int <0 if KO, >0 if OK
See also
add_object_linked(), updateObjectLinked(), deleteObjectLinked()
Definition at line 3906 of file commonobject.class.php.
Referenced by Propal\InvoiceArrayList().
fetchOneLike()
CommonObject::fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
Parameters
string $ref Wildcard
Returns
int >1 = OK, 0 = Not found or table_ref_field not defined, <0 = KO
Definition at line 1779 of file commonobject.class.php.
fetchValuesForExtraLanguages()
CommonObject::fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
Returns
int <0 if error, 0 if no values of alternative languages to find nor found, 1 if a value was found and loaded
See also
fetch_optionnals()
Definition at line 5824 of file commonobject.class.php.
formAddObjectLine()
CommonObject::formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir = '/core/tpl')
Show add free and predefined products/services form.
Parameters
int $dateSelector 1=Show also date range input fields
Societe $seller Object thirdparty who sell
Societe $buyer Object thirdparty who buy
string $defaulttpldir Directory where to find the template
Returns
void
Reimplemented in ProductAttribute.
Definition at line 4835 of file commonobject.class.php.
getAllItemsLinkedByObjectID()
static CommonObject::getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element) static
Function used to get an array with all items linked to an object id in association table.
Parameters
int $fk_object_where id of object we need to get linked items
string $field_select name of field we need to get a list
string $field_where name of field of object we need to get linked items
string $table_element name of association table
Returns
array Array of record
Definition at line 4297 of file commonobject.class.php.
getBannerAddress()
CommonObject::getBannerAddress ($htmlkey, $object)
Return full address for banner.
Parameters
string $htmlkey HTML id to make banner content unique
Object $object Object (thirdparty, thirdparty of contact for contact, null for a member)
Returns
string Full address string
Definition at line 838 of file commonobject.class.php.
getCanvas()
CommonObject::getCanvas ($id = 0, $ref = '')
Load type of canvas of an object if it exists.
Parameters
int $id Record id
string $ref Record ref
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 4481 of file commonobject.class.php.
getCategoriesCommon()
CommonObject::getCategoriesCommon ($type_categ)
Sets object to given categories.
Deletes object from existing categories not supplied. Adds it to non existing supplied categories. Existing categories are left untouch.
Parameters
string $type_categ Category type ('customer', 'supplier', 'website_page', ...)
Returns
int Array of category objects or < 0 if KO
Definition at line 9939 of file commonobject.class.php.
getChildrenOfLine()
CommonObject::getChildrenOfLine ($id, $includealltree = 0)
Get children of line.
Parameters
int $id Id of parent line
int $includealltree 0 = 1st level child, 1 = All level child
Returns
array Array with list of children lines id
Definition at line 3140 of file commonobject.class.php.
getDefaultCreateValueFor()
CommonObject::getDefaultCreateValueFor ($fieldname, $alternatevalue = null)
Return the default value to use for a field when showing the create form of object.
Return values in this order: 1) If parameter is available into POST, we return it first. 2) If not but an alternate value was provided as parameter of function, we return it. 3) If not but a constant $conf->global->OBJECTELEMENT_FIELDNAME is set, we return it (It is better to use the dedicated table). 4) Return value found into database (TODO No yet implemented)
Parameters
string $fieldname Name of field
string $alternatevalue Alternate value to use
Returns
string|string[] Default value (can be an array if the GETPOST return an array)
Definition at line 5737 of file commonobject.class.php.
getFieldError()
CommonObject::getFieldError ($fieldKey)
get field error message
Parameters
string $fieldKey Key of attribute
Returns
string Error message of validation ('' if no error)
Definition at line 7854 of file commonobject.class.php.
getFieldList()
CommonObject::getFieldList ($alias = '')
Function to concat keys of fields.
Parameters
string $alias String of alias of table for fields. For example 't'. It is recommended to use '' and set alias into fields defintion.
Returns
string list of alias fields
Definition at line 9097 of file commonobject.class.php.
getFormatedCustomerRef()
CommonObject::getFormatedCustomerRef ($objref)
Return customer ref for screen output.
Parameters
string $objref Customer ref
Returns
string Customer ref formated
Definition at line 676 of file commonobject.class.php.
getFormatedSupplierRef()
CommonObject::getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
Parameters
string $objref Supplier ref
Returns
string Supplier ref formated
Definition at line 695 of file commonobject.class.php.
getFullAddress()
CommonObject::getFullAddress ($withcountry = 0, $sep = "\n", $withregion = 0, $extralangcode = '')
Return full address of contact.
Parameters
int $withcountry 1=Add country into address string
string $sep Separator to use to build string
int $withregion 1=Add region into address string
string $extralangcode User extralanguages as value
Returns
string Full address string
Definition at line 809 of file commonobject.class.php.
getFullName()
CommonObject::getFullName ($langs, $option = 0, $nameorder = -1, $maxlen = 0)
Return full name (civility+' '+name+' '+lastname)
Parameters
Translate $langs Language object for translation of civility (used only if option is 1)
int $option 0=No option, 1=Add civility
int $nameorder -1=Auto, 0=Lastname+Firstname, 1=Firstname+Lastname, 2=Firstname, 3=Firstname if defined else lastname, 4=Lastname, 5=Lastname if defined else firstname
int $maxlen Maximum length
Returns
string String with full name
Definition at line 717 of file commonobject.class.php.
getIdContact()
CommonObject::getIdContact ($source, $code, $status = 0)
Return id of contacts for a source and a contact code.
Example: contact client de facturation ('external', 'BILLING') Example: contact client de livraison ('external', 'SHIPPING') Example: contact interne suivi paiement ('internal', 'SALESREPFOLL')
Parameters
string $source 'external' or 'internal'
string $code 'BILLING', 'SHIPPING', 'SALESREPFOLL', ...
int $status limited to a certain status
Returns
array List of id for such contacts
Definition at line 1643 of file commonobject.class.php.
Referenced by Facture\getIdBillingContact(), Contrat\getIdBillingContact(), Contrat\getIdServiceContact(), and Facture\getIdShippingContact().
getIdOfLine()
CommonObject::getIdOfLine ($rang)
Get rowid of the line relative to its position.
Parameters
int $rang Rang value
Returns
int Rowid of the line
Definition at line 3349 of file commonobject.class.php.
getJSListDependancies()
CommonObject::getJSListDependancies ($type = '_extra')
Parameters
string $type Type for prefix
Returns
string Javacript code to manage dependency
Definition at line 8353 of file commonobject.class.php.
getKanbanView()
CommonObject::getKanbanView ($option = '')
Return clicable link of object (with eventually picto)
Parameters
string $option Where point the link (0=> main card, 1,2 => shipment, 'nolink'=>No link)
Returns
string HTML Code for Kanban thumb.
Reimplemented in UserGroup, User, Entrepot, CommonOrder, CommonObjectLine, Contact, and BOM.
Definition at line 778 of file commonobject.class.php.
getLastMainDocLink()
CommonObject::getLastMainDocLink ($modulepart, $initsharekey = 0, $relativelink = 0)
Return the link of last main doc file for direct public download.
Parameters
string $modulepart Module related to document
int $initsharekey Init the share key if it was not yet defined
int $relativelink 0=Return full external link, 1=Return link relative to root of file
Returns
string Link or empty string if there is no download link
Definition at line 1025 of file commonobject.class.php.
getListContactId()
CommonObject::getListContactId ($source = 'external')
Return list of id of contacts of object.
Parameters
string $source Source of contact: external (llx_socpeople) or internal (llx_user) or thirdparty (llx_societe)
Returns
array Array of id of contacts (if source=external or internal) Array of id of third parties with at least one contact on object (if source=thirdparty)
Reimplemented in Task.
Definition at line 2306 of file commonobject.class.php.
getNbComments()
CommonObject::getNbComments ()
Return nb comments already posted.
Returns
int
Definition at line 9904 of file commonobject.class.php.
getRangOfLine()
CommonObject::getRangOfLine ($rowid)
Get position of line (rang)
Parameters
int $rowid Id of line
Returns
int Value of rang in table of lines
Definition at line 3325 of file commonobject.class.php.
getRights()
CommonObject::getRights ()
Returns the rights used for this class.
Returns
stdClass
Reimplemented in Product, FactureFournisseur, and CommandeFournisseur.
Definition at line 8428 of file commonobject.class.php.
getSpecialCode()
CommonObject::getSpecialCode ($lineid)
Get special code of a line.
Parameters
int $lineid Id of line
Returns
int Special code
Definition at line 4527 of file commonobject.class.php.
getTotalDiscount()
CommonObject::getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
Returns
float|string Total amout of discount
Definition at line 4657 of file commonobject.class.php.
getTotalWeightVolume()
CommonObject::getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
Returns
array array('weight'=>...,'volume'=>...)
Definition at line 4699 of file commonobject.class.php.
getValueFrom()
CommonObject::getValueFrom ($table, $id, $field)
Getter generic.
Load value from a specific field
Parameters
string $table Table of element or element line
int $id Element id
string $field Field selected
Returns
int <0 if KO, >0 if OK
Definition at line 1993 of file commonobject.class.php.
hasProductsOrServices()
CommonObject::hasProductsOrServices ($predefined = -1)
Function to say how many lines object contains.
Parameters
int $predefined -1=All, 0=Count free product/service only, 1=Count predefined product/service only, 2=Count predefined product, 3=Count predefined service
Returns
int <0 if KO, 0 if no predefined products, nb of lines with predefined products if found
Definition at line 4623 of file commonobject.class.php.
indexFile()
CommonObject::indexFile ($destfull, $update_main_doc_field)
Index a file into the ECM database.
Parameters
string $destfull Full path of file to index
int $update_main_doc_field Update field main_doc fied into the table of object. This param is set when called for a document generation if document generator hase ->update_main_doc_field set and returns ->result['fullpath'].
Returns
int <0 if KO, >0 if OK
Definition at line 5587 of file commonobject.class.php.
initAsSpecimenCommon()
CommonObject::initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
int
Definition at line 9850 of file commonobject.class.php.
Referenced by Asset\initAsSpecimen(), BOM\initAsSpecimen(), BOMLine\initAsSpecimen(), ActionCommReminder\initAsSpecimen(), DefaultValues\initAsSpecimen(), EmailSenderProfile\initAsSpecimen(), EmailCollectorAction\initAsSpecimen(), EmailCollectorFilter\initAsSpecimen(), ConferenceOrBooth\initAsSpecimen(), Mo\initAsSpecimen(), Inventory\initAsSpecimen(), CompanyPaymentMode\initAsSpecimen(), SocieteAccount\initAsSpecimen(), CTicketCategory\initAsSpecimen(), and Hook\initAsSpecimen().
insertExtraFields()
CommonObject::insertExtraFields ($trigger = '', $userused = null)
Add/Update all extra fields values for the current object.
Data to describe values to insert/update are stored into $this->array_options=array('options_codeforfield1'=>'valueforfield1', 'options_codeforfield2'=>'valueforfield2', ...) This function delete record with all extrafields and insert them again from the array $this->array_options.
Parameters
string $trigger If defined, call also the trigger (for example COMPANY_MODIFY)
User $userused Object user
Returns
int -1=error, O=did nothing, 1=OK
See also
insertExtraLanguages(), updateExtraField(), deleteExtraField(), setValueFrom()
Definition at line 6149 of file commonobject.class.php.
insertExtraLanguages()
CommonObject::insertExtraLanguages ($trigger = '', $userused = null)
Add/Update all extra fields values for the current object.
Data to describe values to insert/update are stored into $this->array_options=array('options_codeforfield1'=>'valueforfield1', 'options_codeforfield2'=>'valueforfield2', ...) This function delete record with all extrafields and insert them again from the array $this->array_options.
Parameters
string $trigger If defined, call also the trigger (for example COMPANY_MODIFY)
User $userused Object user
Returns
int -1=error, O=did nothing, 1=OK
See also
insertExtraFields(), updateExtraField(), setValueFrom()
Definition at line 6418 of file commonobject.class.php.
isArray()
CommonObject::isArray ($info) protected
Function test if type is array.
Parameters
array $info content informations of field
Returns
bool true if array
Definition at line 8806 of file commonobject.class.php.
isDate()
CommonObject::isDate ($info)
Function test if type is date.
Parameters
array $info content informations of field
Returns
bool true if date
Definition at line 8824 of file commonobject.class.php.
isDuration()
CommonObject::isDuration ($info)
Function test if type is duration.
Parameters
array $info content informations of field
Returns
bool true if field of type duration
Definition at line 8838 of file commonobject.class.php.
isExistingObject()
static CommonObject::isExistingObject ($element, $id, $ref = '', $ref_ext = '') static
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
Parameters
string $element String of element ('product', 'facture', ...)
int $id Id of object
string $ref Ref of object to check
string $ref_ext Ref ext of object to check
Returns
int <0 if KO, 0 if OK but not found, >0 if OK and exists
Definition at line 622 of file commonobject.class.php.
isFloat()
CommonObject::isFloat ($info)
Function test if type is float.
Parameters
array $info content informations of field
Returns
bool true if float
Definition at line 8876 of file commonobject.class.php.
isForcedToNullIfZero()
CommonObject::isForcedToNullIfZero ($info) protected
Function test if field is forced to null if zero or empty.
Parameters
array $info content informations of field
Returns
bool true if forced to null
Definition at line 8930 of file commonobject.class.php.
isIndex()
CommonObject::isIndex ($info) protected
Function test if is indexed.
Parameters
array $info content informations of field
Returns
bool
Definition at line 8948 of file commonobject.class.php.
isInt()
CommonObject::isInt ($info)
Function test if type is integer.
Parameters
array $info content informations of field
Returns
bool true if integer
Definition at line 8857 of file commonobject.class.php.
isObjectUsed()
CommonObject::isObjectUsed ($id = 0, $entity = 0)
Function to check if an object is used by others.
Check is done into this->childtables. There is no check into llx_element_element.
Parameters
int $id Force id of object
int $entity Force entity to check
Returns
int <0 if KO, 0 if not used, >0 if already used
Definition at line 4546 of file commonobject.class.php.
isText()
CommonObject::isText ($info)
Function test if type is text.
Parameters
array $info content informations of field
Returns
bool true if type text
Definition at line 8894 of file commonobject.class.php.
line_ajaxorder()
CommonObject::line_ajaxorder ($rows)
Update position of line with ajax (rang)
Parameters
array $rows Array of rows
Returns
void
Definition at line 3249 of file commonobject.class.php.
line_down()
CommonObject::line_down ($rowid, $fk_parent_line = true)
Update a line to have a higher rank.
Parameters
int $rowid Id of line
boolean $fk_parent_line Table with fk_parent_line field or not
Returns
void
Definition at line 3197 of file commonobject.class.php.
line_max()
CommonObject::line_max ($fk_parent_line = 0)
Get max value used for position of line (rang)
Parameters
int $fk_parent_line Parent line id
Returns
int Max value of rang in table of lines
Definition at line 3373 of file commonobject.class.php.
line_order()
CommonObject::line_order ($renum = false, $rowidorder = 'ASC', $fk_parent_line = true)
Save a new position (field rang) for details lines.
You can choose to set position for lines with already a position or lines without any position defined.
Parameters
boolean $renum True to renum all already ordered lines, false to renum only not already ordered lines.
string $rowidorder ASC or DESC
boolean $fk_parent_line Table with fk_parent_line field or not
Returns
int <0 if KO, >0 if OK
Definition at line 3055 of file commonobject.class.php.
line_up()
CommonObject::line_up ($rowid, $fk_parent_line = true)
Update a line to have a lower rank.
Parameters
int $rowid Id of line
boolean $fk_parent_line Table with fk_parent_line field or not
Returns
void
Definition at line 3177 of file commonobject.class.php.
liste_contact()
array To store result of CommonObject::liste_contact ($statusoflink = -1, $source = 'external', $list = 0, $code = '', $status = -1)
Get array of all contacts for an object.
Parameters
int $statusoflink Status of links to get (-1=all). Not used.
string $source Source of contact: 'external' or 'thirdparty' (llx_socpeople) or 'internal' (llx_user)
int $list 0:Return array contains all properties, 1:Return array contains just id
string $code Filter on this code of contact type ('SHIPPING', 'BILLING', ...)
int $status Status of user or company
Returns
array|int Array of contacts, -1 if error
Definition at line 1358 of file commonobject.class.php.
liste_type_contact()
CommonObject::liste_type_contact ($source = 'internal', $order = 'position', $option = 0, $activeonly = 0, $code = '')
Return array with list of possible values for type of contacts.
Parameters
string $source 'internal', 'external' or 'all'
string $order Sort order by : 'position', 'code', 'rowid'...
int $option 0=Return array id->label, 1=Return array code->label
int $activeonly 0=all status of contact, 1=only the active
string $code Type of contact (Example: 'CUSTOMER', 'SERVICE')
Returns
array Array list of type of contacts (id->label if option=0, code->label if option=1)
Definition at line 1492 of file commonobject.class.php.
listeTypeContacts()
CommonObject::listeTypeContacts ($source = 'internal', $option = 0, $activeonly = 0, $code = '', $element = '', $excludeelement = '')
Return array with list of possible values for type of contacts.
Parameters
string $source 'internal', 'external' or 'all'
int $option 0=Return array id->label, 1=Return array code->label
int $activeonly 0=all status of contact, 1=only the active
string $code Type of contact (Example: 'CUSTOMER', 'SERVICE')
string $element Filter on 1 element type
string $excludeelement Exclude 1 element type. Example: 'agenda'
Returns
array Array list of type of contacts (id->label if option=0, code->label if option=1)
Definition at line 1555 of file commonobject.class.php.
load_previous_next_ref()
CommonObject::load_previous_next_ref ($filter, $fieldid, $nodbprefix = 0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
Parameters
string $filter Optional filter. Example: " AND (t.field1 = 'aa' OR t.field2 = 'bb')". Do not allow user input data here.
string $fieldid Name of field to use for the select MAX and MIN
int $nodbprefix Do not include DB prefix to forge table name
Returns
int <0 if KO, >0 if OK
Definition at line 2123 of file commonobject.class.php.
printObjectLine()
CommonObject::printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected = 0, $extrafields = null, $defaulttpldir = '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
Parameters
string $action GET/POST action
CommonObjectLine $line Selected object line to output
string $var Not used
int $num Number of line (0)
int $i I
int $dateSelector 1=Show also date range input fields
string $seller Object of seller third party
string $buyer Object of buyer third party
int $selected Object line selected
Extrafields $extrafields Object of extrafields
string $defaulttpldir Directory where to find the template (deprecated)
Returns
void
Reimplemented in ProductAttribute.
Definition at line 4979 of file commonobject.class.php.
printObjectLines()
CommonObject::printObjectLines ($action, $seller, $buyer, $selected = 0, $dateSelector = 0, $defaulttpldir = '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
Parameters
string $action Action code
string $seller Object of seller third party
string $buyer Object of buyer third party
int $selected Object line selected
int $dateSelector 1=Show also date range input fields
string $defaulttpldir Directory where to find the template
Returns
void
Definition at line 4888 of file commonobject.class.php.
printOriginLine()
CommonObject::printOriginLine ($line, $var, $restrictlist = '', $defaulttpldir = '/core/tpl', $selectedLines = array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
Parameters
CommonObjectLine $line Line
string $var Var
string $restrictlist ''=All lines, 'services'=Restrict to services only (strike line if not)
string $defaulttpldir Directory where to find the template
array $selectedLines Array of lines id for selected lines
Returns
void
Reimplemented in Mo.
Definition at line 5158 of file commonobject.class.php.
printOriginLinesList()
CommonObject::printOriginLinesList ($restrictlist = '', $selectedLines = array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
If lines are into a template, title must also be into a template But for the moment we don't know if it's possible, so we keep the method available on overloaded objects.
Parameters
string $restrictlist ''=All lines, 'services'=Restrict to services only
array $selectedLines Array of lines id for selected lines
Returns
void
Reimplemented in Mo.
Definition at line 5105 of file commonobject.class.php.
quote()
CommonObject::quote ($value, $fieldsentry) protected
Add quote to field value if necessary.
Parameters
string | int $value Value to protect
array $fieldsentry Properties of field
Returns
string
Definition at line 9118 of file commonobject.class.php.
setBankAccount()
CommonObject::setBankAccount ($fk_account, $notrigger = false, $userused = null)
Change the bank account.
Parameters
int $fk_account Id of bank account
bool $notrigger false=launch triggers after, true=disable triggers
User $userused Object user
Returns
int 1 if OK, 0 if KO
Definition at line 2991 of file commonobject.class.php.
setCategoriesCommon()
CommonObject::setCategoriesCommon ($categories, $type_categ = '', $remove_existing = true)
Sets object to given categories.
Adds it to non existing supplied categories. Deletes object from existing categories not supplied (if remove_existing==true). Existing categories are left untouch.
Parameters
int[] | int $categories Category ID or array of Categories IDs
string $type_categ Category type ('customer', 'supplier', 'website_page', ...) definied into const class Categorie type
boolean $remove_existing True: Remove existings categories from Object if not supplies by $categories, False: let them
Returns
int <0 if KO, >0 if OK
Definition at line 9962 of file commonobject.class.php.
setDeliveryAddress()
CommonObject::setDeliveryAddress ($id)
Define delivery address.
Deprecated:
Parameters
int $id Address id
Returns
int <0 si ko, >0 si ok
Definition at line 2836 of file commonobject.class.php.
setDocModel()
CommonObject::setDocModel ($user, $modelpdf)
Set last model used by doc generator.
Parameters
User $user User object that make change
string $modelpdf Modele name
Returns
int <0 if KO, >0 if OK
Definition at line 2957 of file commonobject.class.php.
setExtraParameters()
CommonObject::setExtraParameters ()
Set extra parameters.
Returns
int <0 if KO, >0 if OK
Definition at line 4797 of file commonobject.class.php.
setFieldError()
CommonObject::setFieldError ($fieldKey, $msg = '')
set validation error message a field
Parameters
string $fieldKey Key of attribute
string $msg the field error message
Returns
null
Definition at line 7840 of file commonobject.class.php.
setMulticurrencyCode()
CommonObject::setMulticurrencyCode ($code)
Change the multicurrency code.
Parameters
string $code multicurrency code
Returns
int >0 if OK, <0 if KO
Definition at line 2468 of file commonobject.class.php.
setMulticurrencyRate()
CommonObject::setMulticurrencyRate ($rate, $mode = 1)
Change the multicurrency rate.
Parameters
double $rate multicurrency rate
int $mode mode 1 : amounts in company currency will be recalculated, mode 2 : amounts in foreign currency will be recalculated
Returns
int >0 if OK, <0 if KO
Definition at line 2506 of file commonobject.class.php.
setPaymentMethods()
CommonObject::setPaymentMethods ($id)
Change the payments methods.
Parameters
int $id Id of new payment method
Returns
int >0 if OK, <0 if KO
Definition at line 2402 of file commonobject.class.php.
setPaymentTerms()
CommonObject::setPaymentTerms ($id, $deposit_percent = null)
Change the payments terms.
Parameters
int $id Id of new payment terms
string $deposit_percent % of deposit if needed by payment terms
Returns
int >0 if OK, <0 if KO
Definition at line 2708 of file commonobject.class.php.
setProject()
CommonObject::setProject ($projectid, $notrigger = 0)
Link element with a project.
Parameters
int $projectid Project id to link element to
int $notrigger Disable the trigger
Returns
int <0 if KO, >0 if OK
Definition at line 2331 of file commonobject.class.php.
setRetainedWarrantyPaymentTerms()
CommonObject::setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
Parameters
int $id Id of new payment terms
Returns
int >0 if OK, <0 if KO
Definition at line 2804 of file commonobject.class.php.
setSaveQuery()
CommonObject::setSaveQuery () protected
Function to prepare a part of the query for insert by returning an array with all properties of object.
Note $this->${field} are set by the page that make the createCommon() or the updateCommon(). $this->${field} should be a clean and string value (so date are formated for SQL insert).
Returns
array Array with all values of each properties to update
Definition at line 8969 of file commonobject.class.php.
setShippingMethod()
CommonObject::setShippingMethod ($shipping_method_id, $notrigger = false, $userused = null)
Change the shipping method.
Parameters
int $shipping_method_id Id of shipping method
bool $notrigger false=launch triggers after, true=disable triggers
User $userused Object user
Returns
int 1 if OK, 0 if KO
Definition at line 2866 of file commonobject.class.php.
setStatusCommon()
CommonObject::setStatusCommon ($user, $status, $notrigger = 0, $triggercode = '')
Set to a status.
Parameters
User $user Object user that modify
int $status New status to set (often a constant like self::STATUS_XXX)
int $notrigger 1=Does not execute triggers, 0=Execute triggers
string $triggercode Trigger code to use
Returns
int <0 if KO, >0 if OK
Definition at line 9800 of file commonobject.class.php.
Referenced by AssetModel\cancel(), BOM\cancel(), Availabilities\cancel(), Booking\cancel(), ConferenceOrBooth\cancel(), ConferenceOrBoothAttendee\cancel(), Evaluation\cancel(), Evaluationline\cancel(), Job\cancel(), Position\cancel(), Skill\cancel(), Skilldet\cancel(), SkillRank\cancel(), KnowledgeRecord\cancel(), MyObject\cancel(), Mo\cancel(), Partnership\cancel(), ProductFournisseurPrice\cancel(), StockTransfer\cancel(), StockTransferLine\cancel(), RecruitmentCandidature\cancel(), RecruitmentJobPosition\cancel(), Target\cancel(), AssetModel\reopen(), BOM\reopen(), Availabilities\reopen(), Booking\reopen(), Don\reopen(), ConferenceOrBooth\reopen(), ConferenceOrBoothAttendee\reopen(), Evaluation\reopen(), Evaluationline\reopen(), Job\reopen(), Position\reopen(), Skill\reopen(), Skilldet\reopen(), SkillRank\reopen(), KnowledgeRecord\reopen(), MyObject\reopen(), Mo\reopen(), Partnership\reopen(), ProductFournisseurPrice\reopen(), StockTransfer\reopen(), StockTransferLine\reopen(), RecruitmentCandidature\reopen(), RecruitmentJobPosition\reopen(), Target\reopen(), Workstation\setDisabled(), AssetModel\setDraft(), BOM\setDraft(), Availabilities\setDraft(), Booking\setDraft(), ConferenceOrBooth\setDraft(), ConferenceOrBoothAttendee\setDraft(), Evaluation\setDraft(), Evaluationline\setDraft(), Job\setDraft(), Position\setDraft(), Skill\setDraft(), Skilldet\setDraft(), SkillRank\setDraft(), KnowledgeRecord\setDraft(), MyObject\setDraft(), Mo\setDraft(), Partnership\setDraft(), ProductFournisseurPrice\setDraft(), StockTransfer\setDraft(), StockTransferLine\setDraft(), RecruitmentCandidature\setDraft(), RecruitmentJobPosition\setDraft(), Target\setDraft(), and Workstation\setEnabled().
setStatut()
CommonObject::setStatut ($status, $elementId = null, $elementType = '', $trigkey = '', $fieldstatus = 'fk_statut')
Set status of an object.
Parameters
int $status Status to set
int $elementId Id of element to force (use this->id by default if null)
string $elementType Type of element to force (use this->table_element by default)
string $trigkey Trigger key to use for trigger. Use '' means automatic but it is not recommended and is deprecated.
string $fieldstatus Name of status field in this->table_element
Returns
int <0 if KO, >0 if OK
Definition at line 4354 of file commonobject.class.php.
setTransportMode()
CommonObject::setTransportMode ($id)
Change the transport mode methods.
Parameters
int $id Id of transport mode
Returns
int >0 if OK, <0 if KO
Definition at line 2763 of file commonobject.class.php.
setUpperOrLowerCase()
CommonObject::setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
Returns
void;
Definition at line 745 of file commonobject.class.php.
setValueFrom()
CommonObject::setValueFrom ($field, $value, $table = '', $id = null, $format = '', $id_field = '', $fuser = null, $trigkey = '', $fk_user_field = 'fk_user_modif')
Setter generic.
Update a specific field into database. Warning: Trigger is run only if param trigkey is provided.
Parameters
string $field Field to update
mixed $value New value
string $table To force other table element or element line (should not be used)
int $id To force other object id (should not be used)
string $format Data format ('text', 'date'). 'text' is used if not defined
string $id_field To force rowid field name. 'rowid' is used if not defined
User | string $fuser Update the user of last update field with this user. If not provided, current user is used except if value is 'none'
string $trigkey Trigger key to run (in most cases something like 'XXX_MODIFY')
string $fk_user_field Name of field to save user id making change
Returns
int <0 if KO, >0 if OK
See also
updateExtraField()
Definition at line 2026 of file commonobject.class.php.
setValuesForExtraLanguages()
CommonObject::setValuesForExtraLanguages ($onlykey = '')
Fill array_options property of object by extrafields value (using for data sent by forms)
Parameters
string $onlykey Only the following key is filled. When we make update of only one language field ($action = 'update_languages'), calling page must set this to avoid to have other languages being reset.
Returns
int 1 if array_options set, 0 if no value, -1 if error (field required missing for example)
Definition at line 5893 of file commonobject.class.php.
setVarsFromFetchObj()
CommonObject::setVarsFromFetchObj (& $obj)
Function to load data from a SQL pointer into properties of current object $this.
Parameters
stdClass $obj Contain data of object from database
Returns
void
Definition at line 9037 of file commonobject.class.php.
setWarehouse()
CommonObject::setWarehouse ($warehouse_id)
Change the warehouse.
Parameters
int $warehouse_id Id of warehouse
Returns
int 1 if OK, 0 if KO
Definition at line 2924 of file commonobject.class.php.
show_photos()
CommonObject::show_photos ($modulepart, $sdir, $size = 0, $nbmax = 0, $nbbyrow = 5, $showfilename = 0, $showaction = 0, $maxHeight = 120, $maxWidth = 160, $nolink = 0, $notitle = 0, $usesharelink = 0)
Show photos of an object (nbmax maximum), into several columns.
Parameters
string $modulepart 'product', 'ticket', ...
string $sdir Directory to scan (full absolute path)
int $size 0=original size, 1='small' use thumbnail if possible
int $nbmax Nombre maximum de photos (0=pas de max)
int $nbbyrow Number of image per line or -1 to use div separator or 0 to use no separator. Used only if size=1 or 'small'.
int $showfilename 1=Show filename
int $showaction 1=Show icon with action links (resize, delete)
int $maxHeight Max height of original image when size='small' (so we can use original even if small requested). If 0, always use 'small' thumb image.
int $maxWidth Max width of original image when size='small'
int $nolink Do not add a href link to view enlarged imaged into a new tab
int $notitle Do not add title tag on image
int $usesharelink Use the public shared link of image (if not available, the 'nophoto' image will be shown instead)
Returns
string Html code to show photo. Number of photos shown is saved in this->nbphoto
Definition at line 8585 of file commonobject.class.php.
showInputField()
CommonObject::showInputField ($val, $key, $value, $moreparam = '', $keysuffix = '', $keyprefix = '', $morecss = 0, $nonewbutton = 0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
Parameters
array $val Array of properties for field to show (used only if ->fields not defined)
string $key Key of attribute
string | array $value Preselected value to show (for date type it must be in timestamp format, for amount or price it must be a php numeric value, for array type must be array)
string $moreparam To add more parameters on html input tag
string $keysuffix Prefix string to add into name and id of field (can be used to avoid duplicate names)
string $keyprefix Suffix string to add into name and id of field (can be used to avoid duplicate names)
string | int $morecss Value for css to define style/length of field. May also be a numeric.
int $nonewbutton Force to not show the new button on field that are links to object
Returns
string
Reimplemented in Position.
Definition at line 6767 of file commonobject.class.php.
showOptionals()
CommonObject::showOptionals ($extrafields, $mode = 'view', $params = null, $keysuffix = '', $keyprefix = '', $onetrtd = 0, $display_type = 'card')
Function to show lines of extrafields with output datas.
This function is responsible to output the
and
according to correct number of columns received into $params['colspan'] or
according to $display_type
Parameters
Extrafields $extrafields Extrafield Object
string $mode Show output ('view') or input ('create' or 'edit') for extrafield
array $params Optional parameters. Example: array('style'=>'class="oddeven"', 'colspan'=>$colspan)
string $keysuffix Suffix string to add after name and id of field (can be used to avoid duplicate names)
string $keyprefix Prefix string to add before name and id of field (can be used to avoid duplicate names)
string $onetrtd All fields in same tr td. Used by objectline_create.tpl.php for example.
string $display_type "card" for form display, "line" for document line display (extrafields on propal line, order line, etc...)
Returns
string String with html content to show
Definition at line 8057 of file commonobject.class.php.
swapContactStatus()
CommonObject::swapContactStatus ($rowid)
Update status of a contact linked to object.
Parameters
int $rowid Id of link between object and contact
Returns
int <0 if KO, >=0 if OK
Definition at line 1457 of file commonobject.class.php.
trimParameters()
CommonObject::trimParameters ($parameters)
Trim object parameters.
Parameters
string[] $parameters array of parameters to trim
Returns
void
Definition at line 9915 of file commonobject.class.php.
update_contact()
CommonObject::update_contact ($rowid, $statut, $type_contact_id = 0, $fk_socpeople = 0)
Update a link to contact line.
Parameters
int $rowid Id of line contact-element
int $statut New status of link
int $type_contact_id Id of contact type (not modified if 0)
int $fk_socpeople Id of soc_people to update (not modified if 0)
Returns
int <0 if KO, >= 0 if OK
Definition at line 1250 of file commonobject.class.php.
update_note()
CommonObject::update_note ($note, $suffix = '')
Update note of element.
Parameters
string $note New value for note
string $suffix '', '_public' or '_private'
Returns
int <0 if KO, >0 if OK
Definition at line 3448 of file commonobject.class.php.
update_note_public()
CommonObject::update_note_public ($note)
Update public note (kept for backward compatibility)
Parameters
string $note New value for note
Returns
int <0 if KO, >0 if OK
Deprecated:
See also
update_note()
Definition at line 3508 of file commonobject.class.php.
update_price()
CommonObject::update_price ($exclspec = 0, $roundingadjust = 'none', $nodatabaseupdate = 0, $seller = null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
Must be called at end of methods addline or updateline.
Parameters
int $exclspec >0 = Exclude special product (product_type=9)
string $roundingadjust 'none'=Do nothing, 'auto'=Use default method (MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND if defined, or '0'), '0'=Force mode Total of rounding, '1'=Force mode Rounding of total
int $nodatabaseupdate 1=Do not update database total fields of the main object. Update only properties in memory. Can be used to save SQL when this method is called several times, so we can do it only once at end.
Societe $seller If roundingadjust is '0' or '1' or maybe 'auto', it means we recalculate total for lines before calculating total for object and for this, we need seller object (used to analyze lines to check corrupted data).
Returns
int <0 if KO, >0 if OK
Definition at line 3525 of file commonobject.class.php.
update_ref_ext()
CommonObject::update_ref_ext ($ref_ext)
Update external ref of element.
Parameters
string $ref_ext Update field ref_ext
Returns
int <0 if KO, >0 if OK
Definition at line 3418 of file commonobject.class.php.
updateCommon()
CommonObject::updateCommon (User $user, $notrigger = false)
Update object into database.
Parameters
User $user User that modifies
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 9418 of file commonobject.class.php.
Referenced by AssetModel\update(), BOM\update(), BOMLine\update(), Availabilities\update(), Booking\update(), ActionCommReminder\update(), CashControl\update(), DefaultValues\update(), EmailSenderProfile\update(), EmailCollectorAction\update(), EmailCollectorFilter\update(), ConferenceOrBoothAttendee\update(), ExpenseReportIk\update(), ExpenseReportRule\update(), Evaluation\update(), Evaluationline\update(), Job\update(), Position\update(), Skill\update(), Skilldet\update(), SkillRank\update(), KnowledgeRecord\update(), MyObject\update(), MoLine\update(), PartnershipType\update(), ProductFournisseurPrice\update(), Inventory\update(), InventoryLine\update(), StockTransferLine\update(), RecruitmentCandidature\update(), RecruitmentJobPosition\update(), CompanyPaymentMode\update(), SocieteAccount\update(), CTicketCategory\update(), Target\update(), and Hook\update().
updateExtraField()
CommonObject::updateExtraField ($key, $trigger = null, $userused = null)
Update 1 extra field value for the current object.
Keep other fields unchanged. Data to describe values to update are stored into $this->array_options=array('options_codeforfield1'=>'valueforfield1', 'options_codeforfield2'=>'valueforfield2', ...)
Parameters
string $key Key of the extrafield to update (without starting 'options_')
string $trigger If defined, call also the trigger (for example COMPANY_MODIFY)
User $userused Object user
Returns
int -1=error, O=did nothing, 1=OK
See also
updateExtraLanguages(), insertExtraFields(), deleteExtraFields(), setValueFrom()
Definition at line 6536 of file commonobject.class.php.
updateExtraLanguages()
CommonObject::updateExtraLanguages ($key, $trigger = null, $userused = null)
Update an extra language value for the current object.
Data to describe values to update are stored into $this->array_options=array('options_codeforfield1'=>'valueforfield1', 'options_codeforfield2'=>'valueforfield2', ...)
Parameters
string $key Key of the extrafield (without starting 'options_')
string $trigger If defined, call also the trigger (for example COMPANY_MODIFY)
User $userused Object user
Returns
int -1=error, O=did nothing, 1=OK
See also
updateExtraFields(), insertExtraLanguages()
Definition at line 6735 of file commonobject.class.php.
updateLineDown()
CommonObject::updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
Parameters
int $rowid Id of line
int $rang Position
int $max Max
Returns
void
Definition at line 3296 of file commonobject.class.php.
updateLineUp()
CommonObject::updateLineUp ($rowid, $rang)
Update position of line up (rang)
Parameters
int $rowid Id of line
int $rang Position
Returns
void
Definition at line 3265 of file commonobject.class.php.
updateObjectLinked()
CommonObject::updateObjectLinked ($sourceid = null, $sourcetype = '', $targetid = null, $targettype = '', $f_user = null, $notrigger = 0)
Update object linked of a current object.
Parameters
int $sourceid Object source id
string $sourcetype Object source type
int $targetid Object target id
string $targettype Object target type
User $f_user User that create
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int >0 if OK, <0 if KO
See also
add_object_linked(), fetObjectLinked(), deleteObjectLinked()
Definition at line 4148 of file commonobject.class.php.
updateRangOfLine()
CommonObject::updateRangOfLine ($rowid, $rang)
Update position of line (rang)
Parameters
int $rowid Id of line
int $rang Position
Returns
int <0 if KO, >0 if OK
Definition at line 3219 of file commonobject.class.php.
validateField()
array To store error results of CommonObject::validateField ($val, $fieldKey, $fieldValue)
Return validation test result for a field.
Parameters
array $val Array of properties of field to show
string $fieldKey Key of attribute
string $fieldValue value of attribute
Returns
bool return false if fail true on success, see $this->error for error message
Definition at line 7870 of file commonobject.class.php.
Member Data Documentation
$fk_projet
CommonObject::$fk_projet
Deprecated:
See also
$fk_project
Definition at line 194 of file commonobject.class.php.
$note
CommonObject::$note
Deprecated:
See also
$note_private
Definition at line 445 of file commonobject.class.php.
$projet
CommonObject::$projet
Deprecated:
See also
project
Definition at line 188 of file commonobject.class.php.
The documentation for this class was generated from the following file:
htdocs/core/class/commonobject.class.php