dolibarr: modGeneratePassPerso Class Reference
modGeneratePassPerso Class Reference
Class to generate a password according to personal rules.
Public Member Functions
__construct ($db, $conf, $langs, $user)
Constructor.
getDescription ()
Return description of module.
getExample ()
Return an example of password generated by this module.
getNewGeneratedPassword ()
Build new password.
validatePassword ($password)
Validate a password.
consecutiveIterationSameCharacter ($password)
Check the consecutive iterations of the same character.
Public Member Functions inherited from ModeleGenPassword
isEnabled ()
Return if a module can be used or not.
Private Member Functions
initAll ()
Init the property ->All and clean ->Maj, ->Min, ->Nb and ->Spe with list of valid chars.
Detailed Description
Class to generate a password according to personal rules.
Definition at line 33 of file modGeneratePassPerso.class.php.
Constructor & Destructor Documentation
__construct()
modGeneratePassPerso::__construct ($db, $conf, $langs, $user)
Constructor.
Parameters
DoliDB $db Database handler
Conf $conf Handler de conf
Translate $langs Handler de langue
User $user Handler du user connecte
Definition at line 92 of file modGeneratePassPerso.class.php.
Member Function Documentation
consecutiveIterationSameCharacter()
modGeneratePassPerso::consecutiveIterationSameCharacter ($password)
Check the consecutive iterations of the same character.
Parameters
string $password Password to check
Returns
bool False if the number doesn't match the maximum consecutive value allowed.
Definition at line 263 of file modGeneratePassPerso.class.php.
getDescription()
modGeneratePassPerso::getDescription ()
Return description of module.
Returns
string Description of text
Reimplemented from ModeleGenPassword.
Definition at line 145 of file modGeneratePassPerso.class.php.
getExample()
modGeneratePassPerso::getExample ()
Return an example of password generated by this module.
Returns
string Example of password
Reimplemented from ModeleGenPassword.
Definition at line 156 of file modGeneratePassPerso.class.php.
References getNewGeneratedPassword().
getNewGeneratedPassword()
modGeneratePassPerso::getNewGeneratedPassword ()
Build new password.
Returns
string Return a new generated password
Reimplemented from ModeleGenPassword.
Definition at line 166 of file modGeneratePassPerso.class.php.
References initAll().
Referenced by getExample().
initAll()
modGeneratePassPerso::initAll () private
Init the property ->All and clean ->Maj, ->Min, ->Nb and ->Spe with list of valid chars.
Returns
void
Definition at line 127 of file modGeneratePassPerso.class.php.
Referenced by getNewGeneratedPassword().
validatePassword()
modGeneratePassPerso::validatePassword ($password)
Validate a password.
This function is called by User->setPassword() and internally to validate that the password matches the constraints.
Parameters
string $password Password to check
Returns
int 0 if KO, >0 if OK
Reimplemented from ModeleGenPassword.
Definition at line 207 of file modGeneratePassPerso.class.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/security/generate/modGeneratePassPerso.class.php