dolibarr: DoliDBPgsql Class Reference
DoliDBPgsql Class Reference
Class to drive a Postgresql database for Dolibarr.
Public Member Functions
__construct ($type, $host, $user, $pass, $name='', $port=0)
Constructor.
select_db ($database)
Select a database Ici postgresql n'a aucune fonction equivalente de mysql_select_db On compare juste manuellement si la database choisie est bien celle activee par la connexion.
connect ($host, $login, $passwd, $name, $port=0)
Connexion to server.
getVersion ()
Return version of database server.
getDriverInfo ()
Return version of database client driver.
close ()
Close database connexion.
query ($query, $usesavepoint=0, $type='auto', $result_mode=0)
Convert request to PostgreSQL syntax, execute it and return the resultset.
fetch_object ($resultset)
Returns the current line (as an object) for the resultset cursor.
fetch_array ($resultset)
Return datas as an array.
fetch_row ($resultset)
Return datas as an array.
num_rows ($resultset)
Return number of lines for result of a SELECT.
affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
free ($resultset=null)
Libere le dernier resultset utilise sur cette connexion.
plimit ($limit=0, $offset=0)
Define limits and offset of request.
escape ($stringtoencode)
Escape a string to insert data.
escapeforlike ($stringtoencode)
Escape a string to insert data into a like.
ifsql ($test, $resok, $resko)
Format a SQL IF.
regexpsql ($subject, $pattern, $sqlstring=false)
Format a SQL REGEXP.
errno ()
Renvoie le code erreur generique de l'operation precedente.
error ()
Renvoie le texte de l'erreur pgsql de l'operation precedente.
last_insert_id ($tab, $fieldid='rowid')
Get last ID after an insert INSERT.
encrypt ($fieldorvalue, $withQuotes=1)
Encrypt sensitive data in database Warning: This function includes the escape and add the SQL simple quotes on strings.
decrypt ($value)
Decrypt sensitive data in database.
DDLGetConnectId ()
Return connexion ID.
DDLCreateDb ($database, $charset='', $collation='', $owner='')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
DDLListTables ($database, $table='')
List tables into a database.
DDLInfoTable ($table)
List information of columns into a table.
DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys=null, $fulltext_keys=null, $keys=null)
Create a table into database.
DDLDropTable ($table)
Drop a table into database.
DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user to connect to database.
DDLDescTable ($table, $field="")
Return a pointer of line with description of a table or field.
DDLAddField ($table, $field_name, $field_desc, $field_position="")
Create a new field into table.
DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
DDLDropField ($table, $field_name)
Drop a field from table.
getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
getDefaultCollationDatabase ()
Return collation used in database.
getListOfCollation ()
Return list of available collation that can be used for database.
getPathOfDump ()
Return full path of dump program.
getPathOfRestore ()
Return full path of restore program.
getServerParametersValues ($filter='')
Return value of server parameters.
getServerStatusValues ($filter='')
Return value of server status.
Public Member Functions inherited from DoliDB
prefix ()
Return the DB prefix found into prefix_db (if it was set manually by doing $dbhandler->prefix_db=...).
hintindex ($nameofindex)
Return SQL string to force an index.
idate ($param, $gm='tzserver')
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
lasterrno ()
Return last error code.
sanitize ($stringtosanitize, $allowsimplequote=0, $allowsequals=0)
Sanitize a string for SQL forging.
begin ($textinlog='')
Start transaction.
commit ($log='')
Validate a database transaction.
rollback ($log='')
Cancel a transaction and go back to initial data values.
getVersionArray ()
Return version of database server into an array.
lastquery ()
Return last request executed with query()
order ($sortfield=null, $sortorder=null)
Define sort criteria of request.
lasterror ()
Return last error label.
jdate ($string, $gm='tzserver')
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with server TZ = +1 and $gm='tzserver' 19700101020000 -> 7200 whaterver is server TZ if $gm='gmt'.
lastqueryerror ()
Return last query in error.
getRow ($sql)
Return first result from query as object Note : This method executes a given SQL query and retrieves the first row of results as an object.
getRows ($sql)
Return all results from query as an array of objects Note : This method executes a given SQL query and retrieves all row of results as an array of objects.
Public Member Functions inherited from Database
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
sanitize ($stringtosanitize)
Sanitize a string for SQL forging.
Static Public Member Functions
static convertSQLFromMysql ($line, $type='auto', $unescapeslashquot=false)
Convert a SQL request in Mysql syntax to native syntax.
Static Public Member Functions inherited from Database
static convertSQLFromMysql ($line, $type='ddl')
Convert a SQL request in Mysql syntax to native syntax.
Public Attributes
$type = 'pgsql'
Database type.
const LABEL = 'PostgreSQL'
Database label.
$forcecharset = 'UTF8'
Charset.
$forcecollate = ''
Collate used to force collate when creating database.
const VERSIONMIN = '9.0.0'
Version min database.
Detailed Description
Class to drive a Postgresql database for Dolibarr.
Definition at line 36 of file pgsql.class.php.
Constructor & Destructor Documentation
__construct()
DoliDBPgsql::__construct ($type, $host, $user, $pass, $name = '', $port = 0)
Constructor.
This create an opened connexion to a database server and eventually to a database
Parameters
string $type Type of database (mysql, pgsql...)
string $host Address of database server
string $user Nom de l'utilisateur autorise
string $pass Mot de passe
string $name Nom de la database
int $port Port of database server
Definition at line 71 of file pgsql.class.php.
Member Function Documentation
affected_rows()
DoliDBPgsql::affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
Parameters
resource $resultset Result set of request
Returns
int Nb of lines
See also
num_rows()
Implements Database.
Definition at line 657 of file pgsql.class.php.
close()
DoliDBPgsql::close ()
Close database connexion.
Returns
boolean True if disconnect successfull, false otherwise
See also
connect()
Implements Database.
Definition at line 487 of file pgsql.class.php.
References db, and dol_syslog().
connect()
DoliDBPgsql::connect ($host, $login, $passwd, $name, $port = 0)
Connexion to server.
Parameters
string $host Database server host
string $login Login
string $passwd Password
string $name Name of database (not used for mysql, used for pgsql)
integer $port Port of database server
Returns
bool|resource Database access handler
See also
close()
Implements Database.
Definition at line 402 of file pgsql.class.php.
convertSQLFromMysql()
static DoliDBPgsql::convertSQLFromMysql ($line, $type = 'auto', $unescapeslashquot = false) static
Convert a SQL request in Mysql syntax to native syntax.
Parameters
string $line SQL request line to convert
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
bool $unescapeslashquot Unescape slash quote with quote quote
Returns
string SQL request line converted
Definition at line 152 of file pgsql.class.php.
DDLAddField()
DoliDBPgsql::DDLAddField ($table, $field_name, $field_desc, $field_position = "")
Create a new field into table.
Parameters
string $table Name of table
string $field_name Name of field to add
string $field_desc Tableau associatif de description du champ a inserer[nom du parametre][valeur du parametre]
string $field_position Optionnel ex.: "after champtruc"
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 1178 of file pgsql.class.php.
DDLCreateDb()
DoliDBPgsql::DDLCreateDb ($database, $charset = '', $collation = '', $owner = '')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
Parameters
string $database Database name to create
string $charset Charset used to store data
string $collation Charset used to sort data
string $owner Username of database owner
Returns
false|resource resource defined if OK, null if KO
Implements Database.
Definition at line 932 of file pgsql.class.php.
References $forcecharset, and $forcecollate.
DDLCreateTable()
DoliDBPgsql::DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys = null, $fulltext_keys = null, $keys = null)
Create a table into database.
Parameters
string $table Nom de la table
array $fields Tableau associatif [nom champ][tableau des descriptions]
string $primary_key Nom du champ qui sera la clef primaire
string $type Type de la table
array $unique_keys Tableau associatifs Nom de champs qui seront clef unique => valeur
array $fulltext_keys Tableau des Nom de champs qui seront indexes en fulltext
array $keys Tableau des champs cles noms => valeur
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 1033 of file pgsql.class.php.
DDLCreateUser()
DoliDBPgsql::DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user to connect to database.
Parameters
string $dolibarr_main_db_host Ip server
string $dolibarr_main_db_user Name of user to create
string $dolibarr_main_db_pass Password of user to create
string $dolibarr_main_db_name Database name where user must be granted
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 1131 of file pgsql.class.php.
DDLDescTable()
DoliDBPgsql::DDLDescTable ($table, $field = "")
Return a pointer of line with description of a table or field.
Parameters
string $table Name of table
string $field Optionnel : Name of field if we want description of field
Returns
false|resource Resultset x (x->attname)
Implements Database.
Definition at line 1154 of file pgsql.class.php.
DDLDropField()
DoliDBPgsql::DDLDropField ($table, $field_name)
Drop a field from table.
Parameters
string $table Name of table
string $field_name Name of field to drop
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 1267 of file pgsql.class.php.
DDLDropTable()
DoliDBPgsql::DDLDropTable ($table)
Drop a table into database.
Parameters
string $table Name of table
Returns
int <0 if KO, >=0 if OK
Implements Database.
Definition at line 1107 of file pgsql.class.php.
DDLGetConnectId()
DoliDBPgsql::DDLGetConnectId ()
Return connexion ID.
Returns
string Id connexion
Implements Database.
Definition at line 912 of file pgsql.class.php.
DDLInfoTable()
DoliDBPgsql::DDLInfoTable ($table)
List information of columns into a table.
Parameters
string $table Name of table
Returns
array Tableau des informations des champs de la table
Implements Database.
Definition at line 988 of file pgsql.class.php.
DDLListTables()
DoliDBPgsql::DDLListTables ($database, $table = '')
List tables into a database.
Parameters
string $database Name of database
string $table Name of table filter ('xxx')
Returns
array List of tables in an array
Implements Database.
Definition at line 960 of file pgsql.class.php.
DDLUpdateField()
DoliDBPgsql::DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
Parameters
string $table Name of table
string $field_name Name of field to modify
string $field_desc Array with description of field format
Returns
int <0 if KO, >0 if OK
Implements Database.
Definition at line 1224 of file pgsql.class.php.
decrypt()
DoliDBPgsql::decrypt ($value)
Decrypt sensitive data in database.
Parameters
int $value Value to decrypt
Returns
string Decrypted value if used
Implements Database.
Definition at line 891 of file pgsql.class.php.
encrypt()
DoliDBPgsql::encrypt ($fieldorvalue, $withQuotes = 1)
Encrypt sensitive data in database Warning: This function includes the escape and add the SQL simple quotes on strings.
Parameters
string $fieldorvalue Field name or value to encrypt
int $withQuotes Return string including the SQL simple quotes. This param must always be 1 (Value 0 is bugged and deprecated).
Returns
string XXX(field) or XXX('value') or field or 'value'
Implements Database.
Definition at line 870 of file pgsql.class.php.
errno()
DoliDBPgsql::errno ()
Renvoie le code erreur generique de l'operation precedente.
Returns
string Error code (Exemples: DB_ERROR_TABLE_ALREADY_EXISTS, DB_ERROR_RECORD_ALREADY_EXISTS...)
Implements Database.
Definition at line 771 of file pgsql.class.php.
References db.
error()
DoliDBPgsql::error ()
Renvoie le texte de l'erreur pgsql de l'operation precedente.
Returns
string Error text
Implements Database.
Definition at line 835 of file pgsql.class.php.
References db.
escape()
DoliDBPgsql::escape ($stringtoencode)
Escape a string to insert data.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implements Database.
Definition at line 719 of file pgsql.class.php.
escapeforlike()
DoliDBPgsql::escapeforlike ($stringtoencode)
Escape a string to insert data into a like.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implements Database.
Definition at line 730 of file pgsql.class.php.
fetch_array()
DoliDBPgsql::fetch_array ($resultset)
Return datas as an array.
Parameters
resource $resultset Resultset of request
Returns
false|array Array
Implements Database.
Definition at line 604 of file pgsql.class.php.
fetch_object()
DoliDBPgsql::fetch_object ($resultset)
Returns the current line (as an object) for the resultset cursor.
Parameters
resource $resultset Curseur de la requete voulue
Returns
false|object Object result line or false if KO or end of cursor
Implements Database.
Definition at line 587 of file pgsql.class.php.
fetch_row()
DoliDBPgsql::fetch_row ($resultset)
Return datas as an array.
Parameters
resource $resultset Resultset of request
Returns
false|array Array
Implements Database.
Definition at line 621 of file pgsql.class.php.
free()
DoliDBPgsql::free ($resultset = null)
Libere le dernier resultset utilise sur cette connexion.
Parameters
resource $resultset Result set of request
Returns
void
Implements Database.
Definition at line 676 of file pgsql.class.php.
getDefaultCharacterSetDatabase()
DoliDBPgsql::getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
Returns
string Charset
Implements Database.
Definition at line 1285 of file pgsql.class.php.
References $resql, and query().
getDefaultCollationDatabase()
DoliDBPgsql::getDefaultCollationDatabase ()
Return collation used in database.
Returns
string Collation value
Implements Database.
Definition at line 1324 of file pgsql.class.php.
References $resql, and query().
getDriverInfo()
DoliDBPgsql::getDriverInfo ()
Return version of database client driver.
Returns
string Version string
Implements Database.
Definition at line 476 of file pgsql.class.php.
getListOfCharacterSet()
DoliDBPgsql::getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
Returns
array List of Charset
Implements Database.
Definition at line 1301 of file pgsql.class.php.
References $resql, and query().
getListOfCollation()
DoliDBPgsql::getListOfCollation ()
Return list of available collation that can be used for database.
Returns
array Liste of Collation
Implements Database.
Definition at line 1340 of file pgsql.class.php.
References $resql, and query().
getPathOfDump()
DoliDBPgsql::getPathOfDump ()
Return full path of dump program.
Returns
string Full path of dump program
Implements Database.
Definition at line 1362 of file pgsql.class.php.
References $resql, and query().
getPathOfRestore()
DoliDBPgsql::getPathOfRestore ()
Return full path of restore program.
Returns
string Full path of restore program
Implements Database.
Definition at line 1386 of file pgsql.class.php.
References $resql, and query().
getServerParametersValues()
DoliDBPgsql::getServerParametersValues ($filter = '')
Return value of server parameters.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implements Database.
Definition at line 1414 of file pgsql.class.php.
getServerStatusValues()
DoliDBPgsql::getServerStatusValues ($filter = '')
Return value of server status.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implements Database.
Definition at line 1438 of file pgsql.class.php.
getVersion()
DoliDBPgsql::getVersion ()
Return version of database server.
Returns
string Version string
Implements Database.
Definition at line 461 of file pgsql.class.php.
References $resql, and query().
ifsql()
DoliDBPgsql::ifsql ($test, $resok, $resko)
Format a SQL IF.
Parameters
string $test Test string (example: 'cd.statut=0', 'field IS NULL')
string $resok resultat si test egal
string $resko resultat si test non egal
Returns
string chaine formate SQL
Reimplemented from DoliDB.
Definition at line 743 of file pgsql.class.php.
last_insert_id()
DoliDBPgsql::last_insert_id ($tab, $fieldid = 'rowid')
Get last ID after an insert INSERT.
Parameters
string $tab Table name concerned by insert. Ne sert pas sous MySql mais requis pour compatibilite avec Postgresql
string $fieldid Field name
Returns
string Id of row
Implements Database.
Definition at line 848 of file pgsql.class.php.
num_rows()
DoliDBPgsql::num_rows ($resultset)
Return number of lines for result of a SELECT.
Parameters
resource $resultset Resulset of requests
Returns
int Nb of lines, -1 on error
See also
affected_rows()
Implements Database.
Definition at line 639 of file pgsql.class.php.
plimit()
DoliDBPgsql::plimit ($limit = 0, $offset = 0)
Define limits and offset of request.
Parameters
int $limit Maximum number of lines returned (-1=conf->liste_limit, 0=no limit)
int $offset Numero of line from where starting fetch
Returns
string String with SQL syntax to add a limit and offset
Reimplemented from DoliDB.
Definition at line 696 of file pgsql.class.php.
query()
resource boolean Resultset of last DoliDBPgsql::query ($query, $usesavepoint = 0, $type = 'auto', $result_mode = 0)
Convert request to PostgreSQL syntax, execute it and return the resultset.
Parameters
string $query SQL query string
int $usesavepoint 0=Default mode, 1=Run a savepoint before and a rollback to savepoint if error (this allow to have some request with errors inside global transactions).
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
int $result_mode Result mode (not used with pgsql)
Returns
bool|resource Resultset of answer
Implements Database.
Definition at line 508 of file pgsql.class.php.
Referenced by getDefaultCharacterSetDatabase(), getDefaultCollationDatabase(), getListOfCharacterSet(), getListOfCollation(), getPathOfDump(), getPathOfRestore(), and getVersion().
regexpsql()
DoliDBPgsql::regexpsql ($subject, $pattern, $sqlstring = false)
Format a SQL REGEXP.
Parameters
string $subject string tested
string $pattern SQL pattern to match
string $sqlstring whether or not the string being tested is an SQL expression
Returns
string SQL string
Reimplemented from DoliDB.
Definition at line 756 of file pgsql.class.php.
select_db()
DoliDBPgsql::select_db ($database)
Select a database Ici postgresql n'a aucune fonction equivalente de mysql_select_db On compare juste manuellement si la database choisie est bien celle activee par la connexion.
Parameters
string $database Name of database
Returns
bool true if OK, false if KO
Implements Database.
Definition at line 381 of file pgsql.class.php.
The documentation for this class was generated from the following file:
htdocs/core/db/pgsql.class.php