fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      ref: '4.1.0'
    'concat':
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      ref: '1.0.1'
  symlinks:
    supervisord: "#{source_dir}"