name    'ajcrowe-supervisord'
version '0.4.0'
source 'git@github.com/ajcrowe/puppet-supervisord.git'
author 'Alex Crowe'
license 'Apache License, Version 2.0'
summary 'supervisord class and functions'
description 'supervisord class and functions'
project_page 'https://github.com/ajcrowe/puppet-supervisord'

dependency 'puppetlabs/concat', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
