# Action to prepare the github action
# Go on Dolibarr - Settings - Developer settings - Enter a name + webhook to disable + Permissions (see app test) + Can install by any account
# Click on generate the private keys
# Click on Install application - choose user of the Organization
# Go on Organisation - Secret and variables and create a secret PR18_SECRET_KEY and copy the content of received private key. Choose the repository access to "Repository Dolibarr".
# Go on Organisation - Secret and variables and create a variable PR18_APP_ID and copy the ID of the previously create ID. Choose the repository access to "Repository Dolibarr".
#

name: Set reviewer and label for v18
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - "18.0"
  push:
    branches:
      - "18.0"


permissions:
  pull-requests: write
  issues: write
  
jobs:
  assign-and-label-v18:
    runs-on: ubuntu-latest

    steps:
    #- name: Install GitHub CLI
    #  run: sudo apt-get install gh

    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.PR18_APP_ID }}
        private-key: ${{ secrets.PR18_SECRET_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Assign Tag
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        url: ${{ github.event.pull_request.html_url }}
      run: |
        echo "env.url=${{env.url}}"
          gh pr edit "${{env.url}}" --add-label "Issue for v18 maintenance Team"

    - name: Assign reviewer 1
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        url: ${{ github.event.pull_request.html_url }}
      run: |
        echo "env.url=${{env.url}}"
        gh pr edit "${{env.url}}" --add-reviewer lvessiller-opendsi

    - name: Assign reviewer 2
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        url: ${{ github.event.pull_request.html_url }}
      run: |
        echo "env.url=${{env.url}}"
        gh pr edit "${{env.url}}" --add-reviewer rycks
