on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "18.0"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    #- name: Authenticate GitHub CLI
    #  env:
    #    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #  run: gh auth login --with-token <<< "$GH_TOKEN"

    - name: Log var
      run: echo "The value of the organization variable is ${{vars.AAA}} ${{vars.BBB}} ${{vars.CCC}} !"

    - name: Assign reviewer
      env:
        AAA: "${{ vars.AAA }}"
        BBB: "${{ vars.BBB }}"
        CCC: "${{ vars.CCC }}"
        GITHUB_TOKEN: ${{ github.token }}
        REVIEWER: "rycks" # Remplacez par le nom d'utilisateur GitHub du reviewer
      run: |
        pr_number=$(jq --raw-output .number < $GITHUB_EVENT_PATH)
        gh pr edit $pr_number --add-reviewer "$REVIEWER"
        # test
