name: tmp phpstan td dump

on:
  push:
    branches:
      - tmp-phpstan-td-dump

permissions:
  contents: read
  pull-requests: write

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Dump source regions
        run: |
          {
            echo "SOURCE REGION DUMP v3"
            echo ""
            echo '~~~ actions_massactions.inc.php 1280-1330'
            sed -n '1280,1330p' htdocs/core/actions_massactions.inc.php
            echo '~~~ commonobject.class.php 3020,3070'
            sed -n '3020,3070p' htdocs/core/class/commonobject.class.php
            echo '~~~ commonobject.class.php 3070,3240'
            sed -n '3070,3240p' htdocs/core/class/commonobject.class.php
            echo '~~~'
          } > td_comment.md

      - name: Publish result on temp PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment 41399 --repo Dolibarr/dolibarr --body-file td_comment.md
